encounter 0x14, EnemySpawn_0800b8a8
    encounter 0x14, EnemySpawn_0800b8b4
    encounter 0x14, EnemySpawn_0800b8c0
    encounter 0x14, EnemySpawn_0800b8cc
    encounter 0x14, EnemySpawn_0800b8d8
    encounter 0x14, EnemySpawn_0800b8e4
    encounter 0x14, EnemySpawn_0800b8f0
    encounter 0x14, EnemySpawn_0800b8fc
    encounter 0x0C, EnemySpawn_0800b908
    encounter 0x0C, EnemySpawn_0800b918
    encounter 0x0C, EnemySpawn_0800b928
    encounter 0x0C, EnemySpawn_0800b938
    encounter 0x0C, EnemySpawn_0800b948
    encounter 0x0C, EnemySpawn_0800b958
    encounter 0x0C, EnemySpawn_0800b968
    encounter 0x0C, EnemySpawn_0800b974
EnemySpawn_0800b8a8:
    spawn Flappy1, 5, 2
    spawn Spooky1, 6, 1
    spawn_end

EnemySpawn_0800b8b4:
    spawn Canodumb1, 4, 1
    spawn Beetank1, 6, 3
    spawn_end

EnemySpawn_0800b8c0:
    spawn Flappy1, 5, 1
    spawn Flappy1, 6, 3
    spawn_end

EnemySpawn_0800b8cc:
    spawn Beetank1, 5, 3
    spawn Beetank1, 6, 1
    spawn_end

EnemySpawn_0800b8d8:
    spawn Spooky1, 4, 1
    spawn Handy1, 6, 2
    spawn_end

EnemySpawn_0800b8e4:
    spawn Canodumb1, 5, 2
    spawn Flappy1, 6, 2
    spawn_end

EnemySpawn_0800b8f0:
    spawn Handy1, 5, 3
    spawn Handy1, 6, 1
    spawn_end

EnemySpawn_0800b8fc:
    spawn Beetank1, 5, 2
    spawn Handy1, 6, 3
    spawn_end

EnemySpawn_0800b908:
    spawn Mettaur1, 4, 3
    spawn Mettaur1, 5, 1
    spawn Handy1, 6, 2
    spawn_end

EnemySpawn_0800b918:
    spawn Mettaur1, 4, 2
    spawn Spooky1, 5, 1
    spawn Spooky1, 6, 3
    spawn_end

EnemySpawn_0800b928:
    spawn Spooky1, 4, 1
    spawn Spooky1, 5, 3
    spawn Canodumb1, 6, 2
    spawn_end

EnemySpawn_0800b938:
    spawn Flappy1, 4, 3
    spawn Mettaur1, 5, 1
    spawn Flappy1, 6, 2
    spawn_end

EnemySpawn_0800b948:
    spawn Flappy1, 4, 2
    spawn Flappy1, 5, 1
    spawn Flappy1, 6, 3
    spawn_end

EnemySpawn_0800b958:
    spawn Spooky1, 4, 1
    spawn Spooky1, 5, 3
    spawn Beetank1, 6, 2
    spawn_end

EnemySpawn_0800b968:
    spawn Spooky1, 4, 2
    spawn Handy1, 5, 3
    spawn_end

EnemySpawn_0800b974:
    spawn Flappy1, 4, 3
    spawn Spooky1, 5, 2
    spawn Handy1, 6, 1
    spawn_end
