encounter 0x20, EnemySpawn_0800de4c
encounter 0x20, EnemySpawn_0800de54
encounter 0x20, EnemySpawn_0800de5c
encounter 0x20, EnemySpawn_0800de64
encounter 0x20, EnemySpawn_0800de6c
encounter 0x20, EnemySpawn_0800de78
encounter 0x20, EnemySpawn_0800de84
encounter 0x20, EnemySpawn_0800de90

EnemySpawn_0800de4c:
    spawn AquaPuffy, 5, 2
    spawn_end

EnemySpawn_0800de54:
    spawn HeatPuffy, 5, 2
    spawn_end

EnemySpawn_0800de5c:
    spawn HeatPuffy, 6, 2
    spawn_end

EnemySpawn_0800de64:
    spawn AquaPuffy, 6, 2
    spawn_end

EnemySpawn_0800de6c:
    spawn HeatPuffy, 5, 3
    spawn AquaPuffy, 6, 1
    spawn_end

EnemySpawn_0800de78:
    spawn AquaPuffy, 5, 1
    spawn HeatPuffy, 6, 3
    spawn_end

EnemySpawn_0800de84:
    spawn AquaPuffy, 4, 1
    spawn AquaPuffy, 6, 2
    spawn_end

EnemySpawn_0800de90:
    spawn HeatPuffy, 4, 3
    spawn HeatPuffy, 6, 1
    spawn_end
