encounter 0x20, EnemySpawn_0800e00c
encounter 0x20, EnemySpawn_0800e014
encounter 0x20, EnemySpawn_0800e01c
encounter 0x20, EnemySpawn_0800e028
encounter 0x20, EnemySpawn_0800e034
encounter 0x20, EnemySpawn_0800e044
encounter 0x20, EnemySpawn_0800e054
encounter 0x20, EnemySpawn_0800e064

EnemySpawn_0800e00c:
    spawn Piranha1, 5, 2
    spawn_end

EnemySpawn_0800e014:
    spawn Piranha2, 5, 2
    spawn_end

EnemySpawn_0800e01c:
    spawn Piranha1, 5, 1
    spawn Piranha1, 6, 3
    spawn_end

EnemySpawn_0800e028:
    spawn Piranha2, 4, 3
    spawn Piranha2, 6, 1
    spawn_end

EnemySpawn_0800e034:
    spawn Piranha1, 4, 1
    spawn Piranha1, 5, 3
    spawn Piranha1, 6, 2
    spawn_end

EnemySpawn_0800e044:
    spawn Piranha2, 4, 2
    spawn Piranha2, 5, 1
    spawn Piranha2, 6, 2
    spawn_end

EnemySpawn_0800e054:
    spawn Piranha1, 4, 1
    spawn Piranha2, 5, 3
    spawn Piranha1, 6, 2
    spawn_end

EnemySpawn_0800e064:
    spawn Piranha2, 4, 2
    spawn Piranha1, 5, 3
    spawn Piranha2, 6, 1
    spawn_end
