global_label encounterGroupOther

.word encounterList_0800db10 @ Doghouse
.word encounterList_0800dba8 @ Servbot
.word encounterList_0800dc3c @ New Game Machine
.word encounterList_0800dcd4 @ Telephone
.word encounterList_0800dd6c @ Car
.word encounterList_0800de0c @ Vending Machine Waterworks
.word encounterList_0800de9c @ Lobby TV
.word encounterList_0800df30 @ Large Monitor
.word encounterList_0800dfcc @ COntrol Equipment
.word encounterList_0800e074 @ Vending Machine Scilab
.word encounterList_0800e104 @ Recycled PET
.word encounterList_0800e198 @ Big Vase
.word encounterList_0800e230 @ Blackboard

encounterList_0800db10: .include "data/encounter/Other/0.inc"
encounterList_0800dba8: .include "data/encounter/Other/1.inc"
encounterList_0800dc3c: .include "data/encounter/Other/2.inc"
encounterList_0800dcd4: .include "data/encounter/Other/3.inc"
encounterList_0800dd6c: .include "data/encounter/Other/4.inc"
encounterList_0800de0c: .include "data/encounter/Other/5.inc"
encounterList_0800de9c: .include "data/encounter/Other/6.inc"
encounterList_0800df30: .include "data/encounter/Other/7.inc"
encounterList_0800dfcc: .include "data/encounter/Other/8.inc"
encounterList_0800e074: .include "data/encounter/Other/9.inc"
encounterList_0800e104: .include "data/encounter/Other/10.inc"
encounterList_0800e198: .include "data/encounter/Other/11.inc"
encounterList_0800e230: .include "data/encounter/Other/12.inc"
