global_label encounterGroupOther

.word encounterList_0800db10
.word encounterList_0800dba8
.word encounterList_0800dc3c
.word encounterList_0800dcd4
.word encounterList_0800dd6c
.word encounterList_0800de0c
.word encounterList_0800de9c
.word encounterList_0800df30
.word encounterList_0800dfcc
.word encounterList_0800e074
.word encounterList_0800e104
.word encounterList_0800e198
.word encounterList_0800e230

encounterList_0800db10: .include "data/encounter/Other/0.inc"
encounterList_0800dba8: .include "data/encounter/Other/1.inc"
encounterList_0800dc3c: .include "data/encounter/Other/2.inc"
encounterList_0800dcd4: .include "data/encounter/Other/3.inc"
encounterList_0800dd6c: .include "data/encounter/Other/4.inc"
encounterList_0800de0c: .include "data/encounter/Other/5.inc"
encounterList_0800de9c: .include "data/encounter/Other/6.inc"
encounterList_0800df30: .include "data/encounter/Other/7.inc"
encounterList_0800dfcc: .include "data/encounter/Other/8.inc"
encounterList_0800e074: .include "data/encounter/Other/9.inc"
encounterList_0800e104: .include "data/encounter/Other/10.inc"
encounterList_0800e198: .include "data/encounter/Other/11.inc"
encounterList_0800e230: .include "data/encounter/Other/12.inc"
