encounter 0x0C, EnemySpawn_0800c224
encounter 0x0C, EnemySpawn_0800c22c
encounter 0x0C, EnemySpawn_0800c238
encounter 0x0C, EnemySpawn_0800c244
encounter 0x0C, EnemySpawn_0800c250
encounter 0x0C, EnemySpawn_0800c25c
encounter 0x0C, EnemySpawn_0800c268
encounter 0x0C, EnemySpawn_0800c274
encounter 0x14, EnemySpawn_0800c280
encounter 0x14, EnemySpawn_0800c290
encounter 0x14, EnemySpawn_0800c29c
encounter 0x14, EnemySpawn_0800c2a8
encounter 0x14, EnemySpawn_0800c2b8
encounter 0x14, EnemySpawn_0800c2c4
encounter 0x14, EnemySpawn_0800c2d4
encounter 0x14, EnemySpawn_0800c2e0

EnemySpawn_0800c224:
    spawn AquaPuffy, 5, 2
    spawn_end

EnemySpawn_0800c22c:
    spawn AquaPuffy, 5, 2
    spawn Spooky2, 6, 1
    spawn_end

EnemySpawn_0800c238:
    spawn AquaPuffy, 5, 2
    spawn Fishy1, 6, 3
    spawn_end

EnemySpawn_0800c244:
    spawn AquaPuffy, 5, 3
    spawn AquaPuffy, 6, 1
    spawn_end

EnemySpawn_0800c250:
    spawn Vatgear, 4, 2
    spawn Spooky2, 6, 2
    spawn_end

EnemySpawn_0800c25c:
    spawn Cloudy1, 5, 3
    spawn AquaPuffy, 5, 1
    spawn_end

EnemySpawn_0800c268:
    spawn Fishy1, 4, 1
    spawn Spooky2, 6, 3
    spawn_end

EnemySpawn_0800c274:
    spawn Spooky2, 4, 3
    spawn Spooky2, 5, 1
    spawn_end

EnemySpawn_0800c280:
    spawn Fishy1, 4, 1
    spawn Fishy1, 5, 3
    spawn AquaPuffy, 6, 2
    spawn_end

EnemySpawn_0800c290:
    spawn Vatgear, 4, 3
    spawn Fishy1, 5, 2
    spawn_end

EnemySpawn_0800c29c:
    spawn Fishy1, 5, 2
    spawn AquaPuffy, 6, 1
    spawn_end

EnemySpawn_0800c2a8:
    spawn Piranha1, 4, 1
    spawn Piranha1, 5, 2
    spawn Piranha1, 6, 3
    spawn_end

EnemySpawn_0800c2b8:
    spawn Piranha1, 4, 1
    spawn Vatgear, 5, 3
    spawn_end

EnemySpawn_0800c2c4:
    spawn Piranha1, 4, 3
    spawn Piranha1, 4, 1
    spawn Fishy1, 6, 2
    spawn_end

EnemySpawn_0800c2d4:
    spawn AquaPuffy, 5, 3
    spawn Spooky2, 6, 2
    spawn_end

EnemySpawn_0800c2e0:
    spawn Cloudy1, 4, 3
    spawn Spooky2, 6, 1
    spawn_end
