encounter 0x14, EnemySpawn_0800c36c
encounter 0x14, EnemySpawn_0800c374
encounter 0x14, EnemySpawn_0800c380
encounter 0x14, EnemySpawn_0800c38c
encounter 0x14, EnemySpawn_0800c398
encounter 0x14, EnemySpawn_0800c3a4
encounter 0x14, EnemySpawn_0800c3b0
encounter 0x14, EnemySpawn_0800c3bc
encounter 0x0C, EnemySpawn_0800c3c8
encounter 0x0C, EnemySpawn_0800c3d8
encounter 0x0C, EnemySpawn_0800c3e8
encounter 0x0C, EnemySpawn_0800c3f4
encounter 0x0C, EnemySpawn_0800c400
encounter 0x0C, EnemySpawn_0800c410
encounter 0x0C, EnemySpawn_0800c420
encounter 0x0C, EnemySpawn_0800c430

EnemySpawn_0800c36c:
    spawn Swordy3, 5, 2
    spawn_end

EnemySpawn_0800c374:
    spawn Vatgear, 4, 3
    spawn Swordy3, 6, 1
    spawn_end

EnemySpawn_0800c380:
    spawn Swordy3, 5, 3
    spawn AquaPuffy, 6, 1
    spawn_end

EnemySpawn_0800c38c:
    spawn Swordy3, 5, 1
    spawn Swordy3, 6, 3
    spawn_end

EnemySpawn_0800c398:
    spawn Swordy3, 4, 3
    spawn Spooky2, 6, 1
    spawn_end

EnemySpawn_0800c3a4:
    spawn Swordy3, 5, 2
    spawn Fishy1, 6, 2
    spawn_end

EnemySpawn_0800c3b0:
    spawn Vatgear, 5, 1
    spawn Vatgear, 6, 3
    spawn_end

EnemySpawn_0800c3bc:
    spawn Cloudy1, 5, 2
    spawn Canodumb2, 6, 1
    spawn_end

EnemySpawn_0800c3c8:
    spawn Piranha1, 4, 1
    spawn Swordy3, 5, 2
    spawn Piranha1, 6, 2
    spawn_end

EnemySpawn_0800c3d8:
    spawn Piranha1, 4, 3
    spawn Piranha1, 4, 1
    spawn AquaPuffy, 6, 1
    spawn_end

EnemySpawn_0800c3e8:
    spawn Piranha1, 4, 1
    spawn Cloudy1, 5, 2
    spawn_end

EnemySpawn_0800c3f4:
    spawn Swordy3, 4, 1
    spawn Piranha1, 5, 3
    spawn_end

EnemySpawn_0800c400:
    spawn Swordy3, 4, 2
    spawn Swordy3, 5, 3
    spawn Spooky2, 6, 1
    spawn_end

EnemySpawn_0800c410:
    spawn Fishy1, 4, 3
    spawn Swordy3, 5, 1
    spawn Fishy1, 6, 2
    spawn_end

EnemySpawn_0800c420:
    spawn Vatgear, 4, 2
    spawn Swordy3, 5, 1
    spawn AquaPuffy, 6, 3
    spawn_end

EnemySpawn_0800c430:
    spawn Swordy3, 4, 3
    spawn Piranha1, 6, 1
    spawn_end
