global_label encounterGroupWaterworksComp

.word encounterList_0800bdcc @ Waterworks Comp 1
.word encounterList_0800bf14 @ Waterworks Comp 2
.word encounterList_0800c05c @ Waterworks Comp 3
.word encounterList_0800c1a4 @ Waterworks Comp 4
.word encounterList_0800c2ec @ Waterworks Comp 5
.word encounterList_0800c43c @ Waterworks Comp 6

encounterList_0800bdcc: .include "data/encounter/WaterworksComp/0.inc"
encounterList_0800bf14: .include "data/encounter/WaterworksComp/1.inc"
encounterList_0800c05c: .include "data/encounter/WaterworksComp/2.inc"
encounterList_0800c1a4: .include "data/encounter/WaterworksComp/3.inc"
encounterList_0800c2ec: .include "data/encounter/WaterworksComp/4.inc"
encounterList_0800c43c: .include "data/encounter/WaterworksComp/5.inc"
