global_label EncounterData_Other_Comp

.word encounterList_Doghouse_Comp
.word encounterList_Servbot_Comp
.word encounterList_New_Game_Machine_Comp
.word encounterList_Telephone_Comp
.word encounterList_Car_Comp
.word encounterList_Waterworks_Vending_Machine_Comp
.word encounterList_TV_Comp
.word encounterList_Large_Monitor_Comp
.word encounterList_Control_Equipment_Comp
.word encounterList_SciLab_Vending_Machine_Comp
.word encounterList_Recycled_PET_Comp
.word encounterList_Big_Vase_Comp
.word encounterList_Blackboard_Comp

encounterList_Doghouse_Comp:                    .include "data/encounter/Other_Comp/Doghouse_Comp.inc"
encounterList_Servbot_Comp:                     .include "data/encounter/Other_Comp/Servbot_Comp.inc"
encounterList_New_Game_Machine_Comp:            .include "data/encounter/Other_Comp/New_Game_Machine_Comp.inc"
encounterList_Telephone_Comp:                   .include "data/encounter/Other_Comp/Telephone_Comp.inc"
encounterList_Car_Comp:                         .include "data/encounter/Other_Comp/Car_Comp.inc"
encounterList_Waterworks_Vending_Machine_Comp:  .include "data/encounter/Other_Comp/Waterworks_Vending_Machine_Comp.inc"
encounterList_TV_Comp:                          .include "data/encounter/Other_Comp/TV_Comp.inc"
encounterList_Large_Monitor_Comp:               .include "data/encounter/Other_Comp/Large_Monitor_Comp.inc"
encounterList_Control_Equipment_Comp:           .include "data/encounter/Other_Comp/Control_Equipment_Comp.inc"
encounterList_SciLab_Vending_Machine_Comp:      .include "data/encounter/Other_Comp/SciLab_Vending_Machine_Comp.inc"
encounterList_Recycled_PET_Comp:                .include "data/encounter/Other_Comp/Recycled_PET_Comp.inc"
encounterList_Big_Vase_Comp:                    .include "data/encounter/Other_Comp/Big_Vase_Comp.inc"
encounterList_Blackboard_Comp:                  .include "data/encounter/Other_Comp/Blackboard_Comp.inc"
