encounter 0x20, EnemySpawn_0800dd14
encounter 0x20, EnemySpawn_0800dd1c
encounter 0x20, EnemySpawn_0800dd24
encounter 0x20, EnemySpawn_0800dd2c
encounter 0x20, EnemySpawn_0800dd38
encounter 0x20, EnemySpawn_0800dd44
encounter 0x20, EnemySpawn_0800dd50
encounter 0x20, EnemySpawn_0800dd60

EnemySpawn_0800dd14:
    spawn Fishy1, 5, 2
    spawn_end

EnemySpawn_0800dd1c:
    spawn Mettaur1, 5, 2
    spawn_end

EnemySpawn_0800dd24:
    spawn Mettaur1, 4, 2
    spawn_end

EnemySpawn_0800dd2c:
    spawn Fishy1, 4, 2
    spawn Fishy1, 6, 2
    spawn_end

EnemySpawn_0800dd38:
    spawn Fishy1, 5, 1
    spawn Fishy1, 6, 3
    spawn_end

EnemySpawn_0800dd44:
    spawn Fishy1, 5, 3
    spawn Swordy1, 6, 2
    spawn_end

EnemySpawn_0800dd50:
    spawn Fishy1, 4, 3
    spawn Fishy1, 5, 1
    spawn Fishy1, 6, 2
    spawn_end

EnemySpawn_0800dd60:
    spawn Swordy1, 4, 1
    spawn Swordy1, 6, 3
    spawn_end
