encounter 0x20, EnemySpawn_0800dedc
encounter 0x20, EnemySpawn_0800dee4
encounter 0x20, EnemySpawn_0800deec
encounter 0x20, EnemySpawn_0800def4
encounter 0x20, EnemySpawn_0800defc
encounter 0x20, EnemySpawn_0800df08
encounter 0x20, EnemySpawn_0800df14
encounter 0x20, EnemySpawn_0800df20

EnemySpawn_0800dedc:
    spawn Cloudy1, 5, 2
    spawn_end

EnemySpawn_0800dee4:
    spawn Ratty1, 5, 2
    spawn_end

EnemySpawn_0800deec:
    spawn Cloudy1, 4, 2
    spawn_end

EnemySpawn_0800def4:
    spawn Ratty1, 6, 2
    spawn_end

EnemySpawn_0800defc:
    spawn Ratty1, 5, 3
    spawn Ratty1, 6, 1
    spawn_end

EnemySpawn_0800df08:
    spawn Cloudy1, 4, 3
    spawn Ratty1, 5, 2
    spawn_end

EnemySpawn_0800df14:
    spawn Ratty1, 4, 3
    spawn Cloudy1, 5, 1
    spawn_end

EnemySpawn_0800df20:
    spawn Ratty1, 4, 3
    spawn Ratty1, 5, 1
    spawn Ratty1, 6, 3
    spawn_end
