global_label EnemySpawn_0800b220
    spawn GutsManV1, 5, 2
    spawn_end

global_label EnemySpawn_0800b228
    spawn GutsManV2, 5, 2
    spawn_end

global_label EnemySpawn_0800b230
    spawn GutsManV3, 5, 2
    spawn_end

global_label EnemySpawn_0800b238
    spawn Mettaur1, 5, 2
    spawn_end

global_label EnemySpawn_0800b240
    spawn FireManV1, 5, 2
    spawn_end

global_label EnemySpawn_0800b248
    spawn NumberManV1, 6, 2
    spawn_end

global_label EnemySpawn_0800b250
    spawn NumberManV2, 6, 2
    spawn_end

global_label EnemySpawn_0800b258
    spawn NumberManV3, 6, 2
    spawn_end

global_label EnemySpawn_0800b260
    spawn StoneManV1, 6, 2
    spawn_end

global_label EnemySpawn_0800b268
    spawn StoneManV2, 6, 2
    spawn_end

global_label EnemySpawn_0800b270
    spawn ColdBear2, 5, 1
    spawn ColdBear3, 5, 3
    spawn_end

global_label EnemySpawn_0800b27c
    spawn IceManV1, 6, 2
    spawn_end

global_label EnemySpawn_0800b284
    spawn IceManV2, 6, 2
    spawn_end

global_label EnemySpawn_0800b28c
    spawn IceManV3, 6, 2
    spawn_end

global_label EnemySpawn_0800b294
    spawn ColorManV1, 6, 2
    spawn BlueDummyV1, 5, 3
    spawn RedDummyV1, 4, 1
    spawn_end

global_label EnemySpawn_0800b2a4
    spawn ColorManV2, 6, 2
    spawn BlueDummyV2, 5, 3
    spawn RedDummyV2, 4, 1
    spawn_end

    spawn ColorManV3, 6, 2
    spawn BlueDummyV3, 5, 3
    spawn RedDummyV3, 4, 1
    spawn_end

global_label EnemySpawn_0800b2c4
    spawn InvElecMan, 5, 2
    spawn_end

global_label EnemySpawn_0800b2cc
    spawn ElecManV1, 5, 2
    spawn_end

global_label EnemySpawn_0800b2d4
    spawn ElecManV2, 5, 2
    spawn_end

global_label EnemySpawn_0800b2dc
    spawn WoodManV1, 5, 2
    spawn_end

global_label EnemySpawn_0800b2e4
    spawn WoodManV2, 5, 2
    spawn_end

global_label EnemySpawn_0800b2ec
    spawn WoodManV3, 5, 2
    spawn_end

global_label EnemySpawn_0800b2f4
    spawn SharkManV1, 5, 2
    spawn_end

global_label EnemySpawn_0800b2fc
    spawn SharkManV2, 5, 2
    spawn_end

global_label EnemySpawn_0800b304
    spawn SharkManV3, 5, 2
    spawn_end

global_label EnemySpawn_0800b30c
    spawn SkullManV1, 5, 2
    spawn_end

global_label EnemySpawn_0800b314
    spawn SkullManV2, 5, 2
    spawn_end

global_label EnemySpawn_0800b31c
    spawn SkullManV3, 5, 2
    spawn_end

global_label EnemySpawn_0800b324
    spawn FireManV2, 5, 2
    spawn_end

global_label EnemySpawn_0800b32c
    spawn ProtoManV1, 5, 2
    spawn_end

global_label EnemySpawn_0800b334
    spawn ProtoManV2, 5, 2
    spawn_end

global_label EnemySpawn_0800b33c
    spawn ProtoManV3, 5, 2
    spawn_end

global_label EnemySpawn_0800b344
    spawn Froshell3, 5, 2
    spawn HardHead3, 4, 3
    spawn HardHead3, 6, 1
    spawn_end

global_label EnemySpawn_0800b354
    spawn Prog1, 6, 2
    spawn_end

global_label EnemySpawn_0800b35c
    spawn Prog2, 6, 2
    spawn_end

global_label EnemySpawn_0800b364
    spawn Prog3, 5, 2
    spawn_end

global_label EnemySpawn_0800b36c
    spawn BombManV1, 6, 2
    spawn_end

global_label EnemySpawn_0800b374
    spawn BombManV2, 6, 2
    spawn_end

    spawn BombManV3, 6, 2
    spawn_end

global_label EnemySpawn_0800b384
    spawn MagicManV1, 6, 2
    spawn_end

global_label EnemySpawn_0800b38c
    spawn MagicManV2, 6, 2
    spawn_end

    spawn MagicManV3, 6, 2
    spawn_end

global_label EnemySpawn_0800b39c
    spawn LifeVirus, 5, 2
    spawn_end

global_label EnemySpawn_0800b3a4
    spawn HardHead2, 4, 1
    spawn HardHead2, 4, 3
    spawn Froshell2, 5, 2
    spawn_end

global_label EnemySpawn_0800b3b4
    spawn ColdBear3, 4, 1
    spawn ColdBear3, 4, 3
    spawn_end

global_label EnemySpawn_0800b3c0
    spawn PharaohManV1, 6, 2
    spawn_end

    spawn PharaohManV2, 6, 2
    spawn_end

    spawn PharaohManV3, 6, 2
    spawn_end

global_label EnemySpawn_0800b3d8
    spawn ShadowManV1, 5, 2
    spawn_end

    spawn ShadowManV2, 5, 2
    spawn_end

    spawn ShadowManV3, 5, 2
    spawn_end
