encounter 0x20, EnemySpawn_0800c5e0
encounter 0x20, EnemySpawn_0800c5ec
encounter 0x20, EnemySpawn_0800c5fc
encounter 0x20, EnemySpawn_0800c608
encounter 0x20, EnemySpawn_0800c614
encounter 0x20, EnemySpawn_0800c620
encounter 0x20, EnemySpawn_0800c62c
encounter 0x20, EnemySpawn_0800c638

EnemySpawn_0800c5e0:
    spawn Mettaur2, 5, 3
    spawn Mettaur2, 5, 1
    spawn_end

EnemySpawn_0800c5ec:
    spawn AquaPuffy, 4, 1
    spawn Mettaur2, 5, 2
    spawn HeatPuffy, 6, 3
    spawn_end

EnemySpawn_0800c5fc:
    spawn Mettaur2, 5, 2
    spawn AquaPuffy, 6, 1
    spawn_end

EnemySpawn_0800c608:
    spawn Vulgear, 5, 1
    spawn Vatgear, 6, 3
    spawn_end

EnemySpawn_0800c614:
    spawn Vatgear, 5, 2
    spawn Vulgear, 6, 1
    spawn_end

EnemySpawn_0800c620:
    spawn Vatgear, 4, 3
    spawn Mettaur2, 6, 1
    spawn_end

EnemySpawn_0800c62c:
    spawn Vatgear, 6, 3
    spawn AquaPuffy, 6, 2
    spawn_end

EnemySpawn_0800c638:
    spawn Vulgear, 4, 1
    spawn HeatPuffy, 6, 3
    spawn_end
