encounter 0x20, EnemySpawn_0800d878
encounter 0x20, EnemySpawn_0800d880
encounter 0x20, EnemySpawn_0800d890
encounter 0x20, EnemySpawn_0800d8a0
encounter 0x20, EnemySpawn_0800d8ac
encounter 0x20, EnemySpawn_0800d8bc
encounter 0x20, EnemySpawn_0800d8cc
encounter 0x20, EnemySpawn_0800d8d8

EnemySpawn_0800d878:
    spawn Mettaur2, 5, 2
    spawn_end

EnemySpawn_0800d880:
    spawn Mettaur1, 4, 1
    spawn Mettaur2, 5, 3
    spawn Mettaur1, 6, 2
    spawn_end

EnemySpawn_0800d890:
    spawn Mettaur1, 4, 2
    spawn Mettaur2, 5, 1
    spawn Mettaur2, 6, 3
    spawn_end

EnemySpawn_0800d8a0:
    spawn Mettaur1, 5, 3
    spawn Mettaur2, 5, 1
    spawn_end

EnemySpawn_0800d8ac:
    spawn Mettaur1, 4, 3
    spawn Mettaur1, 4, 2
    spawn Mettaur1, 4, 1
    spawn_end

EnemySpawn_0800d8bc:
    spawn Mettaur1, 4, 3
    spawn Mettaur1, 5, 1
    spawn Beetank1, 6, 2
    spawn_end

EnemySpawn_0800d8cc:
    spawn Beetank1, 5, 3
    spawn Beetank1, 6, 1
    spawn_end

EnemySpawn_0800d8d8:
    spawn Mettaur2, 5, 2
    spawn Beetank1, 6, 2
    spawn_end
