encounter 0x14, EnemySpawn_0800cdfc
encounter 0x14, EnemySpawn_0800ce04
encounter 0x14, EnemySpawn_0800ce10
encounter 0x14, EnemySpawn_0800ce20
encounter 0x14, EnemySpawn_0800ce2c
encounter 0x14, EnemySpawn_0800ce38
encounter 0x14, EnemySpawn_0800ce44
encounter 0x14, EnemySpawn_0800ce50
encounter 0x0C, EnemySpawn_0800ce5c
encounter 0x0C, EnemySpawn_0800ce64
encounter 0x0C, EnemySpawn_0800ce74
encounter 0x0C, EnemySpawn_0800ce84
encounter 0x0C, EnemySpawn_0800ce94
encounter 0x0C, EnemySpawn_0800cea4
encounter 0x0C, EnemySpawn_0800ceb4
encounter 0x0C, EnemySpawn_0800cec4

EnemySpawn_0800cdfc:
    spawn Prog2, 5, 2
    spawn_end

EnemySpawn_0800ce04:
    spawn Prog2, 5, 1
    spawn Prog2, 6, 3
    spawn_end

EnemySpawn_0800ce10:
    spawn Prog1, 4, 1
    spawn Prog1, 5, 3
    spawn Remobit1, 6, 2
    spawn_end

EnemySpawn_0800ce20:
    spawn Prog2, 5, 3
    spawn Remobit1, 6, 1
    spawn_end

EnemySpawn_0800ce2c:
    spawn Fanner1, 4, 3
    spawn Remobit1, 6, 1
    spawn_end

EnemySpawn_0800ce38:
    spawn Ratty1, 5, 1
    spawn Remobit1, 6, 2
    spawn_end

EnemySpawn_0800ce44:
    spawn Billy, 4, 2
    spawn Remobit1, 6, 3
    spawn_end

EnemySpawn_0800ce50:
    spawn Canodumb2, 5, 2
    spawn Remobit1, 6, 2
    spawn_end

EnemySpawn_0800ce5c:
    spawn Remobit1, 5, 2
    spawn_end

EnemySpawn_0800ce64:
    spawn Ratty1, 4, 3
    spawn Ratty1, 5, 1
    spawn Ratty1, 6, 3
    spawn_end

EnemySpawn_0800ce74:
    spawn Ratty1, 5, 3
    spawn Prog2, 5, 1
    spawn Ratty1, 6, 2
    spawn_end

EnemySpawn_0800ce84:
    spawn Canodumb2, 4, 3
    spawn Canodumb2, 5, 1
    spawn Remobit1, 6, 2
    spawn_end

EnemySpawn_0800ce94:
    spawn Canodumb2, 5, 2
    spawn Ratty1, 6, 3
    spawn Ratty1, 6, 1
    spawn_end

EnemySpawn_0800cea4:
    spawn Billy, 4, 1
    spawn Billy, 5, 3
    spawn Canodumb2, 6, 1
    spawn_end

EnemySpawn_0800ceb4:
    spawn Remobit1, 4, 3
    spawn Prog1, 5, 2
    spawn Billy, 6, 1
    spawn_end

EnemySpawn_0800cec4:
    spawn Fanner1, 4, 3
    spawn Fanner1, 5, 1
    spawn Fanner1, 6, 2
    spawn_end
