encounter 0x10, EnemySpawn_0800cf54
encounter 0x10, EnemySpawn_0800cf5c
encounter 0x10, EnemySpawn_0800cf68
encounter 0x10, EnemySpawn_0800cf74
encounter 0x10, EnemySpawn_0800cf80
encounter 0x10, EnemySpawn_0800cf8c
encounter 0x10, EnemySpawn_0800cf98
encounter 0x10, EnemySpawn_0800cfa4
encounter 0x10, EnemySpawn_0800cfb0
encounter 0x10, EnemySpawn_0800cfc0
encounter 0x10, EnemySpawn_0800cfd0
encounter 0x10, EnemySpawn_0800cfe0
encounter 0x10, EnemySpawn_0800cff0
encounter 0x10, EnemySpawn_0800d000
encounter 0x10, EnemySpawn_0800d010
encounter 0x10, EnemySpawn_0800d020

EnemySpawn_0800cf54:
    spawn Prog3, 5, 2
    spawn_end

EnemySpawn_0800cf5c:
    spawn Prog3, 5, 1
    spawn Prog3, 6, 3
    spawn_end

EnemySpawn_0800cf68:
    spawn Prog2, 4, 3
    spawn Prog2, 6, 1
    spawn_end

EnemySpawn_0800cf74:
    spawn Prog3, 5, 2
    spawn Remobit1, 6, 2
    spawn_end

EnemySpawn_0800cf80:
    spawn Fanner1, 5, 3
    spawn Remobit1, 6, 3
    spawn_end

EnemySpawn_0800cf8c:
    spawn Billy, 4, 3
    spawn Billy, 4, 1
    spawn_end

EnemySpawn_0800cf98:
    spawn Fanner1, 4, 3
    spawn Canodumb3, 5, 2
    spawn_end

EnemySpawn_0800cfa4:
    spawn Fanner1, 4, 3
    spawn Fanner1, 5, 1
    spawn_end

EnemySpawn_0800cfb0:
    spawn Prog3, 4, 2
    spawn Canodumb3, 5, 3
    spawn Remobit1, 6, 3
    spawn_end

EnemySpawn_0800cfc0:
    spawn Canodumb3, 4, 1
    spawn Canodumb3, 5, 2
    spawn Remobit1, 6, 1
    spawn_end

EnemySpawn_0800cfd0:
    spawn Canodumb3, 4, 3
    spawn Remobit1, 5, 3
    spawn Billy, 5, 2
    spawn_end

EnemySpawn_0800cfe0:
    spawn Ratty1, 4, 2
    spawn Ratty1, 5, 2
    spawn Remobit1, 6, 2
    spawn_end

EnemySpawn_0800cff0:
    spawn Ratty1, 4, 1
    spawn Fanner1, 5, 2
    spawn Remobit1, 6, 3
    spawn_end

EnemySpawn_0800d000:
    spawn Billy, 4, 1
    spawn Fanner1, 5, 3
    spawn Billy, 6, 2
    spawn_end

EnemySpawn_0800d010:
    spawn Billy, 4, 2
    spawn Fanner1, 5, 1
    spawn Fanner1, 6, 3
    spawn_end

EnemySpawn_0800d020:
    spawn Billy, 4, 1
    spawn Fanner1, 5, 3
    spawn Billy, 5, 2
    spawn_end
