encounter 0x14, EnemySpawn_0800cca8
encounter 0x14, EnemySpawn_0800ccb0
encounter 0x14, EnemySpawn_0800ccbc
encounter 0x14, EnemySpawn_0800ccc8
encounter 0x14, EnemySpawn_0800ccd4
encounter 0x14, EnemySpawn_0800ccdc
encounter 0x14, EnemySpawn_0800cce8
encounter 0x14, EnemySpawn_0800ccf4
encounter 0x0C, EnemySpawn_0800cd00
encounter 0x0C, EnemySpawn_0800cd0c
encounter 0x0C, EnemySpawn_0800cd1c
encounter 0x0C, EnemySpawn_0800cd2c
encounter 0x0C, EnemySpawn_0800cd3c
encounter 0x0C, EnemySpawn_0800cd4c
encounter 0x0C, EnemySpawn_0800cd5c
encounter 0x0C, EnemySpawn_0800cd6c

EnemySpawn_0800cca8:
    spawn Prog1, 6, 2
    spawn_end

EnemySpawn_0800ccb0:
    spawn Billy, 5, 3
    spawn Prog1, 6, 2
    spawn_end

EnemySpawn_0800ccbc:
    spawn Ratty1, 5, 3
    spawn Prog1, 5, 1
    spawn_end

EnemySpawn_0800ccc8:
    spawn Prog1, 5, 1
    spawn Prog1, 6, 3
    spawn_end

EnemySpawn_0800ccd4:
    spawn Fanner1, 5, 2
    spawn_end

EnemySpawn_0800ccdc:
    spawn Fanner1, 4, 1
    spawn Fanner1, 5, 3
    spawn_end

EnemySpawn_0800cce8:
    spawn Fanner1, 5, 1
    spawn Billy, 6, 3
    spawn_end

EnemySpawn_0800ccf4:
    spawn Fanner1, 5, 1
    spawn Ratty1, 6, 1
    spawn_end

EnemySpawn_0800cd00:
    spawn Fanner1, 4, 1
    spawn Prog1, 6, 3
    spawn_end

EnemySpawn_0800cd0c:
    spawn Canodumb2, 5, 3
    spawn Canodumb2, 5, 1
    spawn Prog1, 6, 2
    spawn_end

EnemySpawn_0800cd1c:
    spawn Canodumb2, 5, 3
    spawn Fanner1, 5, 1
    spawn Canodumb2, 6, 2
    spawn_end

EnemySpawn_0800cd2c:
    spawn Ratty1, 4, 1
    spawn Fanner1, 5, 3
    spawn Billy, 6, 2
    spawn_end

EnemySpawn_0800cd3c:
    spawn Fanner1, 4, 3
    spawn Billy, 5, 1
    spawn Canodumb2, 6, 2
    spawn_end

EnemySpawn_0800cd4c:
    spawn Fanner1, 4, 3
    spawn Fanner1, 4, 1
    spawn Prog1, 6, 2
    spawn_end

EnemySpawn_0800cd5c:
    spawn Fanner1, 4, 3
    spawn Ratty1, 5, 1
    spawn Billy, 6, 3
    spawn_end

EnemySpawn_0800cd6c:
    spawn Billy, 4, 3
    spawn Billy, 5, 1
    spawn Billy, 6, 2
    spawn_end
