global_label tileset_078A9D4
    .incbin "data/maps/areas/Power_Plant_Comp/tileset_078A9D4.4bpp"

global_label palette_078B754
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B754.gbapal"

global_label palette_078B774
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B774.gbapal"

global_label palette_078B794
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B794.gbapal"

global_label palette_078B7B4
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B7B4.gbapal"

global_label palette_078B7D4
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B7D4.gbapal"

global_label palette_078B7F4
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B7F4.gbapal"

global_label palette_078B814
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B814.gbapal"

global_label palette_078B834
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B834.gbapal"

global_label palette_078B854
    .incbin "data/maps/areas/Power_Plant_Comp/palette_078B854.gbapal"

