global_label tileset_0787B74
    .incbin "data/maps/areas/Traffic_Light_Comp/tileset_0787B74.4bpp"

global_label tileset_0787D34
    .incbin "data/maps/areas/Traffic_Light_Comp/tileset_0787D34.4bpp"

global_label palette_078A834
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A834.gbapal"

global_label palette_078A894
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A894.gbapal"

global_label palette_078A8D4_0
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A8D4/0.gbapal"
global_label palette_078A8D4_1
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A8D4/1.gbapal"
global_label palette_078A8D4_2
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A8D4/2.gbapal"

global_label palette_078A934_0
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A934/0.gbapal"
global_label palette_078A934_1
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A934/1.gbapal"
global_label palette_078A934_2
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A934/2.gbapal"
global_label palette_078A934_3
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A934/3.gbapal"

global_label palette_078A9B4
    .incbin "data/maps/areas/Traffic_Light_Comp/palette_078A9B4.gbapal"
