global_label tileset_0784234
    .incbin "data/maps/areas/Waterworks_Comp/tileset_0784234.4bpp"

global_label tileset_0785034
    .incbin "data/maps/areas/Waterworks_Comp/tileset_0785034.4bpp"

global_label tileset_07854F4
    .incbin "data/maps/areas/Waterworks_Comp/tileset_07854F4.4bpp"

global_label palette_0787174
    .incbin "data/maps/areas/Waterworks_Comp/palette_0787174.gbapal"

global_label palette_0787194
    .incbin "data/maps/areas/Waterworks_Comp/palette_0787194.gbapal"

global_label tileset_07871B4
    .incbin "data/maps/areas/Waterworks_Comp/tileset_07871B4.4bpp"

