global_label BgData_Tileset_School_Class_5A
    .incbin "data/maps/offline/School_Class_5A.tilesetz" @ 0x3B0298
global_label BgData_Palette_School_Class_5A
    .incbin "data/maps/offline/School_Class_5A.palettez" @ 0x3B3230
global_label BgData_Tilemap_School_Class_5A
    .incbin "data/maps/offline/School_Class_5A.tilemapz" @ 0x3B33D4
global_label BgData_Tilemap_School_Class_5B
    .incbin "data/maps/offline/School_Class_5B.tilemapz" @ 0x3B4054
global_label BgData_Palette_School_Library
    .incbin "data/maps/offline/School_Library.palettez" @ 0x3B4CF4
global_label BgData_Tileset_School_Library
    .incbin "data/maps/offline/School_Library.tilesetz" @ 0x3B4E98
global_label BgData_Tilemap_School_Library
    .incbin "data/maps/offline/School_Library.tilemapz" @ 0x3B7980
global_label BgData_Tileset_School_2F_Hallway
    .incbin "data/maps/offline/School_2F_Hallway.tilesetz" @ 0x3B9148
global_label BgData_Palette_School_2F_Hallway
    .incbin "data/maps/offline/School_2F_Hallway.palettez" @ 0x3BBEC0
global_label BgData_Tilemap_School_2F_Hallway
    .incbin "data/maps/offline/School_2F_Hallway.tilemapz" @ 0x3BC064
global_label BgData_Palette_School_Class_1A
    .incbin "data/maps/offline/School_Class_1A.palettez" @ 0x3BF0B4
global_label BgData_Tilemap_School_Class_1A
    .incbin "data/maps/offline/School_Class_1A.tilemapz" @ 0x3BF258
global_label BgData_Palette_School_Class_1B
    .incbin "data/maps/offline/School_Class_1B.palettez" @ 0x3BFEF0
global_label BgData_Tilemap_School_Class_1B
    .incbin "data/maps/offline/School_Class_1B.tilemapz" @ 0x3C0094
global_label BgData_Palette_School_AV_Room
    .incbin "data/maps/offline/School_AV_Room.palettez" @ 0x3C0D04
global_label BgData_Tilemap_School_AV_Room
    .incbin "data/maps/offline/School_AV_Room.tilemapz" @ 0x3C0EA8
global_label BgData_Tileset_School_Infirmary
    .incbin "data/maps/offline/School_Infirmary.tilesetz" @ 0x3C1CA8
global_label BgData_Palette_School_Infirmary
    .incbin "data/maps/offline/School_Infirmary.palettez" @ 0x3C434C
global_label BgData_Tilemap_School_Infirmary
    .incbin "data/maps/offline/School_Infirmary.tilemapz" @ 0x3C44F0
global_label BgData_Tilemap_School_1F_Hallway
    .incbin "data/maps/offline/School_1F_Hallway.tilemapz" @ 0x3C51D4
global_label BgData_Palette_School_Cross_Hallway
    .incbin "data/maps/offline/School_Cross_Hallway.palettez" @ 0x3C8280
global_label BgData_Tilemap_School_Cross_Hallway
    .incbin "data/maps/offline/School_Cross_Hallway.tilemapz" @ 0x3C8424
global_label BgData_Tileset_School_Storage
    .incbin "data/maps/offline/School_Storage.tilesetz" @ 0x3C8F94
global_label BgData_Palette_School_Storage
    .incbin "data/maps/offline/School_Storage.palettez" @ 0x3CBF18
global_label BgData_Tilemap_School_Storage
    .incbin "data/maps/offline/School_Storage.tilemapz" @ 0x3CC0BC
global_label BgData_Tileset_School_Staff_Lounge
    .incbin "data/maps/offline/School_Staff_Lounge.tilesetz" @ 0x3CD220
global_label BgData_Palette_School_Staff_Lounge
    .incbin "data/maps/offline/School_Staff_Lounge.palettez" @ 0x3CFBD0
global_label BgData_Tilemap_School_Staff_Lounge
    .incbin "data/maps/offline/School_Staff_Lounge.tilemapz" @ 0x3CFD74
global_label BgData_Palette_School_Staff_Lounge_Hallway
    .incbin "data/maps/offline/School_Staff_Lounge_Hallway.palettez" @ 0x3D10CC
global_label BgData_Tilemap_School_Staff_Lounge_Hallway
    .incbin "data/maps/offline/School_Staff_Lounge_Hallway.tilemapz" @ 0x3D1270
global_label BgData_Tileset_ACDC_Town
    .incbin "data/maps/offline/ACDC_Town.tilesetz" @ 0x3D22F0
global_label BgData_Palette_ACDC_Town
    .incbin "data/maps/offline/ACDC_Town.palettez" @ 0x3D8104
global_label BgData_Tilemap_ACDC_Town
    .incbin "data/maps/offline/ACDC_Town.tilemapz" @ 0x3D82A8
global_label BgData_Tileset_ACDC_School_Gate
    .incbin "data/maps/offline/ACDC_School_Gate.tilesetz" @ 0x3DD8FC
global_label BgData_Palette_ACDC_School_Gate
    .incbin "data/maps/offline/ACDC_School_Gate.palettez" @ 0x3E1FC0
global_label BgData_Tilemap_ACDC_School_Gate
    .incbin "data/maps/offline/ACDC_School_Gate.tilemapz" @ 0x3E2164
global_label BgData_Tileset_ACDC_Lan_Living_Room
    .incbin "data/maps/offline/ACDC_Lan_Living_Room.tilesetz" @ 0x3E3CC4
global_label BgData_Palette_ACDC_Lan_Living_Room
    .incbin "data/maps/offline/ACDC_Lan_Living_Room.palettez" @ 0x3E6678
global_label BgData_Tilemap_ACDC_Lan_Living_Room
    .incbin "data/maps/offline/ACDC_Lan_Living_Room.tilemapz" @ 0x3E681C
global_label BgData_Tileset_ACDC_Lan_Room
    .incbin "data/maps/offline/ACDC_Lan_Room.tilesetz" @ 0x3E7718
global_label BgData_Palette_ACDC_Lan_Room
    .incbin "data/maps/offline/ACDC_Lan_Room.palettez" @ 0x3E9500
global_label BgData_Tilemap_ACDC_Lan_Room
    .incbin "data/maps/offline/ACDC_Lan_Room.tilemapz" @ 0x3E96A4
global_label BgData_Tileset_ACDC_Mayl_Living_Room
    .incbin "data/maps/offline/ACDC_Mayl_Living_Room.tilesetz" @ 0x3EA180
global_label BgData_Palette_ACDC_Mayl_Living_Room
    .incbin "data/maps/offline/ACDC_Mayl_Living_Room.palettez" @ 0x3EC5F0
global_label BgData_Tilemap_ACDC_Mayl_Living_Room
    .incbin "data/maps/offline/ACDC_Mayl_Living_Room.tilemapz" @ 0x3EC794
global_label BgData_Tileset_ACDC_Mayl_Room
    .incbin "data/maps/offline/ACDC_Mayl_Room.tilesetz" @ 0x3ED76C
global_label BgData_Palette_ACDC_Mayl_Room
    .incbin "data/maps/offline/ACDC_Mayl_Room.palettez" @ 0x3EF004
global_label BgData_Tilemap_ACDC_Mayl_Room
    .incbin "data/maps/offline/ACDC_Mayl_Room.tilemapz" @ 0x3EF1A8
global_label BgData_Tileset_ACDC_Dex_Room
    .incbin "data/maps/offline/ACDC_Dex_Room.tilesetz" @ 0x3EFBD4
global_label BgData_Palette_ACDC_Dex_Room
    .incbin "data/maps/offline/ACDC_Dex_Room.palettez" @ 0x3F2310
global_label BgData_Tilemap_ACDC_Dex_Room
    .incbin "data/maps/offline/ACDC_Dex_Room.tilemapz" @ 0x3F24B4
global_label BgData_Tileset_ACDC_Yai_Room
    .incbin "data/maps/offline/ACDC_Yai_Room.tilesetz" @ 0x3F308C
global_label BgData_Palette_ACDC_Yai_Room
    .incbin "data/maps/offline/ACDC_Yai_Room.palettez" @ 0x3F600C
global_label BgData_Tilemap_ACDC_Yai_Room
    .incbin "data/maps/offline/ACDC_Yai_Room.tilemapz" @ 0x3F61B0
global_label BgData_Tileset_ACDC_Higsbys
    .incbin "data/maps/offline/ACDC_Higsbys.tilesetz" @ 0x3F715C
global_label BgData_Palette_ACDC_Higsbys
    .incbin "data/maps/offline/ACDC_Higsbys.palettez" @ 0x3F9D04
global_label BgData_Tilemap_ACDC_Higsbys
    .incbin "data/maps/offline/ACDC_Higsbys.tilemapz" @ 0x3F9EA8
global_label BgData_Tileset_ACDC_Station
    .incbin "data/maps/offline/ACDC_Station.tilesetz" @ 0x3FACE4
global_label BgData_Palette_ACDC_Station
    .incbin "data/maps/offline/ACDC_Station.palettez" @ 0x3FEE84
global_label BgData_Tilemap_ACDC_Station
    .incbin "data/maps/offline/ACDC_Station.tilemapz" @ 0x3FF028
global_label BgData_Palette_ACDC_Secret_Station
    .incbin "data/maps/offline/ACDC_Secret_Station.palettez" @ 0x4005B0
global_label BgData_Tilemap_ACDC_Secret_Station
    .incbin "data/maps/offline/ACDC_Secret_Station.tilemapz" @ 0x400754
global_label BgData_Tileset_Govt_Complex_Front
    .incbin "data/maps/offline/Govt_Complex_Front.tilesetz" @ 0x401ABC
global_label BgData_Palette_Govt_Complex_Front
    .incbin "data/maps/offline/Govt_Complex_Front.palettez" @ 0x405374
global_label BgData_Tilemap_Govt_Complex_Front
    .incbin "data/maps/offline/Govt_Complex_Front.tilemapz" @ 0x405518
global_label BgData_Palette_Govt_Complex_Station
    .incbin "data/maps/offline/Govt_Complex_Station.palettez" @ 0x40A4A0
global_label BgData_Tilemap_Govt_Complex_Station
    .incbin "data/maps/offline/Govt_Complex_Station.tilemapz" @ 0x40A644
global_label BgData_Tileset_Govt_Waterworks_Lobby
    .incbin "data/maps/offline/Govt_Waterworks_Lobby.tilesetz" @ 0x40BDD0
global_label BgData_Palette_Govt_Waterworks_Lobby
    .incbin "data/maps/offline/Govt_Waterworks_Lobby.palettez" @ 0x40E520
global_label BgData_Tilemap_Govt_Waterworks_Lobby
    .incbin "data/maps/offline/Govt_Waterworks_Lobby.tilemapz" @ 0x40E6C4
global_label BgData_Tileset_Govt_SciLab_Lobby
    .incbin "data/maps/offline/Govt_SciLab_Lobby.tilesetz" @ 0x410FA4
global_label BgData_Palette_Govt_SciLab_Lobby
    .incbin "data/maps/offline/Govt_SciLab_Lobby.palettez" @ 0x41338C
global_label BgData_Tilemap_Govt_SciLab_Lobby
    .incbin "data/maps/offline/Govt_SciLab_Lobby.tilemapz" @ 0x413530
global_label BgData_Tileset_Govt_Complex_Hallway
    .incbin "data/maps/offline/Govt_Complex_Hallway.tilesetz" @ 0x415D74
global_label BgData_Palette_Govt_Complex_Hallway
    .incbin "data/maps/offline/Govt_Complex_Hallway.palettez" @ 0x41640C
global_label BgData_Tilemap_Govt_Complex_Hallway
    .incbin "data/maps/offline/Govt_Complex_Hallway.tilemapz" @ 0x4165B0
global_label BgData_Tileset_Govt_Yuichiro_Lab
    .incbin "data/maps/offline/Govt_Yuichiro_Lab.tilesetz" @ 0x4176B8
global_label BgData_Palette_Govt_Yuichiro_Lab
    .incbin "data/maps/offline/Govt_Yuichiro_Lab.palettez" @ 0x419D04
global_label BgData_Tilemap_Govt_Yuichiro_Lab
    .incbin "data/maps/offline/Govt_Yuichiro_Lab.tilemapz" @ 0x419EA8
global_label BgData_Tileset_Govt_Waterworks_Office
    .incbin "data/maps/offline/Govt_Waterworks_Office.tilesetz" @ 0x41C27C
global_label BgData_Palette_Govt_Waterworks_Office
    .incbin "data/maps/offline/Govt_Waterworks_Office.palettez" @ 0x41D8F0
global_label BgData_Tilemap_Govt_Waterworks_Office
    .incbin "data/maps/offline/Govt_Waterworks_Office.tilemapz" @ 0x41DA94
global_label BgData_Tileset_Govt_Waterworks_Control_Room
    .incbin "data/maps/offline/Govt_Waterworks_Control_Room.tilesetz" @ 0x41F390
global_label BgData_Palette_Govt_Waterworks_Control_Room
    .incbin "data/maps/offline/Govt_Waterworks_Control_Room.palettez" @ 0x420B50
global_label BgData_Tilemap_Govt_Waterworks_Control_Room
    .incbin "data/maps/offline/Govt_Waterworks_Control_Room.tilemapz" @ 0x420CF4
global_label BgData_Tileset_Govt_Waterworks_Pump_Room
    .incbin "data/maps/offline/Govt_Waterworks_Pump_Room.tilesetz" @ 0x42344C
global_label BgData_Palette_Govt_Waterworks_Pump_Room
    .incbin "data/maps/offline/Govt_Waterworks_Pump_Room.palettez" @ 0x426324
global_label BgData_Tilemap_Govt_Waterworks_Pump_Room
    .incbin "data/maps/offline/Govt_Waterworks_Pump_Room.tilemapz" @ 0x4264C8
global_label BgData_Palette_Govt_Waterworks_Purification_Room
    .incbin "data/maps/offline/Govt_Waterworks_Purification_Room.palettez" @ 0x428498
global_label BgData_Tilemap_Govt_Waterworks_Purification_Room
    .incbin "data/maps/offline/Govt_Waterworks_Purification_Room.tilemapz" @ 0x42863C
global_label BgData_Tileset_DenTown_Center
    .incbin "data/maps/offline/DenTown_Center.tilesetz" @ 0x42BDB8
global_label BgData_Palette_DenTown_Center
    .incbin "data/maps/offline/DenTown_Center.palettez" @ 0x42ED5C
global_label BgData_Tilemap_DenTown_Center
    .incbin "data/maps/offline/DenTown_Center.tilemapz" @ 0x42EF00
global_label BgData_Palette_DenTown_Station
    .incbin "data/maps/offline/DenTown_Station.palettez" @ 0x432970
global_label BgData_Tilemap_DenTown_Station
    .incbin "data/maps/offline/DenTown_Station.tilemapz" @ 0x432B14
global_label BgData_Tileset_DenTown_Block_1
    .incbin "data/maps/offline/DenTown_Block_1.tilesetz" @ 0x43423C
global_label BgData_Palette_DenTown_Block_1
    .incbin "data/maps/offline/DenTown_Block_1.palettez" @ 0x438430
global_label BgData_Tilemap_DenTown_Block_1
    .incbin "data/maps/offline/DenTown_Block_1.tilemapz" @ 0x4385D4
global_label BgData_Palette_DenTown_Block_2
    .incbin "data/maps/offline/DenTown_Block_2.palettez" @ 0x43A984
global_label BgData_Tilemap_DenTown_Block_2
    .incbin "data/maps/offline/DenTown_Block_2.tilemapz" @ 0x43AB28
global_label BgData_Palette_DenTown_Block_3
    .incbin "data/maps/offline/DenTown_Block_3.palettez" @ 0x43CE70
global_label BgData_Tilemap_DenTown_Block_3
    .incbin "data/maps/offline/DenTown_Block_3.tilemapz" @ 0x43D014
global_label BgData_Palette_DenTown_Block_4
    .incbin "data/maps/offline/DenTown_Block_4.palettez" @ 0x43F534
global_label BgData_Tilemap_DenTown_Block_4
    .incbin "data/maps/offline/DenTown_Block_4.tilemapz" @ 0x43F6D8
global_label BgData_Tileset_DenTown_Miyu_Antiques
    .incbin "data/maps/offline/DenTown_Miyu_Antiques.tilesetz" @ 0x441810
global_label BgData_Palette_DenTown_Miyu_Antiques
    .incbin "data/maps/offline/DenTown_Miyu_Antiques.palettez" @ 0x443618
global_label BgData_Tilemap_DenTown_Miyu_Antiques
    .incbin "data/maps/offline/DenTown_Miyu_Antiques.tilemapz" @ 0x4437BC
global_label BgData_Tileset_DenTown_Summer_School
    .incbin "data/maps/offline/DenTown_Summer_School.tilesetz" @ 0x4442B0
global_label BgData_Palette_DenTown_Summer_School
    .incbin "data/maps/offline/DenTown_Summer_School.palettez" @ 0x44531C
global_label BgData_Tilemap_DenTown_Summer_School
    .incbin "data/maps/offline/DenTown_Summer_School.tilemapz" @ 0x4454C0
global_label BgData_Tileset_SciLab_Restaurant_Hallway
    .incbin "data/maps/offline/SciLab_Restaurant_Hallway.tilesetz" @ 0x445F98
global_label BgData_Palette_SciLab_Restaurant_Hallway
    .incbin "data/maps/offline/SciLab_Restaurant_Hallway.palettez" @ 0x447BB8
global_label BgData_Tilemap_SciLab_Restaurant_Hallway
    .incbin "data/maps/offline/SciLab_Restaurant_Hallway.tilemapz" @ 0x447D5C
global_label BgData_Tileset_SciLab_Restaurant
    .incbin "data/maps/offline/SciLab_Restaurant.tilesetz" @ 0x44A1C4
global_label BgData_Palette_SciLab_Restaurant
    .incbin "data/maps/offline/SciLab_Restaurant.palettez" @ 0x44CB4C
global_label BgData_Tilemap_SciLab_Restaurant
    .incbin "data/maps/offline/SciLab_Restaurant.tilemapz" @ 0x44CCF0
global_label BgData_Palette_SciLab_Power_Plant_Hallway
    .incbin "data/maps/offline/SciLab_Power_Plant_Hallway.palettez" @ 0x44F584
global_label BgData_Tilemap_SciLab_Power_Plant_Hallway
    .incbin "data/maps/offline/SciLab_Power_Plant_Hallway.tilemapz" @ 0x44F728
global_label BgData_Palette_SciLab_Power_Plant
    .incbin "data/maps/offline/SciLab_Power_Plant.palettez" @ 0x451AFC
global_label BgData_Tilemap_SciLab_Power_Plant
    .incbin "data/maps/offline/SciLab_Power_Plant.tilemapz" @ 0x451CA0
global_label BgData_Palette_SciLab_Power_Plant_Control_Room
    .incbin "data/maps/offline/SciLab_Power_Plant_Control_Room.palettez" @ 0x4537D8
global_label BgData_Tilemap_SciLab_Power_Plant_Control_Room
    .incbin "data/maps/offline/SciLab_Power_Plant_Control_Room.tilemapz" @ 0x45397C
global_label BgData_Tileset_SciLab_Generator_Room
    .incbin "data/maps/offline/SciLab_Generator_Room.tilesetz" @ 0x454EEC
global_label BgData_Palette_SciLab_Generator_Room
    .incbin "data/maps/offline/SciLab_Generator_Room.palettez" @ 0x45673C
global_label BgData_Tilemap_SciLab_Generator_Room
    .incbin "data/maps/offline/SciLab_Generator_Room.tilemapz" @ 0x4568E0
global_label BgData_Tileset_WWW_Base
    .incbin "data/maps/offline/WWW_Base.tilesetz" @ 0x458D1C
global_label BgData_Palette_WWW_Base
    .incbin "data/maps/offline/WWW_Base.palettez" @ 0x45C3EC
global_label BgData_Tilemap_WWW_Base
    .incbin "data/maps/offline/WWW_Base.tilemapz" @ 0x45C590
global_label BgData_Tileset_WWW_Wily_Lab
    .incbin "data/maps/offline/WWW_Wily_Lab.tilesetz" @ 0x45E93C
global_label BgData_Palette_WWW_Wily_Lab
    .incbin "data/maps/offline/WWW_Wily_Lab.palettez" @ 0x462CC4
global_label BgData_Tilemap_WWW_Wily_Lab
    .incbin "data/maps/offline/WWW_Wily_Lab.tilemapz" @ 0x462E68
global_label BgData_Tileset_WWW_Rocket_Hangar
    .incbin "data/maps/offline/WWW_Rocket_Hangar.tilesetz" @ 0x465260
global_label BgData_Palette_WWW_Rocket_Hangar
    .incbin "data/maps/offline/WWW_Rocket_Hangar.palettez" @ 0x468E34
global_label BgData_Tilemap_WWW_Rocket_Hangar
    .incbin "data/maps/offline/WWW_Rocket_Hangar.tilemapz" @ 0x468FD8
global_label BgData_Tileset_WWW_Passage_1
    .incbin "data/maps/offline/WWW_Passage_1.tilesetz" @ 0x46B200
global_label BgData_Palette_WWW_Passage_1
    .incbin "data/maps/offline/WWW_Passage_1.palettez" @ 0x46C410
global_label BgData_Tilemap_WWW_Passage_1
    .incbin "data/maps/offline/WWW_Passage_1.tilemapz" @ 0x46C5B4
global_label BgData_Palette_WWW_Passage_2
    .incbin "data/maps/offline/WWW_Passage_2.palettez" @ 0x46D578
global_label BgData_Tilemap_WWW_Passage_2
    .incbin "data/maps/offline/WWW_Passage_2.tilemapz" @ 0x46D71C
global_label BgData_Palette_WWW_Passage_3
    .incbin "data/maps/offline/WWW_Passage_3.palettez" @ 0x46E6B0
global_label BgData_Tilemap_WWW_Passage_3
    .incbin "data/maps/offline/WWW_Passage_3.tilemapz" @ 0x46E854
global_label BgData_Tileset_School_Comp_1
    .incbin "data/maps/online/School_Comp_1.tilesetz" @ 0x46F8A8
global_label BgData_Palette_School_Comp_1
    .incbin "data/maps/online/School_Comp_1.palettez" @ 0x472B84
global_label BgData_Tilemap_School_Comp_1
    .incbin "data/maps/online/School_Comp_1.tilemapz" @ 0x472D28
global_label BgData_Tileset_School_Comp_2
    .incbin "data/maps/online/School_Comp_2.tilesetz" @ 0x475A74
global_label BgData_Palette_School_Comp_2
    .incbin "data/maps/online/School_Comp_2.palettez" @ 0x478820
global_label BgData_Tilemap_School_Comp_2
    .incbin "data/maps/online/School_Comp_2.tilemapz" @ 0x4789C4
global_label BgData_Palette_School_Comp_3
    .incbin "data/maps/online/School_Comp_3.palettez" @ 0x47B634
global_label BgData_Tilemap_School_Comp_3
    .incbin "data/maps/online/School_Comp_3.tilemapz" @ 0x47B7D8
global_label BgData_Palette_School_Comp_4
    .incbin "data/maps/online/School_Comp_4.palettez" @ 0x47E290
global_label BgData_Tilemap_School_Comp_4
    .incbin "data/maps/online/School_Comp_4.tilemapz" @ 0x47E434
global_label BgData_Palette_School_Comp_5
    .incbin "data/maps/online/School_Comp_5.palettez" @ 0x481450
global_label BgData_Tilemap_School_Comp_5
    .incbin "data/maps/online/School_Comp_5.tilemapz" @ 0x4815F4
global_label BgData_Tileset_Oven_Comp_1
    .incbin "data/maps/online/Oven_Comp_1.tilesetz" @ 0x483F78
global_label BgData_Palette_Oven_Comp_1
    .incbin "data/maps/online/Oven_Comp_1.palettez" @ 0x487718
global_label BgData_Tilemap_Oven_Comp_1
    .incbin "data/maps/online/Oven_Comp_1.tilemapz" @ 0x4878BC
global_label BgData_Tilemap_Oven_Comp_2
    .incbin "data/maps/online/Oven_Comp_2.tilemapz" @ 0x48BB6C
global_label BgData_Tileset_Waterworks_Comp_1
    .incbin "data/maps/online/Waterworks_Comp_1.tilesetz" @ 0x48EE68
global_label BgData_Palette_Waterworks_Comp_1
    .incbin "data/maps/online/Waterworks_Comp_1.palettez" @ 0x4955C4
global_label BgData_Tilemap_Waterworks_Comp_1
    .incbin "data/maps/online/Waterworks_Comp_1.tilemapz" @ 0x495768
global_label BgData_Tilemap_Waterworks_Comp_2
    .incbin "data/maps/online/Waterworks_Comp_2.tilemapz" @ 0x49A91C
global_label BgData_Tilemap_Waterworks_Comp_3
    .incbin "data/maps/online/Waterworks_Comp_3.tilemapz" @ 0x49EC7C
global_label BgData_Tileset_Waterworks_Comp_4
    .incbin "data/maps/online/Waterworks_Comp_4.tilesetz" @ 0x4A4264
global_label BgData_Palette_Waterworks_Comp_4
    .incbin "data/maps/online/Waterworks_Comp_4.palettez" @ 0x4A99D0
global_label BgData_Tilemap_Waterworks_Comp_4
    .incbin "data/maps/online/Waterworks_Comp_4.tilemapz" @ 0x4A9B74
global_label BgData_Tileset_Waterworks_Comp_5
    .incbin "data/maps/online/Waterworks_Comp_5.tilesetz" @ 0x4AF050
global_label BgData_Palette_Waterworks_Comp_5
    .incbin "data/maps/online/Waterworks_Comp_5.palettez" @ 0x4B26C4
global_label BgData_Tilemap_Waterworks_Comp_5
    .incbin "data/maps/online/Waterworks_Comp_5.tilemapz" @ 0x4B2868
global_label BgData_Palette_Waterworks_Comp_6
    .incbin "data/maps/online/Waterworks_Comp_6.palettez" @ 0x4B6EE0
global_label BgData_Tilemap_Waterworks_Comp_6
    .incbin "data/maps/online/Waterworks_Comp_6.tilemapz" @ 0x4B7084
global_label BgData_Tileset_Traffic_Light_Comp_1
    .incbin "data/maps/online/Traffic_Light_Comp_1.tilesetz" @ 0x4BBFB0
global_label BgData_Palette_Traffic_Light_Comp_1
    .incbin "data/maps/online/Traffic_Light_Comp_1.palettez" @ 0x4BDB30
global_label BgData_Tilemap_Traffic_Light_Comp_1
    .incbin "data/maps/online/Traffic_Light_Comp_1.tilemapz" @ 0x4BDCD4
global_label BgData_Tilemap_Traffic_Light_Comp_2
    .incbin "data/maps/online/Traffic_Light_Comp_2.tilemapz" @ 0x4C16F0
global_label BgData_Tilemap_Traffic_Light_Comp_3
    .incbin "data/maps/online/Traffic_Light_Comp_3.tilemapz" @ 0x4C5284
global_label BgData_Tilemap_Traffic_Light_Comp_4
    .incbin "data/maps/online/Traffic_Light_Comp_4.tilemapz" @ 0x4C9438
global_label BgData_Tilemap_Traffic_Light_Comp_5
    .incbin "data/maps/online/Traffic_Light_Comp_5.tilemapz" @ 0x4CCC70
global_label BgData_Tileset_Power_Plant_Comp_1
    .incbin "data/maps/online/Power_Plant_Comp_1.tilesetz" @ 0x4D16FC
global_label BgData_Palette_Power_Plant_Comp_1
    .incbin "data/maps/online/Power_Plant_Comp_1.palettez" @ 0x4D3868
global_label BgData_Tilemap_Power_Plant_Comp_1
    .incbin "data/maps/online/Power_Plant_Comp_1.tilemapz" @ 0x4D3A0C
global_label BgData_Tilemap_Power_Plant_Comp_2
    .incbin "data/maps/online/Power_Plant_Comp_2.tilemapz" @ 0x4D8530
global_label BgData_Tilemap_Power_Plant_Comp_3
    .incbin "data/maps/online/Power_Plant_Comp_3.tilemapz" @ 0x4DCF48
global_label BgData_Tilemap_Power_Plant_Comp_4
    .incbin "data/maps/online/Power_Plant_Comp_4.tilemapz" @ 0x4E1AE8
global_label BgData_Tilemap_WWW_Comp_1
    .incbin "data/maps/online/WWW_Comp_1.tilemapz" @ 0x4E63AC
global_label BgData_Palette_WWW_Comp_2
    .incbin "data/maps/online/WWW_Comp_2.palettez" @ 0x4EAFBC
global_label BgData_Tilemap_WWW_Comp_2
    .incbin "data/maps/online/WWW_Comp_2.tilemapz" @ 0x4EB160
global_label BgData_Tilemap_WWW_Comp_3
    .incbin "data/maps/online/WWW_Comp_3.tilemapz" @ 0x4EEFC0
global_label BgData_Tilemap_WWW_Comp_4
    .incbin "data/maps/online/WWW_Comp_4.tilemapz" @ 0x4F3DE0
global_label BgData_Tilemap_WWW_Comp_5
    .incbin "data/maps/online/WWW_Comp_5.tilemapz" @ 0x4F8438
global_label BgData_Tileset_Rocket_Comp
    .incbin "data/maps/online/Rocket_Comp.tilesetz" @ 0x4FCBA4
global_label BgData_Palette_Rocket_Comp
    .incbin "data/maps/online/Rocket_Comp.palettez" @ 0x4FDCFC
global_label BgData_Tilemap_Rocket_Comp
    .incbin "data/maps/online/Rocket_Comp.tilemapz" @ 0x4FDEA0
global_label BgData_Tileset_ACDC_Lan_PC
    .incbin "data/maps/online/ACDC_Lan_PC.tilesetz" @ 0x500FD4
global_label BgData_Palette_ACDC_Lan_PC
    .incbin "data/maps/online/ACDC_Lan_PC.palettez" @ 0x502C60
global_label BgData_Tilemap_ACDC_Lan_PC
    .incbin "data/maps/online/ACDC_Lan_PC.tilemapz" @ 0x502E04
global_label BgData_Tilemap_ACDC_Mayl_PC
    .incbin "data/maps/online/ACDC_Mayl_PC.tilemapz" @ 0x503934
global_label BgData_Palette_ACDC_Mayl_PC
    .incbin "data/maps/online/ACDC_Mayl_PC.palettez" @ 0x506384
global_label BgData_Tilemap_ACDC_Yai_PC
    .incbin "data/maps/online/ACDC_Yai_PC.tilemapz" @ 0x506528
global_label BgData_Palette_ACDC_Yai_PC
    .incbin "data/maps/online/ACDC_Yai_PC.palettez" @ 0x5087D4
global_label BgData_Tilemap_ACDC_Dex_PC
    .incbin "data/maps/online/ACDC_Dex_PC.tilemapz" @ 0x508978
global_label BgData_Palette_ACDC_Dex_PC
    .incbin "data/maps/online/ACDC_Dex_PC.palettez" @ 0x50C900
global_label BgData_Tileset_Govt_Yuichiro_PC
    .incbin "data/maps/online/Govt_Yuichiro_PC.tilesetz" @ 0x50CAA4
global_label BgData_Palette_Govt_Yuichiro_PC
    .incbin "data/maps/online/Govt_Yuichiro_PC.palettez" @ 0x50DC6C
global_label BgData_Tilemap_Govt_Yuichiro_PC
    .incbin "data/maps/online/Govt_Yuichiro_PC.tilemapz" @ 0x50DE10
global_label BgData_Tilemap_Govt_Lunch_Cart_Comp
    .incbin "data/maps/online/Govt_Lunch_Cart_Comp.tilemapz" @ 0x50F498
global_label BgData_Palette_Govt_Lunch_Cart_Comp
    .incbin "data/maps/online/Govt_Lunch_Cart_Comp.palettez" @ 0x511580
global_label BgData_Tilemap_DenTown_Antique_Comp
    .incbin "data/maps/online/DenTown_Antique_Comp.tilemapz" @ 0x511724
global_label BgData_Palette_DenTown_Antique_Comp
    .incbin "data/maps/online/DenTown_Antique_Comp.palettez" @ 0x51398C
global_label BgData_Tilemap_SciLab_Fish_Stand_Comp
    .incbin "data/maps/online/SciLab_Fish_Stand_Comp.tilemapz" @ 0x513B30
global_label BgData_Palette_SciLab_Fish_Stand_Comp
    .incbin "data/maps/online/SciLab_Fish_Stand_Comp.palettez" @ 0x517C78
global_label BgData_Tilemap_Other_Generic_Comp
    .incbin "data/maps/online/Other_Generic_Comp.tilemapz" @ 0x517E1C
global_label BgData_Palette_Other_Generic_Comp
    .incbin "data/maps/online/Other_Generic_Comp.palettez" @ 0x51A1C4
global_label BgData_Tileset_Internet_1
    .incbin "data/maps/online/Internet_1.tilesetz" @ 0x51A368
global_label BgData_Palette_Internet_1
    .incbin "data/maps/online/Internet_1.palettez" @ 0x51E23C
global_label BgData_Tilemap_Internet_1
    .incbin "data/maps/online/Internet_1.tilemapz" @ 0x51E3E0
global_label BgData_Tilemap_Internet_2
    .incbin "data/maps/online/Internet_2.tilemapz" @ 0x523568
global_label BgData_Tilemap_Internet_3
    .incbin "data/maps/online/Internet_3.tilemapz" @ 0x528AE8
global_label BgData_Tilemap_Internet_4
    .incbin "data/maps/online/Internet_4.tilemapz" @ 0x52D57C
global_label BgData_Tilemap_Undernet_1
    .incbin "data/maps/online/Undernet_1.tilemapz" @ 0x531ED4
global_label BgData_Tilemap_Undernet_2
    .incbin "data/maps/online/Undernet_2.tilemapz" @ 0x53614C
global_label BgData_Tilemap_Undernet_3
    .incbin "data/maps/online/Undernet_3.tilemapz" @ 0x53A4C8
global_label BgData_Tilemap_Undernet_4
    .incbin "data/maps/online/Undernet_4.tilemapz" @ 0x53E484
global_label BgData_Tilemap_Undernet_5
    .incbin "data/maps/online/Undernet_5.tilemapz" @ 0x542204
global_label BgData_Tilemap_Undernet_6
    .incbin "data/maps/online/Undernet_6.tilemapz" @ 0x545C3C
global_label BgData_Tilemap_Undernet_7
    .incbin "data/maps/online/Undernet_7.tilemapz" @ 0x549A60
global_label BgData_Tilemap_Undernet_8
    .incbin "data/maps/online/Undernet_8.tilemapz" @ 0x54DF24
global_label BgData_Tilemap_Undernet_9
    .incbin "data/maps/online/Undernet_9.tilemapz" @ 0x551D84
global_label BgData_Tilemap_Undernet_10
    .incbin "data/maps/online/Undernet_10.tilemapz" @ 0x55564C
global_label BgData_Tilemap_Undernet_11
    .incbin "data/maps/online/Undernet_11.tilemapz" @ 0x559694
global_label BgData_Tilemap_Undernet_12
    .incbin "data/maps/online/Undernet_12.tilemapz" @ 0x55CF88
global_label BgData_Tileset_Battle_NumberMan
    .incbin "data/maps/battle/Battle_NumberMan.tilesetz" @ 0x561434
global_label BgData_Palette_Battle_NumberMan
    .incbin "data/maps/battle/Battle_NumberMan.palettez" @ 0x561650
global_label BgData_Tilemap_Battle_NumberMan
    .incbin "data/maps/battle/Battle_NumberMan.tilemapz" @ 0x561774
global_label BgData_Tileset_Battle_FireMan
    .incbin "data/maps/battle/Battle_FireMan.tilesetz" @ 0x561C78
global_label BgData_Palette_Battle_FireMan
    .incbin "data/maps/battle/Battle_FireMan.palettez" @ 0x561E84
global_label BgData_Tilemap_Battle_FireMan
    .incbin "data/maps/battle/Battle_FireMan.tilemapz" @ 0x561FA8
global_label BgData_Tileset_Battle_IceMan
    .incbin "data/maps/battle/Battle_IceMan.tilesetz" @ 0x562478
global_label BgData_Palette_Battle_IceMan
    .incbin "data/maps/battle/Battle_IceMan.palettez" @ 0x562674
global_label BgData_Tilemap_Battle_IceMan
    .incbin "data/maps/battle/Battle_IceMan.tilemapz" @ 0x562798
global_label BgData_Tileset_Battle_ColorMan
    .incbin "data/maps/battle/Battle_ColorMan.tilesetz" @ 0x562C6C
global_label BgData_Palette_Battle_ColorMan
    .incbin "data/maps/battle/Battle_ColorMan.palettez" @ 0x562EE4
global_label BgData_Tilemap_Battle_ColorMan
    .incbin "data/maps/battle/Battle_ColorMan.tilemapz" @ 0x563008
global_label BgData_Tileset_Battle_ElecMan
    .incbin "data/maps/battle/Battle_ElecMan.tilesetz" @ 0x563500
global_label BgData_Palette_Battle_ElecMan
    .incbin "data/maps/battle/Battle_ElecMan.palettez" @ 0x5637A8
global_label BgData_Tilemap_Battle_ElecMan
    .incbin "data/maps/battle/Battle_ElecMan.tilemapz" @ 0x5638CC
global_label BgData_Tileset_Battle_WWW
    .incbin "data/maps/battle/Battle_WWW.tilesetz" @ 0x563E24
global_label BgData_Palette_Battle_WWW
    .incbin "data/maps/battle/Battle_WWW.palettez" @ 0x563FEC
global_label BgData_Tilemap_Battle_WWW
    .incbin "data/maps/battle/Battle_WWW.tilemapz" @ 0x564110
global_label BgData_Tileset_Battle_Internet
    .incbin "data/maps/battle/Battle_Internet.tilesetz" @ 0x564654
global_label BgData_Palette_Battle_Internet
    .incbin "data/maps/battle/Battle_Internet.palettez" @ 0x5648D0
global_label BgData_Tilemap_Battle_Internet
    .incbin "data/maps/battle/Battle_Internet.tilemapz" @ 0x5649F4
global_label BgData_Tileset_Battle_Generic
    .incbin "data/maps/battle/Battle_Generic.tilesetz" @ 0x564EF4
global_label BgData_Palette_Battle_Generic
    .incbin "data/maps/battle/Battle_Generic.palettez" @ 0x565124
global_label BgData_Tilemap_Battle_Generic
    .incbin "data/maps/battle/Battle_Generic.tilemapz" @ 0x565248
global_label BgData_Tileset_Battle_LanHP
    .incbin "data/maps/battle/Battle_LanHP.tilesetz" @ 0x565750
global_label BgData_Palette_Battle_LanHP
    .incbin "data/maps/battle/Battle_LanHP.palettez" @ 0x5659AC
global_label BgData_Tilemap_Battle_LanHP
    .incbin "data/maps/battle/Battle_LanHP.tilemapz" @ 0x565AD0
global_label BgData_Tileset_Battle_MaylHP
    .incbin "data/maps/battle/Battle_MaylHP.tilesetz" @ 0x565FD8
global_label BgData_Palette_Battle_MaylHP
    .incbin "data/maps/battle/Battle_MaylHP.palettez" @ 0x566260
global_label BgData_Tilemap_Battle_MaylHP
    .incbin "data/maps/battle/Battle_MaylHP.tilemapz" @ 0x566384
global_label BgData_Tileset_Battle_YaiHP
    .incbin "data/maps/battle/Battle_YaiHP.tilesetz" @ 0x566898
global_label BgData_Palette_Battle_YaiHP
    .incbin "data/maps/battle/Battle_YaiHP.palettez" @ 0x566A7C
global_label BgData_Tilemap_Battle_YaiHP
    .incbin "data/maps/battle/Battle_YaiHP.tilemapz" @ 0x566BA0
global_label BgData_Tileset_Battle_DexHP
    .incbin "data/maps/battle/Battle_DexHP.tilesetz" @ 0x5670B0
global_label BgData_Palette_Battle_DexHP
    .incbin "data/maps/battle/Battle_DexHP.palettez" @ 0x567410
global_label BgData_Tilemap_Battle_DexHP
    .incbin "data/maps/battle/Battle_DexHP.tilemapz" @ 0x567534
global_label BgData_Tileset_Battle_YuichiroHP
    .incbin "data/maps/battle/Battle_YuichiroHP.tilesetz" @ 0x567AA4
global_label BgData_Palette_Battle_YuichiroHP
    .incbin "data/maps/battle/Battle_YuichiroHP.palettez" @ 0x567CD4
global_label BgData_Tilemap_Battle_YuichiroHP
    .incbin "data/maps/battle/Battle_YuichiroHP.tilemapz" @ 0x567DF8
global_label BgData_Tileset_Battle_SalHP
    .incbin "data/maps/battle/Battle_SalHP.tilesetz" @ 0x568300
global_label BgData_Palette_Battle_SalHP
    .incbin "data/maps/battle/Battle_SalHP.palettez" @ 0x5684C0
global_label BgData_Tilemap_Battle_SalHP
    .incbin "data/maps/battle/Battle_SalHP.tilemapz" @ 0x5685E4
global_label BgData_Tileset_Battle_MiyuHP
    .incbin "data/maps/battle/Battle_MiyuHP.tilesetz" @ 0x568AF0
global_label BgData_Palette_Battle_MiyuHP
    .incbin "data/maps/battle/Battle_MiyuHP.palettez" @ 0x568CB4
global_label BgData_Tilemap_Battle_MiyuHP
    .incbin "data/maps/battle/Battle_MiyuHP.tilemapz" @ 0x568DD8
global_label BgData_Tileset_Battle_MasaHP
    .incbin "data/maps/battle/Battle_MasaHP.tilesetz" @ 0x5692E8
global_label BgData_Palette_Battle_MasaHP
    .incbin "data/maps/battle/Battle_MasaHP.palettez" @ 0x56939C
global_label BgData_Tilemap_Battle_MasaHP
    .incbin "data/maps/battle/Battle_MasaHP.tilemapz" @ 0x5694C0
global_label BgData_Tileset_Battle_LifeVirus
    .incbin "data/maps/battle/Battle_LifeVirus.tilesetz" @ 0x56999C
global_label BgData_Palette_Battle_LifeVirus
    .incbin "data/maps/battle/Battle_LifeVirus.palettez" @ 0x569A40
global_label BgData_Tilemap_Battle_LifeVirus
    .incbin "data/maps/battle/Battle_LifeVirus.tilemapz" @ 0x569B64

global_label MapData_School_Class_5A
    .incbin "data/maps/offline/School_Class_5A.scb" @ 0x56A038
global_label MapData_School_Class_5B
    .incbin "data/maps/offline/School_Class_5B.scb" @ 0x56AAD4
global_label MapData_School_Library
    .incbin "data/maps/offline/School_Library.scb" @ 0x56B55C
global_label MapData_School_2F_Hallway
    .incbin "data/maps/offline/School_2F_Hallway.scb" @ 0x56C38C
global_label MapData_School_Class_1A
    .incbin "data/maps/offline/School_Class_1A.scb" @ 0x56C880
global_label MapData_School_Class_1B
    .incbin "data/maps/offline/School_Class_1B.scb" @ 0x56D314
global_label MapData_School_AV_Room
    .incbin "data/maps/offline/School_AV_Room.scb" @ 0x56DD8C
global_label MapData_School_Infirmary
    .incbin "data/maps/offline/School_Infirmary.scb" @ 0x56E684
global_label MapData_School_1F_Hallway
    .incbin "data/maps/offline/School_1F_Hallway.scb" @ 0x56E94C
global_label MapData_School_Cross_Hallway
    .incbin "data/maps/offline/School_Cross_Hallway.scb" @ 0x56EEA0
global_label MapData_School_Storage
    .incbin "data/maps/offline/School_Storage.scb" @ 0x56F084
global_label MapData_School_Staff_Lounge
    .incbin "data/maps/offline/School_Staff_Lounge.scb" @ 0x56F604
global_label MapData_School_Staff_Lounge_Hallway
    .incbin "data/maps/offline/School_Staff_Lounge_Hallway.scb" @ 0x5707EC
global_label MapData_ACDC_Town
    .incbin "data/maps/offline/ACDC_Town.scb" @ 0x570A60
global_label MapData_ACDC_School_Gate
    .incbin "data/maps/offline/ACDC_School_Gate.scb" @ 0x574080
global_label MapData_ACDC_Lan_Living_Room
    .incbin "data/maps/offline/ACDC_Lan_Living_Room.scb" @ 0x574A2C
global_label MapData_ACDC_Lan_Room
    .incbin "data/maps/offline/ACDC_Lan_Room.scb" @ 0x5751D0
global_label MapData_ACDC_Mayl_Living_Room
    .incbin "data/maps/offline/ACDC_Mayl_Living_Room.scb" @ 0x5754A8
global_label MapData_ACDC_Mayl_Room
    .incbin "data/maps/offline/ACDC_Mayl_Room.scb" @ 0x575C98
global_label MapData_ACDC_Dex_Room
    .incbin "data/maps/offline/ACDC_Dex_Room.scb" @ 0x5761A8
global_label MapData_ACDC_Yai_Room
    .incbin "data/maps/offline/ACDC_Yai_Room.scb" @ 0x57663C
global_label MapData_ACDC_Higsbys
    .incbin "data/maps/offline/ACDC_Higsbys.scb" @ 0x576C60
global_label MapData_ACDC_Station
    .incbin "data/maps/offline/ACDC_Station.scb" @ 0x577280
global_label MapData_ACDC_Secret_Station
    .incbin "data/maps/offline/ACDC_Secret_Station.scb" @ 0x577770
global_label MapData_Govt_Complex_Front
    .incbin "data/maps/offline/Govt_Complex_Front.scb" @ 0x57793C
global_label MapData_Govt_Complex_Station
    .incbin "data/maps/offline/Govt_Complex_Station.scb" @ 0x578BB8
global_label MapData_Govt_Waterworks_Lobby
    .incbin "data/maps/offline/Govt_Waterworks_Lobby.scb" @ 0x578FB0
global_label MapData_Govt_SciLab_Lobby
    .incbin "data/maps/offline/Govt_SciLab_Lobby.scb" @ 0x57A3B0
global_label MapData_Govt_Complex_Hallway
    .incbin "data/maps/offline/Govt_Complex_Hallway.scb" @ 0x57B814
global_label MapData_Govt_Yuichiro_Lab
    .incbin "data/maps/offline/Govt_Yuichiro_Lab.scb" @ 0x57C4A0
global_label MapData_Govt_Waterworks_Office
    .incbin "data/maps/offline/Govt_Waterworks_Office.scb" @ 0x57D2A8
global_label MapData_Govt_Waterworks_Control_Room
    .incbin "data/maps/offline/Govt_Waterworks_Control_Room.scb" @ 0x57DAA8
global_label MapData_Govt_Waterworks_Pump_Room
    .incbin "data/maps/offline/Govt_Waterworks_Pump_Room.scb" @ 0x57E6DC
global_label MapData_Govt_Waterworks_Purification_Room
    .incbin "data/maps/offline/Govt_Waterworks_Purification_Room.scb" @ 0x57E994
global_label MapData_DenTown_Center
    .incbin "data/maps/offline/DenTown_Center.scb" @ 0x57F160
global_label MapData_DenTown_Station
    .incbin "data/maps/offline/DenTown_Station.scb" @ 0x581924
global_label MapData_DenTown_Block_1
    .incbin "data/maps/offline/DenTown_Block_1.scb" @ 0x581D30
global_label MapData_DenTown_Block_2
    .incbin "data/maps/offline/DenTown_Block_2.scb" @ 0x583404
global_label MapData_DenTown_Block_3
    .incbin "data/maps/offline/DenTown_Block_3.scb" @ 0x584CC0
global_label MapData_DenTown_Block_4
    .incbin "data/maps/offline/DenTown_Block_4.scb" @ 0x5864D0
global_label MapData_DenTown_Miyu_Antiques
    .incbin "data/maps/offline/DenTown_Miyu_Antiques.scb" @ 0x587ACC
global_label MapData_DenTown_Summer_School
    .incbin "data/maps/offline/DenTown_Summer_School.scb" @ 0x587E00
global_label MapData_SciLab_Restaurant_Hallway
    .incbin "data/maps/offline/SciLab_Restaurant_Hallway.scb" @ 0x58853C
global_label MapData_SciLab_Restaurant
    .incbin "data/maps/offline/SciLab_Restaurant.scb" @ 0x588C00
global_label MapData_SciLab_Power_Plant_Hallway
    .incbin "data/maps/offline/SciLab_Power_Plant_Hallway.scb" @ 0x58A988
global_label MapData_SciLab_Power_Plant
    .incbin "data/maps/offline/SciLab_Power_Plant.scb" @ 0x58AFF0
global_label MapData_SciLab_Power_Plant_Control_Room
    .incbin "data/maps/offline/SciLab_Power_Plant_Control_Room.scb" @ 0x58B330
global_label MapData_SciLab_Generator_Room
    .incbin "data/maps/offline/SciLab_Generator_Room.scb" @ 0x58BCB0
global_label MapData_WWW_Base
    .incbin "data/maps/offline/WWW_Base.scb" @ 0x58BFF8
global_label MapData_WWW_Wily_Lab
    .incbin "data/maps/offline/WWW_Wily_Lab.scb" @ 0x58D42C
global_label MapData_WWW_Rocket_Hangar
    .incbin "data/maps/offline/WWW_Rocket_Hangar.scb" @ 0x58DCA8
global_label MapData_WWW_Passage_1
    .incbin "data/maps/offline/WWW_Passage_1.scb" @ 0x58E4D4
global_label MapData_WWW_Passage_2
    .incbin "data/maps/offline/WWW_Passage_2.scb" @ 0x58EAA4
global_label MapData_WWW_Passage_3
    .incbin "data/maps/offline/WWW_Passage_3.scb" @ 0x58F058
global_label MapData_School_Comp_1
    .incbin "data/maps/online/School_Comp_1.scb" @ 0x58F5C8
global_label MapData_School_Comp_2
    .incbin "data/maps/online/School_Comp_2.scb" @ 0x590FF8
global_label MapData_School_Comp_3
    .incbin "data/maps/online/School_Comp_3.scb" @ 0x593D9C
global_label MapData_School_Comp_4
    .incbin "data/maps/online/School_Comp_4.scb" @ 0x5949D8
global_label MapData_School_Comp_5
    .incbin "data/maps/online/School_Comp_5.scb" @ 0x595F10
global_label MapData_Oven_Comp_1
    .incbin "data/maps/online/Oven_Comp_1.scb" @ 0x596C9C
global_label MapData_Oven_Comp_2
    .incbin "data/maps/online/Oven_Comp_2.scb" @ 0x5985C4
global_label MapData_Waterworks_Comp_1
    .incbin "data/maps/online/Waterworks_Comp_1.scb" @ 0x599A28
global_label MapData_Waterworks_Comp_2
    .incbin "data/maps/online/Waterworks_Comp_2.scb" @ 0x59BD44
global_label MapData_Waterworks_Comp_3
    .incbin "data/maps/online/Waterworks_Comp_3.scb" @ 0x59EBA0
global_label MapData_Waterworks_Comp_4
    .incbin "data/maps/online/Waterworks_Comp_4.scb" @ 0x5A427C
global_label MapData_Waterworks_Comp_5
    .incbin "data/maps/online/Waterworks_Comp_5.scb" @ 0x5A9F50
global_label MapData_Waterworks_Comp_6
    .incbin "data/maps/online/Waterworks_Comp_6.scb" @ 0x5B1478
global_label MapData_Traffic_Light_Comp_1
    .incbin "data/maps/online/Traffic_Light_Comp_1.scb" @ 0x5B64D0
global_label MapData_Traffic_Light_Comp_2
    .incbin "data/maps/online/Traffic_Light_Comp_2.scb" @ 0x5B82F4
global_label MapData_Traffic_Light_Comp_3
    .incbin "data/maps/online/Traffic_Light_Comp_3.scb" @ 0x5BA740
global_label MapData_Traffic_Light_Comp_4
    .incbin "data/maps/online/Traffic_Light_Comp_4.scb" @ 0x5BE13C
global_label MapData_Traffic_Light_Comp_5
    .incbin "data/maps/online/Traffic_Light_Comp_5.scb" @ 0x5C05DC
global_label MapData_Power_Plant_Comp_1
    .incbin "data/maps/online/Power_Plant_Comp_1.scb" @ 0x5C2A2C
global_label MapData_Power_Plant_Comp_2
    .incbin "data/maps/online/Power_Plant_Comp_2.scb" @ 0x5C7B08
global_label MapData_Power_Plant_Comp_3
    .incbin "data/maps/online/Power_Plant_Comp_3.scb" @ 0x5C9FF8
global_label MapData_Power_Plant_Comp_4
    .incbin "data/maps/online/Power_Plant_Comp_4.scb" @ 0x5CD228
global_label MapData_WWW_Comp_1
    .incbin "data/maps/online/WWW_Comp_1.scb" @ 0x5CFF6C
global_label MapData_WWW_Comp_2
    .incbin "data/maps/online/WWW_Comp_2.scb" @ 0x5D1B54
global_label MapData_WWW_Comp_3
    .incbin "data/maps/online/WWW_Comp_3.scb" @ 0x5D57A8
global_label MapData_WWW_Comp_4
    .incbin "data/maps/online/WWW_Comp_4.scb" @ 0x5D9F4C
global_label MapData_WWW_Comp_5
    .incbin "data/maps/online/WWW_Comp_5.scb" @ 0x5DB4A8
global_label MapData_Rocket_Comp
    .incbin "data/maps/online/Rocket_Comp.scb" @ 0x5DE704
global_label MapData_ACDC_Lan_PC
    .incbin "data/maps/online/ACDC_Lan_PC.scb" @ 0x5DED58
global_label MapData_ACDC_Mayl_PC
    .incbin "data/maps/online/ACDC_Mayl_PC.scb" @ 0x5DEFE4
global_label MapData_ACDC_Yai_PC
    .incbin "data/maps/online/ACDC_Yai_PC.scb" @ 0x5E0C24
global_label MapData_ACDC_Dex_PC
    .incbin "data/maps/online/ACDC_Dex_PC.scb" @ 0x5E1C18
global_label MapData_Govt_Yuichiro_PC
    .incbin "data/maps/online/Govt_Yuichiro_PC.scb" @ 0x5E22A8
global_label MapData_Govt_Lunch_Cart_Comp
    .incbin "data/maps/online/Govt_Lunch_Cart_Comp.scb" @ 0x5E27D8
global_label MapData_DenTown_Antique_Comp
    .incbin "data/maps/online/DenTown_Antique_Comp.scb" @ 0x5E2F20
global_label MapData_SciLab_Fish_Stand_Comp
    .incbin "data/maps/online/SciLab_Fish_Stand_Comp.scb" @ 0x5E384C
global_label MapData_Other_Generic_Comp
    .incbin "data/maps/online/Other_Generic_Comp.scb" @ 0x5E41F8
global_label MapData_Internet_1
    .incbin "data/maps/online/Internet_1.scb" @ 0x5E4604
global_label MapData_Internet_2
    .incbin "data/maps/online/Internet_2.scb" @ 0x5E774C
global_label MapData_Internet_3
    .incbin "data/maps/online/Internet_3.scb" @ 0x5ED608
global_label MapData_Internet_4
    .incbin "data/maps/online/Internet_4.scb" @ 0x5F1E54
global_label MapData_Undernet_1
    .incbin "data/maps/online/Undernet_1.scb" @ 0x5F5548
global_label MapData_Undernet_2
    .incbin "data/maps/online/Undernet_2.scb" @ 0x5F8100
global_label MapData_Undernet_3
    .incbin "data/maps/online/Undernet_3.scb" @ 0x5FA53C
global_label MapData_Undernet_4
    .incbin "data/maps/online/Undernet_4.scb" @ 0x5FCB14
global_label MapData_Undernet_5
    .incbin "data/maps/online/Undernet_5.scb" @ 0x5FFEE0
global_label MapData_Undernet_6
    .incbin "data/maps/online/Undernet_6.scb" @ 0x6017A8
global_label MapData_Undernet_7
    .incbin "data/maps/online/Undernet_7.scb" @ 0x604AB4
global_label MapData_Undernet_8
    .incbin "data/maps/online/Undernet_8.scb" @ 0x6074E0
global_label MapData_Undernet_9
    .incbin "data/maps/online/Undernet_9.scb" @ 0x609B64
global_label MapData_Undernet_10
    .incbin "data/maps/online/Undernet_10.scb" @ 0x60AD44
global_label MapData_Undernet_11
    .incbin "data/maps/online/Undernet_11.scb" @ 0x60DE5C
global_label MapData_Undernet_12
    .incbin "data/maps/online/Undernet_12.scb" @ 0x6109C0
