global_label DialogueData_Offline
    .word DialogueData_School
    .word DialogueData_ACDC
    .word DialogueData_Govt
    .word DialogueData_DenTown
    .word DialogueData_SciLab
    .word DialogueData_WWW

global_label DialogueData_Online
    .word DialogueData_School_Comp
    .word DialogueData_Oven_Comp
    .word DialogueData_Waterworks_Comp
    .word DialogueData_Traffic_Light_Comp
    .word DialogueData_Power_Plant_Comp
    .word DialogueData_WWW_Comp
    .word 0
    .word 0
    .word DialogueData_ACDC_HP
    .word DialogueData_Govt_Complex_HP
    .word DialogueData_DenTown_HP
    .word DialogueData_SciLab_HP
    .word DialogueData_Other_Comp
    .word 0
    .word 0
    .word 0
    .word DialogueData_Internet

global_label DialogueData_Battle
    .word DialogueData_Battle_Other

DialogueData_School:
    .word DialogueData_School_Class_5A
    .word DialogueData_School_Class_5B
    .word DialogueData_School_Library
    .word DialogueData_School_2F_Hallway
    .word 0
    .word DialogueData_School_Class_1A
    .word DialogueData_School_Class_1B
    .word DialogueData_School_AV_Room
    .word DialogueData_School_Infirmary
    .word DialogueData_School_1F_Hallway
    .word 0
    .word DialogueData_School_Cross_Hallway
    .word DialogueData_School_Storage
    .word DialogueData_School_Staff_Lounge
    .word DialogueData_School_Staff_Lounge_Hallway

DialogueData_ACDC:
    .word DialogueData_ACDC_Town
    .word DialogueData_ACDC_School_Gate
    .word DialogueData_ACDC_Lan_Living_Room
    .word DialogueData_ACDC_Lan_Room
    .word 0
    .word DialogueData_ACDC_Mayl_Living_Room
    .word DialogueData_ACDC_Mayl_Room
    .word DialogueData_ACDC_Dex_Room
    .word 0
    .word DialogueData_ACDC_Yai_Room
    .word 0
    .word DialogueData_ACDC_Higsbys
    .word DialogueData_ACDC_Station
DialogueData_Govt:
    .word DialogueData_Govt_Complex_Front
    .word DialogueData_Govt_Complex_Station
    .word DialogueData_Govt_Waterworks_Lobby
    .word DialogueData_Govt_SciLab_Lobby
    .word 0
    .word DialogueData_Govt_Yuichiro_Lab
    .word DialogueData_Govt_Waterworks_Office
    .word DialogueData_Govt_Waterworks_Control_Room
    .word 0
    .word DialogueData_Govt_Waterworks_Pump_Room
    .word 0
    .word DialogueData_Govt_Waterworks_Purification_Room
DialogueData_DenTown:
    .word DialogueData_DenTown_Center
    .word DialogueData_DenTown_Station
    .word DialogueData_DenTown_Block_1
    .word DialogueData_DenTown_Block_2
    .word DialogueData_DenTown_Block_3
    .word DialogueData_DenTown_Block_4
    .word DialogueData_DenTown_Miyu_Antiques
    .word DialogueData_DenTown_Summer_School
DialogueData_SciLab:
    .word DialogueData_SciLab_Restaurant_Hallway
    .word DialogueData_SciLab_Restaurant
    .word DialogueData_SciLab_Power_Plant_Hallway
    .word DialogueData_SciLab_Power_Plant
    .word DialogueData_SciLab_Power_Plant_Control_Room
    .word DialogueData_SciLab_Generator_Room
DialogueData_WWW:
    .word DialogueData_WWW_Base
    .word DialogueData_WWW_Wily_Lab
    .word DialogueData_WWW_Rocket_Hangar
    .word DialogueData_WWW_Passage_1
    .word DialogueData_WWW_Passage_2
    .word DialogueData_WWW_Passage_3
DialogueData_School_Comp:
    .word DialogueData_School_Comp_1
    .word DialogueData_School_Comp_2
    .word DialogueData_School_Comp_3
    .word DialogueData_School_Comp_4
    .word DialogueData_School_Comp_5
DialogueData_Oven_Comp:
    .word DialogueData_Oven_Comp_1
    .word DialogueData_Oven_Comp_2
DialogueData_Waterworks_Comp:
    .word DialogueData_Waterworks_Comp_1
    .word DialogueData_Waterworks_Comp_2
    .word DialogueData_Waterworks_Comp_3
    .word DialogueData_Waterworks_Comp_4
    .word DialogueData_Waterworks_Comp_5
    .word DialogueData_Waterworks_Comp_6
DialogueData_Traffic_Light_Comp:
    .word DialogueData_Traffic_Light_Comp_1
    .word DialogueData_Traffic_Light_Comp_2
    .word DialogueData_Traffic_Light_Comp_3
    .word DialogueData_Traffic_Light_Comp_4
    .word DialogueData_Traffic_Light_Comp_5
DialogueData_Power_Plant_Comp:
    .word DialogueData_Power_Plant_Comp_1
    .word DialogueData_Power_Plant_Comp_2
    .word DialogueData_Power_Plant_Comp_3
    .word DialogueData_Power_Plant_Comp_4
DialogueData_WWW_Comp:
    .word DialogueData_WWW_Comp_1
    .word DialogueData_WWW_Comp_2
    .word DialogueData_WWW_Comp_3
    .word DialogueData_WWW_Comp_4
    .word DialogueData_WWW_Comp_5
    .word DialogueData_Rocket_Comp
DialogueData_ACDC_HP:
    .word DialogueData_ACDC_Lan_PC
    .word DialogueData_ACDC_Mayl_PC
    .word DialogueData_ACDC_Yai_PC
    .word DialogueData_ACDC_Dex_PC
DialogueData_Govt_Complex_HP:
    .word DialogueData_Govt_Yuichiro_PC
    .word DialogueData_Govt_Lunch_Cart_Comp
DialogueData_DenTown_HP:
    .word DialogueData_DenTown_Antique_Comp
DialogueData_SciLab_HP:
    .word DialogueData_SciLab_Fish_Stand_Comp
DialogueData_Other_Comp:
    .word DialogueData_Other_Doghouse_Comp
    .word DialogueData_Other_Servbot_Comp
    .word DialogueData_Other_New_Game_Machine_Comp
    .word DialogueData_Other_Telephone_Comp
    .word DialogueData_Other_Car_Comp
    .word DialogueData_Other_Waterworks_Vending_Machine
    .word DialogueData_Other_Lobby_TV_Comp
    .word DialogueData_Other_Large_Monitor_Comp
    .word DialogueData_Other_Control_Equipment_Comp
    .word DialogueData_Other_SciLab_Vending_Machine
    .word DialogueData_Other_Recycled_PET_Comp
    .word DialogueData_Other_Big_Vase_Comp
    .word DialogueData_Other_Blackboard_Comp
DialogueData_Internet:
    .word DialogueData_Internet_1
    .word DialogueData_Internet_2
    .word DialogueData_Internet_3
    .word DialogueData_Internet_4
    .word DialogueData_Undernet_1
    .word DialogueData_Undernet_2
    .word DialogueData_Undernet_3
    .word DialogueData_Undernet_4
    .word DialogueData_Undernet_5
    .word DialogueData_Undernet_6
    .word DialogueData_Undernet_7
    .word DialogueData_Undernet_8
    .word DialogueData_Undernet_9
    .word DialogueData_Undernet_10
    .word DialogueData_Undernet_11
    .word DialogueData_Undernet_12
DialogueData_Battle_Other:
    .word 0
    .word 0
CommentaryData_Offline:
    .word CommentaryData_School
    .word CommentaryData_ACDC
    .word CommentaryData_Govt
    .word CommentaryData_DenTown
    .word CommentaryData_SciLab
    .word CommentaryData_WWW
CommentaryData_Online:
    .word CommentaryData_School_Comp
    .word CommentaryData_Oven_Comp
    .word CommentaryData_Waterworks_Comp
    .word CommentaryData_Traffic_Light_Comp
    .word CommentaryData_Power_Plant_Comp
    .word CommentaryData_WWW_Comp
    .word 0
    .word 0
    .word CommentaryData_ACDC_HP
    .word CommentaryData_Govt_Complex_HP
    .word CommentaryData_DenTown_HP
    .word CommentaryData_SciLab_HP
    .word CommentaryData_Other
    .word 0
    .word 0
    .word 0
    .word CommentaryData_Internet
CommentaryData_Battle:
    .word PTR_080151c0
CommentaryData_School:
    .word CommentaryData_School_Class_5A
    .word CommentaryData_School_Class_5B
    .word CommentaryData_School_Library
    .word CommentaryData_School_2F_Hallway
    .word CommentaryData_None
    .word CommentaryData_School_Class_1A
    .word CommentaryData_School_Class_1B
    .word CommentaryData_School_AV_Room
    .word CommentaryData_School_Infirmary
    .word CommentaryData_School_1F_Hallway
    .word CommentaryData_None
    .word CommentaryData_School_Cross_Hallway
    .word CommentaryData_School_Storage
    .word CommentaryData_School_Staff_Lounge
    .word CommentaryData_School_Staff_Lounge_Hallway
CommentaryData_ACDC:
    .word CommentaryData_ACDC_Town
    .word CommentaryData_ACDC_School_Gate
    .word CommentaryData_ACDC_Lan_Living_Room
    .word CommentaryData_ACDC_Lan_Room
    .word CommentaryData_None
    .word CommentaryData_ACDC_Mayl_Living_Room
    .word CommentaryData_ACDC_Mayl_Room
    .word CommentaryData_ACDC_Dex_Room
    .word CommentaryData_None
    .word CommentaryData_ACDC_Yai_Room
    .word CommentaryData_None
    .word CommentaryData_ACDC_Higsbys
    .word CommentaryData_ACDC_Station
    .word CommentaryData_ACDC_Secret_Station
CommentaryData_Govt:
    .word CommentaryData_Govt_Complex_Front
    .word CommentaryData_Govt_Complex_Station
    .word CommentaryData_Govt_Waterworks_Lobby
    .word CommentaryData_Govt_SciLab_Lobby
    .word CommentaryData_Govt_Complex_Hallway
    .word CommentaryData_Govt_Yuichiro_Lab
    .word CommentaryData_Govt_Waterworks_Office
    .word CommentaryData_Govt_Waterworks_Control_Room
    .word CommentaryData_None
    .word CommentaryData_Govt_Waterworks_Pump_Room
    .word CommentaryData_None
    .word CommentaryData_Govt_Waterworks_Purification_Room
CommentaryData_DenTown:
    .word CommentaryData_DenTown_Center
    .word CommentaryData_DenTown_Station
    .word CommentaryData_DenTown_Block_1
    .word CommentaryData_DenTown_Block_2
    .word CommentaryData_DenTown_Block_3
    .word CommentaryData_DenTown_Block_4
    .word CommentaryData_DenTown_Miyu_Antiques
    .word CommentaryData_DenTown_Summer_School
CommentaryData_SciLab:
    .word CommentaryData_SciLab_Restaurant_Hallway
    .word CommentaryData_SciLab_Restaurant
    .word CommentaryData_SciLab_Power_Plant_Hallway
    .word CommentaryData_SciLab_Power_Plant
    .word CommentaryData_SciLab_Power_Plant_Control_Room
    .word CommentaryData_SciLab_Generator_Room
CommentaryData_WWW:
    .word CommentaryData_WWW_Base
    .word CommentaryData_WWW_Wily_Lab
    .word CommentaryData_None
    .word CommentaryData_WWW_Passage_1
    .word CommentaryData_WWW_Passage_2
    .word CommentaryData_WWW_Passage_3
CommentaryData_School_Comp:
    .word CommentaryData_School_Comp_1
    .word CommentaryData_School_Comp_2
    .word CommentaryData_School_Comp_3
    .word CommentaryData_School_Comp_4
    .word CommentaryData_School_Comp_5
CommentaryData_Oven_Comp:
    .word CommentaryData_Oven_Comp_1
    .word CommentaryData_Oven_Comp_2
CommentaryData_Waterworks_Comp:
    .word CommentaryData_Waterworks_Comp_1
    .word CommentaryData_Waterworks_Comp_2
    .word CommentaryData_Waterworks_Comp_3
    .word CommentaryData_Waterworks_Comp_4
    .word CommentaryData_Waterworks_Comp_5
    .word CommentaryData_Waterworks_Comp_6
CommentaryData_Traffic_Light_Comp:
    .word CommentaryData_Traffic_Light_Comp_1
    .word CommentaryData_Traffic_Light_Comp_2
    .word CommentaryData_Traffic_Light_Comp_3
    .word CommentaryData_Traffic_Light_Comp_4
    .word CommentaryData_Traffic_Light_Comp_5
CommentaryData_Power_Plant_Comp:
    .word CommentaryData_Power_Plant_Comp_1
    .word CommentaryData_Power_Plant_Comp_2
    .word CommentaryData_Power_Plant_Comp_3
    .word CommentaryData_Power_Plant_Comp_4
CommentaryData_WWW_Comp:
    .word CommentaryData_WWW_Comp_1
    .word CommentaryData_WWW_Comp_2
    .word CommentaryData_WWW_Comp_3
    .word CommentaryData_WWW_Comp_4
    .word CommentaryData_WWW_Comp_5
    .word CommentaryData_Rocket_Comp
CommentaryData_ACDC_HP:
    .word CommentaryData_ACDC_Lan_PC
    .word CommentaryData_ACDC_Mayl_PC
    .word CommentaryData_ACDC_Yai_PC
    .word CommentaryData_ACDC_Dex_PC
CommentaryData_Govt_Complex_HP:
    .word CommentaryData_Govt_Yuichiro_PC
    .word CommentaryData_Govt_Lunch_Cart_Comp
CommentaryData_DenTown_HP:
    .word CommentaryData_DenTown_Antique_Comp
CommentaryData_SciLab_HP:
    .word CommentaryData_SciLab_Fish_Stand_Comp
CommentaryData_Other:
    .word CommentaryData_Other_Doghouse_Comp
    .word CommentaryData_Other_Servbot_Comp
    .word CommentaryData_Other_New_Game_Machine_Comp
    .word CommentaryData_Other_Telephone_Comp
    .word CommentaryData_Other_Car_Comp
    .word CommentaryData_Other_Waterworks_Vending_Machine
    .word CommentaryData_Other_Lobby_TV_Comp
    .word CommentaryData_Other_Large_Monitor_Comp
    .word CommentaryData_Other_Control_Equipment_Comp
    .word CommentaryData_Other_SciLab_Vending_Machine
    .word CommentaryData_Other_Recycled_PET_Comp
    .word CommentaryData_Other_Big_Vase_Comp
    .word CommentaryData_Other_Blackboard_Comp
CommentaryData_Internet:
    .word CommentaryData_Internet_1
    .word CommentaryData_Internet_2
    .word CommentaryData_Internet_3
    .word CommentaryData_Internet_4
    .word CommentaryData_Undernet_1
    .word CommentaryData_Undernet_2
    .word CommentaryData_Undernet_3
    .word CommentaryData_Undernet_4
    .word CommentaryData_Undernet_5
    .word CommentaryData_Undernet_6
    .word CommentaryData_Undernet_7
    .word CommentaryData_Undernet_8
    .word CommentaryData_Undernet_9
    .word CommentaryData_Undernet_10
    .word CommentaryData_Undernet_11
    .word CommentaryData_Undernet_12
PTR_080151c0:
    .word 0
    .word 0
