global_label DialogueData_Offline
    .word DialogueData_ACDC_Elementary
    .word DialogueData_ACDC_Town
    .word DialogueData_Govt_Complex
    .word DialogueData_DenTown
    .word DialogueData_SciLab
    .word DialogueData_WWW_Base

global_label DialogueData_Online
    .word DialogueData_School_Comp
    .word DialogueData_Oven_Comp
    .word DialogueData_Waterworks_Comp
    .word DialogueData_Traffic_Light_Comp
    .word DialogueData_Power_Plant_Comp
    .word DialogueData_WWW_Comp
    .word 0
    .word 0
    .word DialogueData_ACDC_HP
    .word DialogueData_Govt_Complex_HP
    .word DialogueData_DenTown_HP
    .word DialogueData_SciLab_HP
    .word DialogueData_Other_Comp
    .word 0
    .word 0
    .word 0
    .word DialogueData_Internet

global_label DialogueData_Battle
    .word DialogueData_Battle_Other

DialogueData_ACDC_Elementary:
    .word DialogueData_ACDC_Elementary_Area_0
    .word DialogueData_ACDC_Elementary_Area_1
    .word DialogueData_ACDC_Elementary_Area_2
    .word DialogueData_ACDC_Elementary_Area_3
    .word 0
    .word DialogueData_ACDC_Elementary_Area_5
    .word DialogueData_ACDC_Elementary_Area_6
    .word DialogueData_ACDC_Elementary_Area_7
    .word DialogueData_ACDC_Elementary_Area_8
    .word DialogueData_ACDC_Elementary_Area_9
    .word 0
    .word DialogueData_ACDC_Elementary_Area_B
    .word DialogueData_ACDC_Elementary_Area_C
    .word DialogueData_ACDC_Elementary_Area_D
    .word DialogueData_ACDC_Elementary_Area_E
DialogueData_ACDC_Town:
    .word DialogueData_ACDC_Town_Area_0
    .word DialogueData_ACDC_Town_Area_1
    .word DialogueData_ACDC_Town_Area_2
    .word DialogueData_ACDC_Town_Area_3
    .word 0
    .word DialogueData_ACDC_Town_Area_5
    .word DialogueData_ACDC_Town_Area_6
    .word DialogueData_ACDC_Town_Area_7
    .word 0
    .word DialogueData_ACDC_Town_Area_9
    .word 0
    .word DialogueData_ACDC_Town_Area_B
    .word DialogueData_ACDC_Town_Area_C
DialogueData_Govt_Complex:
    .word DialogueData_Govt_Complex_Area_0
    .word DialogueData_Govt_Complex_Area_1
    .word DialogueData_Govt_Complex_Area_2
    .word DialogueData_Govt_Complex_Area_3
    .word 0
    .word DialogueData_Govt_Complex_Area_5
    .word DialogueData_Govt_Complex_Area_6
    .word DialogueData_Govt_Complex_Area_7
    .word 0
    .word DialogueData_Govt_Complex_Area_9
    .word 0
    .word DialogueData_Govt_Complex_Area_B
DialogueData_DenTown:
    .word DialogueData_DenTown_Area_0
    .word DialogueData_DenTown_Area_1
    .word DialogueData_DenTown_Area_2
    .word DialogueData_DenTown_Area_3
    .word DialogueData_DenTown_Area_4
    .word DialogueData_DenTown_Area_5
    .word DialogueData_DenTown_Area_6
    .word DialogueData_DenTown_Area_7
DialogueData_SciLab:
    .word DialogueData_SciLab_Area_0
    .word DialogueData_SciLab_Area_1
    .word DialogueData_SciLab_Area_2
    .word DialogueData_SciLab_Area_3
    .word DialogueData_SciLab_Area_4
    .word DialogueData_SciLab_Area_5
DialogueData_WWW_Base:
    .word DialogueData_WWW_Base_Area_0
    .word DialogueData_WWW_Base_Area_1
    .word DialogueData_WWW_Base_Area_2
    .word DialogueData_WWW_Base_Area_3
    .word DialogueData_WWW_Base_Area_4
    .word DialogueData_WWW_Base_Area_5
DialogueData_School_Comp:
    .word DialogueData_School_Comp_Area_0
    .word DialogueData_School_Comp_Area_1
    .word DialogueData_School_Comp_Area_2
    .word DialogueData_School_Comp_Area_3
    .word DialogueData_School_Comp_Area_4
DialogueData_Oven_Comp:
    .word DialogueData_Oven_Comp_Area_0
    .word DialogueData_Oven_Comp_Area_1
DialogueData_Waterworks_Comp:
    .word DialogueData_Waterworks_Comp_Area_0
    .word DialogueData_Waterworks_Comp_Area_1
    .word DialogueData_Waterworks_Comp_Area_2
    .word DialogueData_Waterworks_Comp_Area_3
    .word DialogueData_Waterworks_Comp_Area_4
    .word DialogueData_Waterworks_Comp_Area_5
DialogueData_Traffic_Light_Comp:
    .word DialogueData_Traffic_Light_Comp_Area_0
    .word DialogueData_Traffic_Light_Comp_Area_1
    .word DialogueData_Traffic_Light_Comp_Area_2
    .word DialogueData_Traffic_Light_Comp_Area_3
    .word DialogueData_Traffic_Light_Comp_Area_4
DialogueData_Power_Plant_Comp:
    .word DialogueData_Power_Plant_Comp_Area_0
    .word DialogueData_Power_Plant_Comp_Area_1
    .word DialogueData_Power_Plant_Comp_Area_2
    .word DialogueData_Power_Plant_Comp_Area_3
DialogueData_WWW_Comp:
    .word DialogueData_WWW_Comp_Area_0
    .word DialogueData_WWW_Comp_Area_1
    .word DialogueData_WWW_Comp_Area_2
    .word DialogueData_WWW_Comp_Area_3
    .word DialogueData_WWW_Comp_Area_4
    .word DialogueData_WWW_Comp_Area_5
DialogueData_ACDC_HP:
    .word DialogueData_ACDC_HP_Area_0
    .word DialogueData_ACDC_HP_Area_1
    .word DialogueData_ACDC_HP_Area_2
    .word DialogueData_ACDC_HP_Area_3
DialogueData_Govt_Complex_HP:
    .word DialogueData_Govt_Complex_HP_Area_0
    .word DialogueData_Govt_Complex_HP_Area_1
DialogueData_DenTown_HP:
    .word DialogueData_DenTown_HP_Area_0
DialogueData_SciLab_HP:
    .word DialogueData_SciLab_HP_Area_0
DialogueData_Other_Comp:
    .word DialogueData_Other_Comp_Area_0
    .word DialogueData_Other_Comp_Area_1
    .word DialogueData_Other_Comp_Area_2
    .word DialogueData_Other_Comp_Area_3
    .word DialogueData_Other_Comp_Area_4
    .word DialogueData_Other_Comp_Area_5
    .word DialogueData_Other_Comp_Area_6
    .word DialogueData_Other_Comp_Area_7
    .word DialogueData_Other_Comp_Area_8
    .word DialogueData_Other_Comp_Area_9
    .word DialogueData_Other_Comp_Area_A
    .word DialogueData_Other_Comp_Area_B
    .word DialogueData_Other_Comp_Area_C
DialogueData_Internet:
    .word DialogueData_Internet_Area_0
    .word DialogueData_Internet_Area_1
    .word DialogueData_Internet_Area_2
    .word DialogueData_Internet_Area_3
    .word DialogueData_Internet_Area_4
    .word DialogueData_Internet_Area_5
    .word DialogueData_Internet_Area_6
    .word DialogueData_Internet_Area_7
    .word DialogueData_Internet_Area_8
    .word DialogueData_Internet_Area_9
    .word DialogueData_Internet_Area_A
    .word DialogueData_Internet_Area_B
    .word DialogueData_Internet_Area_C
    .word DialogueData_Internet_Area_D
    .word DialogueData_Internet_Area_E
    .word DialogueData_Internet_Area_F
DialogueData_Battle_Other:
    .word 0
    .word 0
CommentaryData_Offline:
    .word CommentaryData_ACDC_Elementary
    .word CommentaryData_ACDC_Town
    .word CommentaryData_Govt_Complex
    .word CommentaryData_DenTown
    .word CommentaryData_SciLab
    .word CommentaryData_WWW_Base
CommentaryData_Online:
    .word CommentaryData_School_Comp
    .word CommentaryData_Oven_Comp
    .word CommentaryData_Waterworks_Comp
    .word CommentaryData_Traffic_Light_Comp
    .word CommentaryData_Power_Plant_Comp
    .word CommentaryData_WWW_Comp
    .word 0
    .word 0
    .word CommentaryData_ACDC_HP
    .word CommentaryData_Govt_Complex_HP
    .word CommentaryData_DenTown_HP
    .word CommentaryData_SciLab_HP
    .word CommentaryData_Other
    .word 0
    .word 0
    .word 0
    .word CommentaryData_Internet
CommentaryData_Battle:
    .word PTR_080151c0
CommentaryData_ACDC_Elementary:
    .word CommentaryData_ACDC_Elementary_Area_0
    .word CommentaryData_ACDC_Elementary_Area_1
    .word CommentaryData_ACDC_Elementary_Area_2
    .word CommentaryData_ACDC_Elementary_Area_3
    .word CommentaryData_None
    .word CommentaryData_ACDC_Elementary_Area_5
    .word CommentaryData_ACDC_Elementary_Area_6
    .word CommentaryData_ACDC_Elementary_Area_7
    .word CommentaryData_ACDC_Elementary_Area_8
    .word CommentaryData_ACDC_Elementary_Area_9
    .word CommentaryData_None
    .word CommentaryData_ACDC_Elementary_Area_B
    .word CommentaryData_ACDC_Elementary_Area_C
    .word CommentaryData_ACDC_Elementary_Area_D
    .word CommentaryData_ACDC_Elementary_Area_E
CommentaryData_ACDC_Town:
    .word CommentaryData_ACDC_Town_Area_0
    .word CommentaryData_ACDC_Town_Area_1
    .word CommentaryData_ACDC_Town_Area_2
    .word CommentaryData_ACDC_Town_Area_3
    .word CommentaryData_None
    .word CommentaryData_ACDC_Town_Area_5
    .word CommentaryData_ACDC_Town_Area_6
    .word CommentaryData_ACDC_Town_Area_7
    .word CommentaryData_None
    .word CommentaryData_ACDC_Town_Area_9
    .word CommentaryData_None
    .word CommentaryData_ACDC_Town_Area_B
    .word CommentaryData_ACDC_Town_Area_C
    .word CommentaryData_ACDC_Town_Area_D
CommentaryData_Govt_Complex:
    .word CommentaryData_Govt_Complex_Area_0
    .word CommentaryData_Govt_Complex_Area_1
    .word CommentaryData_Govt_Complex_Area_2
    .word CommentaryData_Govt_Complex_Area_3
    .word CommentaryData_Govt_Complex_Area_4
    .word CommentaryData_Govt_Complex_Area_5
    .word CommentaryData_Govt_Complex_Area_6
    .word CommentaryData_Govt_Complex_Area_7
    .word CommentaryData_None
    .word CommentaryData_Govt_Complex_Area_9
    .word CommentaryData_None
    .word CommentaryData_Govt_Complex_Area_B
CommentaryData_DenTown:
    .word CommentaryData_DenTown_Area_0
    .word CommentaryData_DenTown_Area_1
    .word CommentaryData_DenTown_Area_2
    .word CommentaryData_DenTown_Area_3
    .word CommentaryData_DenTown_Area_4
    .word CommentaryData_DenTown_Area_5
    .word CommentaryData_DenTown_Area_6
    .word CommentaryData_DenTown_Area_7
CommentaryData_SciLab:
    .word CommentaryData_SciLab_Area_0
    .word CommentaryData_SciLab_Area_1
    .word CommentaryData_SciLab_Area_2
    .word CommentaryData_SciLab_Area_3
    .word CommentaryData_SciLab_Area_4
    .word CommentaryData_SciLab_Area_5
CommentaryData_WWW_Base:
    .word CommentaryData_WWW_Base_Area_0
    .word CommentaryData_WWW_Base_Area_1
    .word CommentaryData_None
    .word CommentaryData_WWW_Base_Area_3
    .word CommentaryData_WWW_Base_Area_4
    .word CommentaryData_WWW_Base_Area_5
CommentaryData_School_Comp:
    .word CommentaryData_School_Comp_Area_0
    .word CommentaryData_School_Comp_Area_1
    .word CommentaryData_School_Comp_Area_2
    .word CommentaryData_School_Comp_Area_3
    .word CommentaryData_School_Comp_Area_4
CommentaryData_Oven_Comp:
    .word CommentaryData_Oven_Comp_Area_0
    .word CommentaryData_Oven_Comp_Area_1
CommentaryData_Waterworks_Comp:
    .word CommentaryData_Waterworks_Comp_Area_0
    .word CommentaryData_Waterworks_Comp_Area_1
    .word CommentaryData_Waterworks_Comp_Area_2
    .word CommentaryData_Waterworks_Comp_Area_3
    .word CommentaryData_Waterworks_Comp_Area_4
    .word CommentaryData_Waterworks_Comp_Area_5
CommentaryData_Traffic_Light_Comp:
    .word CommentaryData_Traffic_Light_Comp_Area_0
    .word CommentaryData_Traffic_Light_Comp_Area_1
    .word CommentaryData_Traffic_Light_Comp_Area_2
    .word CommentaryData_Traffic_Light_Comp_Area_3
    .word CommentaryData_Traffic_Light_Comp_Area_4
CommentaryData_Power_Plant_Comp:
    .word CommentaryData_Power_Plant_Comp_Area_0
    .word CommentaryData_Power_Plant_Comp_Area_1
    .word CommentaryData_Power_Plant_Comp_Area_2
    .word CommentaryData_Power_Plant_Comp_Area_3
CommentaryData_WWW_Comp:
    .word CommentaryData_WWW_Comp_Area_0
    .word CommentaryData_WWW_Comp_Area_1
    .word CommentaryData_WWW_Comp_Area_2
    .word CommentaryData_WWW_Comp_Area_3
    .word CommentaryData_WWW_Comp_Area_4
    .word CommentaryData_WWW_Comp_Area_5
CommentaryData_ACDC_HP:
    .word CommentaryData_ACDC_HP_Area_0
    .word CommentaryData_ACDC_HP_Area_1
    .word CommentaryData_ACDC_HP_Area_2
    .word CommentaryData_ACDC_HP_Area_3
CommentaryData_Govt_Complex_HP:
    .word CommentaryData_Govt_Complex_HP_Area_0
    .word CommentaryData_Govt_Complex_HP_Area_1
CommentaryData_DenTown_HP:
    .word CommentaryData_DenTown_HP_Area_0
CommentaryData_SciLab_HP:
    .word CommentaryData_SciLab_HP_Area_0
CommentaryData_Other:
    .word CommentaryData_Other_Comp_Area_0
    .word CommentaryData_Other_Comp_Area_1
    .word CommentaryData_Other_Comp_Area_2
    .word CommentaryData_Other_Comp_Area_3
    .word CommentaryData_Other_Comp_Area_4
    .word CommentaryData_Other_Comp_Area_5
    .word CommentaryData_Other_Comp_Area_6
    .word CommentaryData_Other_Comp_Area_7
    .word CommentaryData_Other_Comp_Area_8
    .word CommentaryData_Other_Comp_Area_9
    .word CommentaryData_Other_Comp_Area_A
    .word CommentaryData_Other_Comp_Area_B
    .word CommentaryData_Other_Comp_Area_C
CommentaryData_Internet:
    .word CommentaryData_Internet_Area_0
    .word CommentaryData_Internet_Area_1
    .word CommentaryData_Internet_Area_2
    .word CommentaryData_Internet_Area_3
    .word CommentaryData_Internet_Area_4
    .word CommentaryData_Internet_Area_5
    .word CommentaryData_Internet_Area_6
    .word CommentaryData_Internet_Area_7
    .word CommentaryData_Internet_Area_8
    .word CommentaryData_Internet_Area_9
    .word CommentaryData_Internet_Area_A
    .word CommentaryData_Internet_Area_B
    .word CommentaryData_Internet_Area_C
    .word CommentaryData_Internet_Area_D
    .word CommentaryData_Internet_Area_E
    .word CommentaryData_Internet_Area_F
PTR_080151c0:
    .word 0
    .word 0
