global_label DialogueData_Offline
    .word DialogueData_School
    .word DialogueData_ACDC
    .word DialogueData_Govt
    .word DialogueData_DenTown
    .word DialogueData_SciLab
    .word DialogueData_WWW

global_label DialogueData_Online
    .word DialogueData_School_Comp
    .word DialogueData_Oven_Comp
    .word DialogueData_Waterworks_Comp
    .word DialogueData_Traffic_Light_Comp
    .word DialogueData_Power_Plant_Comp
    .word DialogueData_WWW_Comp
    .word 0
    .word 0
    .word DialogueData_ACDC_HP
    .word DialogueData_Govt_Complex_HP
    .word DialogueData_DenTown_HP
    .word DialogueData_SciLab_HP
    .word DialogueData_Other_Comp
    .word 0
    .word 0
    .word 0
    .word DialogueData_Internet

global_label DialogueData_Battle
    .word DialogueData_Battle_Other

DialogueData_School:
    .word DialogueData_School_Class_5A
    .word DialogueData_School_Class_5B
    .word DialogueData_School_Library
    .word DialogueData_School_2F_Hallway
    .word 0
    .word DialogueData_School_Class_1A
    .word DialogueData_School_Class_1B
    .word DialogueData_School_AV_Room
    .word DialogueData_School_Infirmary
    .word DialogueData_School_1F_Hallway
    .word 0
    .word DialogueData_School_Cross_Hallway
    .word DialogueData_School_Storage
    .word DialogueData_School_Staff_Lounge
    .word DialogueData_School_Staff_Lounge_Hallway

DialogueData_ACDC:
    .word DialogueData_ACDC_Town
    .word DialogueData_ACDC_School_Gate
    .word DialogueData_ACDC_Lan_Living_Room
    .word DialogueData_ACDC_Lan_Room
    .word 0
    .word DialogueData_ACDC_Mayl_Living_Room
    .word DialogueData_ACDC_Mayl_Room
    .word DialogueData_ACDC_Dex_Room
    .word 0
    .word DialogueData_ACDC_Yai_Room
    .word 0
    .word DialogueData_ACDC_Higsbys
    .word DialogueData_ACDC_Station
DialogueData_Govt:
    .word DialogueData_Govt_Complex_Front
    .word DialogueData_Govt_Complex_Station
    .word DialogueData_Govt_Waterworks_Lobby
    .word DialogueData_Govt_SciLab_Lobby
    .word 0
    .word DialogueData_Govt_Yuichiro_Lab
    .word DialogueData_Govt_Waterworks_Office
    .word DialogueData_Govt_Waterworks_Control_Room
    .word 0
    .word DialogueData_Govt_Waterworks_Pump_Room
    .word 0
    .word DialogueData_Govt_Waterworks_Purification_Room
DialogueData_DenTown:
    .word DialogueData_DenTown_Area_0
    .word DialogueData_DenTown_Area_1
    .word DialogueData_DenTown_Area_2
    .word DialogueData_DenTown_Area_3
    .word DialogueData_DenTown_Area_4
    .word DialogueData_DenTown_Area_5
    .word DialogueData_DenTown_Area_6
    .word DialogueData_DenTown_Area_7
DialogueData_SciLab:
    .word DialogueData_SciLab_Area_0
    .word DialogueData_SciLab_Area_1
    .word DialogueData_SciLab_Area_2
    .word DialogueData_SciLab_Area_3
    .word DialogueData_SciLab_Area_4
    .word DialogueData_SciLab_Area_5
DialogueData_WWW:
    .word DialogueData_WWW_Base_Area_0
    .word DialogueData_WWW_Base_Area_1
    .word DialogueData_WWW_Base_Area_2
    .word DialogueData_WWW_Base_Area_3
    .word DialogueData_WWW_Base_Area_4
    .word DialogueData_WWW_Base_Area_5
DialogueData_School_Comp:
    .word DialogueData_School_Comp_Area_0
    .word DialogueData_School_Comp_Area_1
    .word DialogueData_School_Comp_Area_2
    .word DialogueData_School_Comp_Area_3
    .word DialogueData_School_Comp_Area_4
DialogueData_Oven_Comp:
    .word DialogueData_Oven_Comp_Area_0
    .word DialogueData_Oven_Comp_Area_1
DialogueData_Waterworks_Comp:
    .word DialogueData_Waterworks_Comp_Area_0
    .word DialogueData_Waterworks_Comp_Area_1
    .word DialogueData_Waterworks_Comp_Area_2
    .word DialogueData_Waterworks_Comp_Area_3
    .word DialogueData_Waterworks_Comp_Area_4
    .word DialogueData_Waterworks_Comp_Area_5
DialogueData_Traffic_Light_Comp:
    .word DialogueData_Traffic_Light_Comp_Area_0
    .word DialogueData_Traffic_Light_Comp_Area_1
    .word DialogueData_Traffic_Light_Comp_Area_2
    .word DialogueData_Traffic_Light_Comp_Area_3
    .word DialogueData_Traffic_Light_Comp_Area_4
DialogueData_Power_Plant_Comp:
    .word DialogueData_Power_Plant_Comp_Area_0
    .word DialogueData_Power_Plant_Comp_Area_1
    .word DialogueData_Power_Plant_Comp_Area_2
    .word DialogueData_Power_Plant_Comp_Area_3
DialogueData_WWW_Comp:
    .word DialogueData_WWW_Comp_Area_0
    .word DialogueData_WWW_Comp_Area_1
    .word DialogueData_WWW_Comp_Area_2
    .word DialogueData_WWW_Comp_Area_3
    .word DialogueData_WWW_Comp_Area_4
    .word DialogueData_WWW_Comp_Area_5
DialogueData_ACDC_HP:
    .word DialogueData_ACDC_HP_Area_0
    .word DialogueData_ACDC_HP_Area_1
    .word DialogueData_ACDC_HP_Area_2
    .word DialogueData_ACDC_HP_Area_3
DialogueData_Govt_Complex_HP:
    .word DialogueData_Govt_Complex_HP_Area_0
    .word DialogueData_Govt_Complex_HP_Area_1
DialogueData_DenTown_HP:
    .word DialogueData_DenTown_HP_Area_0
DialogueData_SciLab_HP:
    .word DialogueData_SciLab_HP_Area_0
DialogueData_Other_Comp:
    .word DialogueData_Other_Comp_Area_0
    .word DialogueData_Other_Comp_Area_1
    .word DialogueData_Other_Comp_Area_2
    .word DialogueData_Other_Comp_Area_3
    .word DialogueData_Other_Comp_Area_4
    .word DialogueData_Other_Comp_Area_5
    .word DialogueData_Other_Comp_Area_6
    .word DialogueData_Other_Comp_Area_7
    .word DialogueData_Other_Comp_Area_8
    .word DialogueData_Other_Comp_Area_9
    .word DialogueData_Other_Comp_Area_A
    .word DialogueData_Other_Comp_Area_B
    .word DialogueData_Other_Comp_Area_C
DialogueData_Internet:
    .word DialogueData_Internet_Area_0
    .word DialogueData_Internet_Area_1
    .word DialogueData_Internet_Area_2
    .word DialogueData_Internet_Area_3
    .word DialogueData_Internet_Area_4
    .word DialogueData_Internet_Area_5
    .word DialogueData_Internet_Area_6
    .word DialogueData_Internet_Area_7
    .word DialogueData_Internet_Area_8
    .word DialogueData_Internet_Area_9
    .word DialogueData_Internet_Area_A
    .word DialogueData_Internet_Area_B
    .word DialogueData_Internet_Area_C
    .word DialogueData_Internet_Area_D
    .word DialogueData_Internet_Area_E
    .word DialogueData_Internet_Area_F
DialogueData_Battle_Other:
    .word 0
    .word 0
CommentaryData_Offline:
    .word CommentaryData_School
    .word CommentaryData_ACDC
    .word CommentaryData_Govt
    .word CommentaryData_DenTown
    .word CommentaryData_SciLab
    .word CommentaryData_WWW
CommentaryData_Online:
    .word CommentaryData_School_Comp
    .word CommentaryData_Oven_Comp
    .word CommentaryData_Waterworks_Comp
    .word CommentaryData_Traffic_Light_Comp
    .word CommentaryData_Power_Plant_Comp
    .word CommentaryData_WWW_Comp
    .word 0
    .word 0
    .word CommentaryData_ACDC_HP
    .word CommentaryData_Govt_Complex_HP
    .word CommentaryData_DenTown_HP
    .word CommentaryData_SciLab_HP
    .word CommentaryData_Other
    .word 0
    .word 0
    .word 0
    .word CommentaryData_Internet
CommentaryData_Battle:
    .word PTR_080151c0
CommentaryData_School:
    .word CommentaryData_School_Class_5A
    .word CommentaryData_School_Class_5B
    .word CommentaryData_School_Library
    .word CommentaryData_School_2F_Hallway
    .word CommentaryData_None
    .word CommentaryData_School_Class_1A
    .word CommentaryData_School_Class_1B
    .word CommentaryData_School_AV_Room
    .word CommentaryData_School_Infirmary
    .word CommentaryData_School_1F_Hallway
    .word CommentaryData_None
    .word CommentaryData_School_Cross_Hallway
    .word CommentaryData_School_Storage
    .word CommentaryData_School_Staff_Lounge
    .word CommentaryData_School_Staff_Lounge_Hallway
CommentaryData_ACDC:
    .word CommentaryData_ACDC_Town
    .word CommentaryData_ACDC_School_Gate
    .word CommentaryData_ACDC_Lan_Living_Room
    .word CommentaryData_ACDC_Lan_Room
    .word CommentaryData_None
    .word CommentaryData_ACDC_Mayl_Living_Room
    .word CommentaryData_ACDC_Mayl_Room
    .word CommentaryData_ACDC_Dex_Room
    .word CommentaryData_None
    .word CommentaryData_ACDC_Yai_Room
    .word CommentaryData_None
    .word CommentaryData_ACDC_Higsbys
    .word CommentaryData_ACDC_Station
    .word CommentaryData_ACDC_Secret_Station
CommentaryData_Govt:
    .word CommentaryData_Govt_Complex_Front
    .word CommentaryData_Govt_Complex_Station
    .word CommentaryData_Govt_Waterworks_Lobby
    .word CommentaryData_Govt_SciLab_Lobby
    .word CommentaryData_Govt_Complex_Hallway
    .word CommentaryData_Govt_Yuichiro_Lab
    .word CommentaryData_Govt_Waterworks_Office
    .word CommentaryData_Govt_Waterworks_Control_Room
    .word CommentaryData_None
    .word CommentaryData_Govt_Waterworks_Pump_Room
    .word CommentaryData_None
    .word CommentaryData_Govt_Waterworks_Purification_Room
CommentaryData_DenTown:
    .word CommentaryData_DenTown_Area_0
    .word CommentaryData_DenTown_Area_1
    .word CommentaryData_DenTown_Area_2
    .word CommentaryData_DenTown_Area_3
    .word CommentaryData_DenTown_Area_4
    .word CommentaryData_DenTown_Area_5
    .word CommentaryData_DenTown_Area_6
    .word CommentaryData_DenTown_Area_7
CommentaryData_SciLab:
    .word CommentaryData_SciLab_Area_0
    .word CommentaryData_SciLab_Area_1
    .word CommentaryData_SciLab_Area_2
    .word CommentaryData_SciLab_Area_3
    .word CommentaryData_SciLab_Area_4
    .word CommentaryData_SciLab_Area_5
CommentaryData_WWW:
    .word CommentaryData_WWW_Base_Area_0
    .word CommentaryData_WWW_Base_Area_1
    .word CommentaryData_None
    .word CommentaryData_WWW_Base_Area_3
    .word CommentaryData_WWW_Base_Area_4
    .word CommentaryData_WWW_Base_Area_5
CommentaryData_School_Comp:
    .word CommentaryData_School_Comp_Area_0
    .word CommentaryData_School_Comp_Area_1
    .word CommentaryData_School_Comp_Area_2
    .word CommentaryData_School_Comp_Area_3
    .word CommentaryData_School_Comp_Area_4
CommentaryData_Oven_Comp:
    .word CommentaryData_Oven_Comp_Area_0
    .word CommentaryData_Oven_Comp_Area_1
CommentaryData_Waterworks_Comp:
    .word CommentaryData_Waterworks_Comp_Area_0
    .word CommentaryData_Waterworks_Comp_Area_1
    .word CommentaryData_Waterworks_Comp_Area_2
    .word CommentaryData_Waterworks_Comp_Area_3
    .word CommentaryData_Waterworks_Comp_Area_4
    .word CommentaryData_Waterworks_Comp_Area_5
CommentaryData_Traffic_Light_Comp:
    .word CommentaryData_Traffic_Light_Comp_Area_0
    .word CommentaryData_Traffic_Light_Comp_Area_1
    .word CommentaryData_Traffic_Light_Comp_Area_2
    .word CommentaryData_Traffic_Light_Comp_Area_3
    .word CommentaryData_Traffic_Light_Comp_Area_4
CommentaryData_Power_Plant_Comp:
    .word CommentaryData_Power_Plant_Comp_Area_0
    .word CommentaryData_Power_Plant_Comp_Area_1
    .word CommentaryData_Power_Plant_Comp_Area_2
    .word CommentaryData_Power_Plant_Comp_Area_3
CommentaryData_WWW_Comp:
    .word CommentaryData_WWW_Comp_Area_0
    .word CommentaryData_WWW_Comp_Area_1
    .word CommentaryData_WWW_Comp_Area_2
    .word CommentaryData_WWW_Comp_Area_3
    .word CommentaryData_WWW_Comp_Area_4
    .word CommentaryData_WWW_Comp_Area_5
CommentaryData_ACDC_HP:
    .word CommentaryData_ACDC_HP_Area_0
    .word CommentaryData_ACDC_HP_Area_1
    .word CommentaryData_ACDC_HP_Area_2
    .word CommentaryData_ACDC_HP_Area_3
CommentaryData_Govt_Complex_HP:
    .word CommentaryData_Govt_Complex_HP_Area_0
    .word CommentaryData_Govt_Complex_HP_Area_1
CommentaryData_DenTown_HP:
    .word CommentaryData_DenTown_HP_Area_0
CommentaryData_SciLab_HP:
    .word CommentaryData_SciLab_HP_Area_0
CommentaryData_Other:
    .word CommentaryData_Other_Comp_Area_0
    .word CommentaryData_Other_Comp_Area_1
    .word CommentaryData_Other_Comp_Area_2
    .word CommentaryData_Other_Comp_Area_3
    .word CommentaryData_Other_Comp_Area_4
    .word CommentaryData_Other_Comp_Area_5
    .word CommentaryData_Other_Comp_Area_6
    .word CommentaryData_Other_Comp_Area_7
    .word CommentaryData_Other_Comp_Area_8
    .word CommentaryData_Other_Comp_Area_9
    .word CommentaryData_Other_Comp_Area_A
    .word CommentaryData_Other_Comp_Area_B
    .word CommentaryData_Other_Comp_Area_C
CommentaryData_Internet:
    .word CommentaryData_Internet_Area_0
    .word CommentaryData_Internet_Area_1
    .word CommentaryData_Internet_Area_2
    .word CommentaryData_Internet_Area_3
    .word CommentaryData_Internet_Area_4
    .word CommentaryData_Internet_Area_5
    .word CommentaryData_Internet_Area_6
    .word CommentaryData_Internet_Area_7
    .word CommentaryData_Internet_Area_8
    .word CommentaryData_Internet_Area_9
    .word CommentaryData_Internet_Area_A
    .word CommentaryData_Internet_Area_B
    .word CommentaryData_Internet_Area_C
    .word CommentaryData_Internet_Area_D
    .word CommentaryData_Internet_Area_E
    .word CommentaryData_Internet_Area_F
PTR_080151c0:
    .word 0
    .word 0
