encounter 0x10, EnemySpawn_0800d32c
encounter 0x10, EnemySpawn_0800d334
encounter 0x10, EnemySpawn_0800d33c
encounter 0x10, EnemySpawn_0800d348
encounter 0x10, EnemySpawn_0800d354
encounter 0x10, EnemySpawn_0800d360
encounter 0x10, EnemySpawn_0800d368
encounter 0x10, EnemySpawn_0800d374
encounter 0x10, EnemySpawn_0800d380
encounter 0x10, EnemySpawn_0800d38c
encounter 0x10, EnemySpawn_0800d39c
encounter 0x10, EnemySpawn_0800d3ac
encounter 0x10, EnemySpawn_0800d3b8
encounter 0x10, EnemySpawn_0800d3c4
encounter 0x10, EnemySpawn_0800d3cc
encounter 0x10, EnemySpawn_0800d3dc

EnemySpawn_0800d32c:
    spawn ColdBear1, 5, 2
    spawn_end

EnemySpawn_0800d334:
    spawn ColdBear1, 4, 3
    spawn_end

EnemySpawn_0800d33c:
    spawn ColdBear1, 6, 3
    spawn ColdBear1, 6, 1
    spawn_end

EnemySpawn_0800d348:
    spawn Cloudy2, 4, 3
    spawn Beetank3, 5, 2
    spawn_end

EnemySpawn_0800d354:
    spawn Beetank3, 4, 2
    spawn Beetank3, 6, 1
    spawn_end

EnemySpawn_0800d360:
    spawn Beetank3, 6, 2
    spawn_end

EnemySpawn_0800d368:
    spawn Piranha2, 4, 3
    spawn Piranha2, 6, 1
    spawn_end

EnemySpawn_0800d374:
    spawn Piranha2, 4, 2
    spawn Beetank3, 5, 2
    spawn_end

EnemySpawn_0800d380:
    spawn Piranha2, 4, 3
    spawn Piranha2, 4, 1
    spawn_end

EnemySpawn_0800d38c:
    spawn Piranha2, 4, 3
    spawn Piranha2, 4, 1
    spawn Beetank3, 5, 2
    spawn_end

EnemySpawn_0800d39c:
    spawn Piranha2, 4, 1
    spawn Piranha2, 5, 3
    spawn Piranha2, 6, 2
    spawn_end

EnemySpawn_0800d3ac:
    spawn ColdBear1, 4, 1
    spawn Beetank3, 6, 2
    spawn_end

EnemySpawn_0800d3b8:
    spawn Cloudy2, 4, 2
    spawn Beetank3, 6, 2
    spawn_end

EnemySpawn_0800d3c4:
    spawn MegalianA, 5, 1
    spawn_end

EnemySpawn_0800d3cc:
    spawn MegalianA, 4, 2
    spawn MegalianA, 4, 1
    spawn Cloudy2, 5, 3
    spawn_end

EnemySpawn_0800d3dc:
    spawn MegalianA, 4, 2
    spawn MegalianA, 6, 1
    spawn_end
