encounter 0x10, EnemySpawn_0800f0a0
encounter 0x10, EnemySpawn_0800f0ac
encounter 0x10, EnemySpawn_0800f0b8
encounter 0x10, EnemySpawn_0800f0c4
encounter 0x10, EnemySpawn_0800f0d0
encounter 0x10, EnemySpawn_0800f0dc
encounter 0x10, EnemySpawn_0800f0e8
encounter 0x10, EnemySpawn_0800f0f8
encounter 0x10, EnemySpawn_0800f104
encounter 0x10, EnemySpawn_0800f110
encounter 0x10, EnemySpawn_0800f120
encounter 0x10, EnemySpawn_0800f128
encounter 0x10, EnemySpawn_0800f138
encounter 0x10, EnemySpawn_0800f144
encounter 0x10, EnemySpawn_0800f14c
encounter 0x10, EnemySpawn_0800f158

EnemySpawn_0800f0a0:
    spawn Piranha2, 5, 2
    spawn Piranha2, 6, 3
    spawn_end

EnemySpawn_0800f0ac:
    spawn Mosqurito1, 5, 3
    spawn Piranha2, 6, 1
    spawn_end

EnemySpawn_0800f0b8:
    spawn Mosqurito1, 4, 2
    spawn Swordy1, 6, 3
    spawn_end

EnemySpawn_0800f0c4:
    spawn Gaia1, 5, 3
    spawn Spooky3, 6, 2
    spawn_end

EnemySpawn_0800f0d0:
    spawn Gaia1, 5, 1
    spawn Gaia1, 6, 3
    spawn_end

EnemySpawn_0800f0dc:
    spawn Mettaur3, 4, 2
    spawn Mettaur3, 4, 1
    spawn_end

EnemySpawn_0800f0e8:
    spawn Piranha2, 4, 1
    spawn Spooky3, 5, 2
    spawn Piranha2, 6, 3
    spawn_end

EnemySpawn_0800f0f8:
    spawn Popper1, 4, 1
    spawn Piranha2, 6, 1
    spawn_end

EnemySpawn_0800f104:
    spawn Spooky3, 4, 2
    spawn Spooky3, 5, 3
    spawn_end

EnemySpawn_0800f110:
    spawn Spooky3, 4, 3
    spawn Spooky3, 5, 1
    spawn Spooky3, 6, 3
    spawn_end

EnemySpawn_0800f120:
    spawn Spooky3, 6, 3
    spawn_end

EnemySpawn_0800f128:
    spawn Swordy1, 4, 3
    spawn Swordy1, 5, 1
    spawn Gaia1, 6, 2
    spawn_end

EnemySpawn_0800f138:
    spawn Piranha2, 4, 3
    spawn Piranha2, 4, 1
    spawn_end

EnemySpawn_0800f144:
    spawn Mosqurito1, 5, 3
    spawn_end

EnemySpawn_0800f14c:
    spawn Mosqurito1, 5, 2
    spawn Mettaur3, 6, 1
    spawn_end

EnemySpawn_0800f158:
    spawn Gaia1, 5, 1
    spawn Beetank3, 6, 2
    spawn_end
