encounter 0x10, EnemySpawn_0800e8e0
encounter 0x10, EnemySpawn_0800e8e8
encounter 0x10, EnemySpawn_0800e8f0
encounter 0x10, EnemySpawn_0800e8fc
encounter 0x10, EnemySpawn_0800e90c
encounter 0x10, EnemySpawn_0800e918
encounter 0x10, EnemySpawn_0800e924
encounter 0x10, EnemySpawn_0800e930
encounter 0x10, EnemySpawn_0800e938
encounter 0x10, EnemySpawn_0800e948
encounter 0x10, EnemySpawn_0800e958
encounter 0x10, EnemySpawn_0800e968
encounter_boss 0x10, EnemySpawn_0800e974
encounter 0x10, EnemySpawn_0800e97c
encounter 0x10, EnemySpawn_0800e98c
encounter 0x10, EnemySpawn_0800e99c

EnemySpawn_0800e8e0:
    spawn Beetank2, 5, 2
    spawn_end

EnemySpawn_0800e8e8:
    spawn Beetank2, 6, 2
    spawn_end

EnemySpawn_0800e8f0:
    spawn Mettaur2, 4, 3
    spawn Mettaur2, 5, 1
    spawn_end

EnemySpawn_0800e8fc:
    spawn Mettaur2, 4, 1
    spawn Mettaur2, 5, 3
    spawn Mettaur2, 6, 2
    spawn_end

EnemySpawn_0800e90c:
    spawn Canodumb2, 5, 3
    spawn Canodumb2, 6, 1
    spawn_end

EnemySpawn_0800e918:
    spawn Beetank2, 5, 2
    spawn Canodumb2, 6, 3
    spawn_end

EnemySpawn_0800e924:
    spawn Mettaur2, 4, 2
    spawn Beetank2, 6, 2
    spawn_end

EnemySpawn_0800e930:
    spawn Billy, 5, 2
    spawn_end

EnemySpawn_0800e938:
    spawn Canodumb2, 5, 3
    spawn Canodumb2, 5, 1
    spawn Beetank2, 6, 2
    spawn_end

EnemySpawn_0800e948:
    spawn Mettaur2, 4, 3
    spawn Mettaur2, 5, 1
    spawn Canodumb2, 6, 2
    spawn_end

EnemySpawn_0800e958:
    spawn Mettaur2, 4, 3
    spawn Mettaur2, 4, 2
    spawn Beetank2, 6, 1
    spawn_end

EnemySpawn_0800e968:
    spawn Billy, 4, 3
    spawn Billy, 5, 1
    spawn_end

EnemySpawn_0800e974:
    spawn StoneManV3, 6, 2
    spawn_end

EnemySpawn_0800e97c:
    spawn Billy, 4, 3
    spawn Fishy1, 5, 1
    spawn Fishy1, 6, 3
    spawn_end

EnemySpawn_0800e98c:
    spawn Fishy1, 4, 1
    spawn Fishy1, 5, 3
    spawn Beetank2, 6, 2
    spawn_end

EnemySpawn_0800e99c:
    spawn Billy, 4, 3
    spawn Mettaur2, 5, 1
    spawn Beetank2, 6, 2
    spawn_end
