global_label encounterGroupInternet

.word encounterList_0800e348
.word encounterList_0800e5c8
.word encounterList_0800e70c
.word encounterList_0800e9ac
.word encounterList_0800eafc
.word encounterList_0800ec44
.word encounterList_0800eed0
.word encounterList_0800f020
.word encounterList_0800f164
.word encounterList_0800f3d8
.word encounterList_0800f50c
.word encounterList_0800f780
.word encounterList_0800f9f8
.word encounterList_0800fb48
.word encounterList_0800fd80
.word encounterList_0800ffe4
.word encounterList_0800e48c
.word encounterList_0800e5c8
.word encounterList_0800e860
.word encounterList_0800e9ac
.word encounterList_0800eafc
.word encounterList_0800ed8c
.word encounterList_0800eed0
.word encounterList_0800f020
.word encounterList_0800f29c
.word encounterList_0800f3d8
.word encounterList_0800f648
.word encounterList_0800f8bc
.word encounterList_0800f9f8
.word encounterList_0800fc68
.word encounterList_0800feb4
.word encounterList_08010134

encounterList_0800e348: .include "data/encounter/Internet/0.inc"
encounterList_0800e48c: .include "data/encounter/Internet/1.inc"
encounterList_0800e5c8: .include "data/encounter/Internet/2.inc"
encounterList_0800e70c: .include "data/encounter/Internet/3.inc"
encounterList_0800e860: .include "data/encounter/Internet/4.inc"
encounterList_0800e9ac: .include "data/encounter/Internet/5.inc"
encounterList_0800eafc: .include "data/encounter/Internet/6.inc"
encounterList_0800ec44: .include "data/encounter/Internet/7.inc"
encounterList_0800ed8c: .include "data/encounter/Internet/8.inc"
encounterList_0800eed0: .include "data/encounter/Internet/9.inc"
encounterList_0800f020: .include "data/encounter/Internet/10.inc"
encounterList_0800f164: .include "data/encounter/Internet/11.inc"
encounterList_0800f29c: .include "data/encounter/Internet/12.inc"
encounterList_0800f3d8: .include "data/encounter/Internet/13.inc"
encounterList_0800f50c: .include "data/encounter/Internet/14.inc"
encounterList_0800f648: .include "data/encounter/Internet/15.inc"
encounterList_0800f780: .include "data/encounter/Internet/16.inc"
encounterList_0800f8bc: .include "data/encounter/Internet/17.inc"
encounterList_0800f9f8: .include "data/encounter/Internet/18.inc"
encounterList_0800fb48: .include "data/encounter/Internet/19.inc"
encounterList_0800fc68: .include "data/encounter/Internet/20.inc"
encounterList_0800fd80: .include "data/encounter/Internet/21.inc"
encounterList_0800feb4: .include "data/encounter/Internet/22.inc"
encounterList_0800ffe4: .include "data/encounter/Internet/23.inc"
encounterList_08010134: .include "data/encounter/Internet/24.inc"
