encounter 0x10, EnemySpawn_0800f800
encounter 0x10, EnemySpawn_0800f808
encounter 0x10, EnemySpawn_0800f814
encounter 0x10, EnemySpawn_0800f81c
encounter 0x10, EnemySpawn_0800f824
encounter 0x10, EnemySpawn_0800f82c
encounter 0x10, EnemySpawn_0800f838
encounter 0x10, EnemySpawn_0800f844
encounter 0x10, EnemySpawn_0800f850
encounter 0x10, EnemySpawn_0800f860
encounter 0x10, EnemySpawn_0800f86c
encounter 0x10, EnemySpawn_0800f878
encounter 0x10, EnemySpawn_0800f884
encounter 0x10, EnemySpawn_0800f894
encounter 0x10, EnemySpawn_0800f89c
encounter 0x10, EnemySpawn_0800f8ac

EnemySpawn_0800f800:
    spawn Gaia2, 6, 3
    spawn_end

EnemySpawn_0800f808:
    spawn Gaia2, 5, 1
    spawn Gaia2, 6, 3
    spawn_end

EnemySpawn_0800f814:
    spawn BigSnake1, 5, 2
    spawn_end

EnemySpawn_0800f81c:
    spawn BigSnake1, 5, 1
    spawn_end

EnemySpawn_0800f824:
    spawn BigSnake1, 4, 1
    spawn_end

EnemySpawn_0800f82c:
    spawn Poitton2, 4, 2
    spawn Poitton2, 6, 3
    spawn_end

EnemySpawn_0800f838:
    spawn Fanner2, 5, 3
    spawn Poitton2, 5, 1
    spawn_end

EnemySpawn_0800f844:
    spawn Fanner2, 4, 1
    spawn Fanner2, 6, 2
    spawn_end

EnemySpawn_0800f850:
    spawn Fanner2, 4, 3
    spawn Fanner2, 5, 1
    spawn Gaia2, 6, 2
    spawn_end

EnemySpawn_0800f860:
    spawn Fanner2, 5, 3
    spawn Miney3, 6, 1
    spawn_end

EnemySpawn_0800f86c:
    spawn Gaia2, 6, 3
    spawn Miney3, 6, 1
    spawn_end

EnemySpawn_0800f878:
    spawn Poitton2, 4, 3
    spawn Miney3, 6, 1
    spawn_end

EnemySpawn_0800f884:
    spawn Poitton2, 4, 1
    spawn Poitton2, 5, 3
    spawn Fanner2, 6, 2
    spawn_end

EnemySpawn_0800f894:
    spawn Gaia2, 5, 2
    spawn_end

EnemySpawn_0800f89c:
    spawn Fanner2, 4, 1
    spawn Fanner2, 5, 3
    spawn Fanner2, 6, 2
    spawn_end

EnemySpawn_0800f8ac:
    spawn Fanner2, 4, 3
    spawn Fanner2, 5, 1
    spawn Miney3, 6, 1
    spawn_end
