encounter 0x10, EnemySpawn_0800fa78
encounter 0x10, EnemySpawn_0800fa80
encounter 0x10, EnemySpawn_0800fa90
encounter 0x10, EnemySpawn_0800faa0
encounter 0x10, EnemySpawn_0800fab0
encounter 0x10, EnemySpawn_0800fabc
encounter 0x10, EnemySpawn_0800facc
encounter 0x10, EnemySpawn_0800fadc
encounter 0x10, EnemySpawn_0800fae4
encounter 0x10, EnemySpawn_0800faf0
encounter 0x10, EnemySpawn_0800fafc
encounter 0x10, EnemySpawn_0800fb08
encounter 0x10, EnemySpawn_0800fb18
encounter 0x10, EnemySpawn_0800fb24
encounter 0x10, EnemySpawn_0800fb30
encounter 0x10, EnemySpawn_0800fb3c

EnemySpawn_0800fa78:
    spawn Mole, 5, 2
    spawn_end

EnemySpawn_0800fa80:
    spawn Canodumb1, 4, 1
    spawn Canodumb2, 5, 2
    spawn Canodumb3, 6, 3
    spawn_end

EnemySpawn_0800fa90:
    spawn Mettaur3, 4, 3
    spawn Mettaur2, 5, 2
    spawn Mettaur1, 6, 1
    spawn_end

EnemySpawn_0800faa0:
    spawn Swordy3, 4, 1
    spawn Swordy2, 5, 2
    spawn Swordy1, 6, 3
    spawn_end

EnemySpawn_0800fab0:
    spawn ColdBear1, 4, 3
    spawn ColdBear1, 4, 1
    spawn_end

EnemySpawn_0800fabc:
    spawn Mettaur3, 4, 3
    spawn Mettaur3, 4, 2
    spawn Mettaur3, 4, 1
    spawn_end

EnemySpawn_0800facc:
    spawn Canodumb3, 5, 3
    spawn Canodumb3, 5, 1
    spawn Canodumb3, 6, 2
    spawn_end

EnemySpawn_0800fadc:
    spawn Swordy3, 4, 2
    spawn_end

EnemySpawn_0800fae4:
    spawn Swordy3, 5, 2
    spawn Spooky3, 6, 1
    spawn_end

EnemySpawn_0800faf0:
    spawn ColdBear1, 4, 1
    spawn Canodumb3, 6, 3
    spawn_end

EnemySpawn_0800fafc:
    spawn ColdBear1, 5, 1
    spawn Beetank3, 6, 2
    spawn_end

EnemySpawn_0800fb08:
    spawn ColdBear1, 4, 2
    spawn Canodumb3, 6, 3
    spawn Canodumb3, 6, 1
    spawn_end

EnemySpawn_0800fb18:
    spawn Beetank3, 5, 3
    spawn Spooky3, 6, 1
    spawn_end

EnemySpawn_0800fb24:
    spawn Swordy2, 5, 3
    spawn Swordy3, 5, 1
    spawn_end

EnemySpawn_0800fb30:
    spawn Beetank3, 5, 3
    spawn Beetank3, 6, 1
    spawn_end

EnemySpawn_0800fb3c:
    spawn Beetank3, 5, 1
    spawn Mettaur3, 6, 2
    spawn_end
