encounter 0x10, EnemySpawn_08010064
encounter 0x10, EnemySpawn_08010070
encounter 0x10, EnemySpawn_0801007c
encounter 0x10, EnemySpawn_08010088
encounter 0x10, EnemySpawn_08010094
encounter 0x10, EnemySpawn_080100a0
encounter 0x10, EnemySpawn_080100ac
encounter 0x10, EnemySpawn_080100bc
encounter 0x10, EnemySpawn_080100cc
encounter 0x10, EnemySpawn_080100dc
encounter 0x10, EnemySpawn_080100e8
encounter 0x10, EnemySpawn_080100f4
encounter 0x10, EnemySpawn_08010100
encounter 0x10, EnemySpawn_0801010c
encounter 0x10, EnemySpawn_08010118
encounter 0x10, EnemySpawn_08010124

EnemySpawn_08010064:
    spawn Satella3, 5, 1
    spawn Gaia3, 6, 2
    spawn_end

EnemySpawn_08010070:
    spawn Gaia3, 5, 3
    spawn Gaia3, 6, 1
    spawn_end

EnemySpawn_0801007c:
    spawn Ratty3, 5, 2
    spawn Ratty3, 6, 3
    spawn_end

EnemySpawn_08010088:
    spawn Ratty3, 5, 1
    spawn Gaia3, 6, 2
    spawn_end

EnemySpawn_08010094:
    spawn Ratty3, 4, 1
    spawn Satella3, 5, 3
    spawn_end

EnemySpawn_080100a0:
    spawn Ratty3, 5, 3
    spawn Ratty3, 5, 2
    spawn_end

EnemySpawn_080100ac:
    spawn Satella3, 5, 3
    spawn Ratty3, 5, 1
    spawn Gaia3, 6, 2
    spawn_end

EnemySpawn_080100bc:
    spawn Ratty3, 4, 3
    spawn Satella3, 5, 1
    spawn Fishy2, 6, 2
    spawn_end

EnemySpawn_080100cc:
    spawn MegalianW, 4, 2
    spawn MegalianA, 5, 1
    spawn MegalianH, 6, 3
    spawn_end

EnemySpawn_080100dc:
    spawn MegalianA, 4, 2
    spawn MegalianW, 5, 1
    spawn_end

EnemySpawn_080100e8:
    spawn MegalianW, 4, 3
    spawn MegalianH, 5, 1
    spawn_end

EnemySpawn_080100f4:
    spawn Fishy2, 4, 2
    spawn MegalianW, 6, 3
    spawn_end

EnemySpawn_08010100:
    spawn Ratty3, 5, 1
    spawn Satella3, 6, 2
    spawn_end

EnemySpawn_0801010c:
    spawn MegalianH, 4, 2
    spawn Satella3, 5, 1
    spawn_end

EnemySpawn_08010118:
    spawn MegalianW, 4, 3
    spawn Gaia3, 5, 1
    spawn_end

EnemySpawn_08010124:
    spawn Fishy2, 4, 1
    spawn Satella3, 5, 2
    spawn Fishy2, 6, 3
    spawn_end
