encounter 0x10, EnemySpawn_0800fe00
encounter 0x10, EnemySpawn_0800fe08
encounter 0x10, EnemySpawn_0800fe10
encounter 0x10, EnemySpawn_0800fe1c
encounter 0x10, EnemySpawn_0800fe28
encounter 0x10, EnemySpawn_0800fe34
encounter 0x10, EnemySpawn_0800fe40
encounter 0x10, EnemySpawn_0800fe4c
encounter 0x10, EnemySpawn_0800fe58
encounter 0x10, EnemySpawn_0800fe68
encounter 0x10, EnemySpawn_0800fe74
encounter 0x10, EnemySpawn_0800fe80
encounter 0x10, EnemySpawn_0800fe8c
encounter 0x10, EnemySpawn_0800fe98
encounter 0x10, EnemySpawn_0800fea4
encounter 0x10, EnemySpawn_0800feac

EnemySpawn_0800fe00:
    spawn Popper2, 6, 1
    spawn_end

EnemySpawn_0800fe08:
    spawn Popper3, 6, 3
    spawn_end

EnemySpawn_0800fe10:
    spawn Popper2, 5, 1
    spawn Popper3, 6, 3
    spawn_end

EnemySpawn_0800fe1c:
    spawn Fanner3, 5, 1
    spawn Fanner3, 5, 3
    spawn_end

EnemySpawn_0800fe28:
    spawn CanDevil2, 4, 2
    spawn Fanner3, 4, 1
    spawn_end

EnemySpawn_0800fe34:
    spawn Mosqurito3, 4, 1
    spawn Mosqurito3, 5, 2
    spawn_end

EnemySpawn_0800fe40:
    spawn Mosqurito3, 4, 2
    spawn CanDevil2, 5, 2
    spawn_end

EnemySpawn_0800fe4c:
    spawn CanDevil2, 4, 1
    spawn CanDevil2, 5, 2
    spawn_end

EnemySpawn_0800fe58:
    spawn Fanner3, 5, 3
    spawn Fanner3, 5, 2
    spawn Fanner3, 6, 1
    spawn_end

EnemySpawn_0800fe68:
    spawn Popper2, 4, 1
    spawn Fanner3, 5, 3
    spawn_end

EnemySpawn_0800fe74:
    spawn MegalianH, 4, 3
    spawn Popper3, 6, 1
    spawn_end

EnemySpawn_0800fe80:
    spawn MegalianH, 4, 2
    spawn MegalianH, 6, 3
    spawn_end

EnemySpawn_0800fe8c:
    spawn CanDevil2, 4, 3
    spawn MegalianH, 5, 1
    spawn_end

EnemySpawn_0800fe98:
    spawn Fanner3, 4, 3
    spawn MegalianH, 4, 1
    spawn_end

EnemySpawn_0800fea4:
    spawn MegalianH, 5, 2
    spawn_end

EnemySpawn_0800feac:
    spawn Mole, 5, 2
    spawn_end
