#include "offsets.h"
    .include "constants.inc"
    .include "macros.inc"


global_label BgTask_804F728
    task_tileset 0, 0x8790AB4, 0x6000020, 0x10, 23, 240
    task_tileset_arg TilemapEntry_804EE78_0
    task_tileset_arg TilemapEntry_804EE78_1, 8
    task_tileset_arg TilemapEntry_804EE78_2, 8
    task_tileset_arg TilemapEntry_804EE78_3, 8
    task_tileset_arg TilemapEntry_804EE78_0, 8
    task_tileset_arg TilemapEntry_804EE78_1, 8
    task_tileset_arg TilemapEntry_804EE78_2, 8
    task_tileset_arg TilemapEntry_804EE78_3, 8
    task_tileset_arg TilemapEntry_804EE78_0, 120
    task_tileset_arg TilemapEntry_804EE78_1, 4
    task_tileset_arg TilemapEntry_804EE78_2, 4
    task_tileset_arg TilemapEntry_804EE78_3, 4
    task_tileset_arg TilemapEntry_804EE78_0, 4
    task_tileset_arg TilemapEntry_804EE78_1, 4
    task_tileset_arg TilemapEntry_804EE78_2, 4
    task_tileset_arg TilemapEntry_804EE78_3, 4
    task_repeat

global_label BgTask_804F7B8
    task_tileset 0, 0x87912B4, 0x6000020, 0x10, 24, 240
    task_tileset_arg TilemapEntry_804EE78_0
    task_tileset_arg TilemapEntry_804EE78_1, 8
    task_tileset_arg TilemapEntry_804EE78_2, 8
    task_tileset_arg TilemapEntry_804EE78_3
    task_tileset_arg TilemapEntry_804EE78_2, 8
    task_tileset_arg TilemapEntry_804EE78_1, 8
    task_repeat

