#include "offsets.h"
    .include "constants.inc"
    .include "macros.inc"

global_label BgTask_805033C
    task_tileset 0, 0x8790AB4, 0x6000020, 0x10, 27, 240
    task_tileset_arg TilemapEntry_804EE78_0
    task_tileset_arg TilemapEntry_804EE78_1, 8
    task_tileset_arg TilemapEntry_804EE78_2, 8
    task_tileset_arg TilemapEntry_804EE78_3, 8
    task_tileset_arg TilemapEntry_804EE78_0, 8
    task_tileset_arg TilemapEntry_804EE78_1, 8
    task_tileset_arg TilemapEntry_804EE78_2, 8
    task_tileset_arg TilemapEntry_804EE78_3, 8
    task_tileset_arg TilemapEntry_804EE78_0, 120
    task_tileset_arg TilemapEntry_804EE78_1, 8
    task_tileset_arg TilemapEntry_804EE78_2, 8
    task_tileset_arg TilemapEntry_804EE78_3, 8
    task_tileset_arg TilemapEntry_804EE78_0, 8
    task_tileset_arg TilemapEntry_804EE78_1, 8
    task_tileset_arg TilemapEntry_804EE78_2, 8
    task_tileset_arg TilemapEntry_804EE78_3, 8
    task_repeat

