#include <stddef.h>
#include "mmbn.h"

#define DECLARE(SYM,VAL) __asm("__AS_DEFINE__ " SYM "\t%0" : : "n" ((unsigned long)(VAL)))

int main(void)
{
    // Main
    DECLARE("Main_manager"                  , offsetof(struct Main, manager));
    DECLARE("Main_input"                    , offsetof(struct Main, input));
    DECLARE("Main_game"                     , offsetof(struct Main, game));
    DECLARE("Main_unk_0C"                   , offsetof(struct Main, unk_0C));
    DECLARE("Main_displaySettings"          , offsetof(struct Main, displaySettings));
    DECLARE("Main_unk_14"                   , offsetof(struct Main, unk_14));
    DECLARE("Main_fadeSettings"             , offsetof(struct Main, fadeSettings));
    DECLARE("Main_unk_1C"                   , offsetof(struct Main, unk_1C));
    DECLARE("Main_unk_20"                   , offsetof(struct Main, unk_20));
    DECLARE("Main_unk_24"                   , offsetof(struct Main, unk_24));
    DECLARE("Main_unk_28"                   , offsetof(struct Main, unk_28));
    DECLARE("Main_unk_2C"                   , offsetof(struct Main, unk_2C));
    DECLARE("Main_unk_30"                   , offsetof(struct Main, unk_30));
    DECLARE("Main_mainMenu"                 , offsetof(struct Main, mainMenu));
    DECLARE("Main_windowSettings"           , offsetof(struct Main, windowSettings));
    DECLARE("Main_blendSettings"            , offsetof(struct Main, blendSettings));
    DECLARE("Main_demo"                     , offsetof(struct Main, demo));
    DECLARE("Main_unk_44"                   , offsetof(struct Main, unk_44));
    DECLARE("Main_text"                     , offsetof(struct Main, text));
    DECLARE("Main_unk_4C"                   , offsetof(struct Main, unk_4C));
    DECLARE("Main_unk_50"                   , offsetof(struct Main, unk_50));
    DECLARE("Main_unk_54"                   , offsetof(struct Main, unk_54));
    DECLARE("Main_unk_58"                   , offsetof(struct Main, unk_58));
    DECLARE("Main_screens"                  , offsetof(struct Main, screens));
    DECLARE("Main_unk_60"                   , offsetof(struct Main, unk_60));
    DECLARE("Main_unk_64"                   , offsetof(struct Main, unk_64));
    DECLARE("Main_unk_68"                   , offsetof(struct Main, unk_68));
    DECLARE("Main_unk_6C"                   , offsetof(struct Main, unk_6C));
    DECLARE("Main_shop"                     , offsetof(struct Main, shop));
    DECLARE("Main_unk_74"                   , offsetof(struct Main, unk_74));
    DECLARE("Main_unk_78"                   , offsetof(struct Main, unk_78));
    DECLARE("Main_unk_7C"                   , offsetof(struct Main, unk_7C));

    // Input
    DECLARE("Input_curKeyState"      , offsetof(Input, curKeyState));
    DECLARE("Input_toggleKeyState"   , offsetof(Input, toggleKeyState));
    DECLARE("Input_heldKeyState"     , offsetof(Input, heldKeyState));
    DECLARE("Input_lastKeyState"     , offsetof(Input, lastKeyState));
    DECLARE("Input_framesHeldA"      , offsetof(Input, framesHeldA));
    DECLARE("Input_framesHeldB"      , offsetof(Input, framesHeldB));
    DECLARE("Input_framesHeldSelect" , offsetof(Input, framesHeldSelect));
    DECLARE("Input_framesHeldStart"  , offsetof(Input, framesHeldStart));
    DECLARE("Input_framesHeldRight"  , offsetof(Input, framesHeldRight));
    DECLARE("Input_framesHeldLeft"   , offsetof(Input, framesHeldLeft));
    DECLARE("Input_framesHeldUp"     , offsetof(Input, framesHeldUp));
    DECLARE("Input_framesHeldDown"   , offsetof(Input, framesHeldDown));
    DECLARE("Input_framesHeldR"      , offsetof(Input, framesHeldR));
    DECLARE("Input_framesHeldL"      , offsetof(Input, framesHeldL));
    DECLARE("Input_unused"           , offsetof(Input, unused));
    DECLARE("Input_frameCounter"     , offsetof(Input, frameCounter));
    
    // Manager
    DECLARE("Manager_m_state0"              , offsetof(struct Manager, m_state0));
    DECLARE("Manager_m_softResetDelayTimer" , offsetof(struct Manager, m_softResetDelayTimer));

    // FadeSettings
    DECLARE("FadeSettings_m_isApplyFadeFunc", offsetof(struct FadeSettings, m_isApplyFadeFunc));
    DECLARE("FadeSettings_m_fadeType"       , offsetof(struct FadeSettings, m_fadeType));
    DECLARE("FadeSettings_m_fadeStep"       , offsetof(struct FadeSettings, m_fadeStep));
    DECLARE("FadeSettings_m_isFadeActive"   , offsetof(struct FadeSettings, m_isFadeActive));
    DECLARE("FadeSettings_m_isFadeStarted"  , offsetof(struct FadeSettings, m_isFadeStarted));

    // BlendSettings
    DECLARE("BlendSettings_m_bldCnt_Target1", offsetof(struct BlendSettings, m_bldCnt_Target1));
    DECLARE("BlendSettings_m_bldAlpha_EVA"  , offsetof(struct BlendSettings, m_bldAlpha_EVA));
    DECLARE("BlendSettings_m_blendControl"  , offsetof(struct BlendSettings, m_blendControl));

    // DisplaySettings
    DECLARE("DisplaySettings_dispcnt"       , offsetof(struct DisplaySettings, dispcnt));
    DECLARE("DisplaySettings_bg0Cnt"        , offsetof(struct DisplaySettings, bg0Cnt));
    DECLARE("DisplaySettings_bg1Cnt"        , offsetof(struct DisplaySettings, bg1Cnt));
    DECLARE("DisplaySettings_bg2Cnt"        , offsetof(struct DisplaySettings, bg2Cnt));
    DECLARE("DisplaySettings_bg3Cnt"        , offsetof(struct DisplaySettings, bg3Cnt));
    DECLARE("DisplaySettings_bg0Hofs"       , offsetof(struct DisplaySettings, bg0Hofs));
    DECLARE("DisplaySettings_bg0Vofs"       , offsetof(struct DisplaySettings, bg0Vofs));
    DECLARE("DisplaySettings_bg1Hofs"       , offsetof(struct DisplaySettings, bg1Hofs));
    DECLARE("DisplaySettings_bg1Vofs"       , offsetof(struct DisplaySettings, bg1Vofs));
    DECLARE("DisplaySettings_bg2Hofs"       , offsetof(struct DisplaySettings, bg2Hofs));
    DECLARE("DisplaySettings_bg2Vofs"       , offsetof(struct DisplaySettings, bg2Vofs));
    DECLARE("DisplaySettings_bg3Hofs"       , offsetof(struct DisplaySettings, bg3Hofs));
    DECLARE("DisplaySettings_bg3Vofs"       , offsetof(struct DisplaySettings, bg3Vofs));

    // GameState
    DECLARE("GameState_m_state0"                  , offsetof(GameState, m_state0));
    DECLARE("GameState_b1"                        , offsetof(GameState, b1));
    DECLARE("GameState_b2"                        , offsetof(GameState, b2));
    DECLARE("GameState_b3"                        , offsetof(GameState, b3));
    DECLARE("GameState_m_currentArea"             , offsetof(GameState, m_currentArea));
    DECLARE("GameState_m_currentSubArea"          , offsetof(GameState, m_currentSubArea));
    DECLARE("GameState_m_storyFlag"               , offsetof(GameState, m_storyFlag));
    DECLARE("GameState_m_b7_fadeType"             , offsetof(GameState, m_b7_fadeType));
    DECLARE("GameState_b8"                        , offsetof(GameState, b8));
    DECLARE("GameState_m_Battle_IsTimePaused"     , offsetof(GameState, m_Battle_IsTimePaused));
    DECLARE("GameState_m_b10"                     , offsetof(GameState, m_b10));
    DECLARE("GameState_m_b11_backgroundId"        , offsetof(GameState, m_b11_backgroundId));
    DECLARE("GameState_m_bx11"                    , offsetof(GameState, m_bx11));
    DECLARE("GameState_m_bx12"                    , offsetof(GameState, m_bx12));
    DECLARE("GameState_m_b14"                     , offsetof(GameState, m_b14));
    DECLARE("GameState_m_battleType"              , offsetof(GameState, m_battleType));
    DECLARE("GameState_m_b16_state"               , offsetof(GameState, m_b16_state));
    DECLARE("GameState_m_isShuffleFolder"         , offsetof(GameState, m_isShuffleFolder));
    DECLARE("GameState_m_b18_commentaryTextIndex" , offsetof(GameState, m_b18_commentaryTextIndex));
    DECLARE("GameState_m_b19_fadeStep"            , offsetof(GameState, m_b19_fadeStep));
    DECLARE("GameState_m_statAttack"              , offsetof(GameState, m_statAttack));
    DECLARE("GameState_m_statSpeed"               , offsetof(GameState, m_statSpeed));
    DECLARE("GameState_m_statCharge"              , offsetof(GameState, m_statCharge));
    DECLARE("GameState_m_armor"                   , offsetof(GameState, m_armor));
    DECLARE("GameState_m_Song_CurrentSongId"      , offsetof(GameState, m_Song_CurrentSongId));
    DECLARE("GameState_m_bustingRank"             , offsetof(GameState, m_bustingRank));
    DECLARE("GameState_m_b26"                     , offsetof(GameState, m_b26));
    DECLARE("GameState_m_b27"                     , offsetof(GameState, m_b27));
    DECLARE("GameState_m_u0_hp0"                  , offsetof(GameState, m_u0_hp0));
    DECLARE("GameState_m_u1_hp1"                  , offsetof(GameState, m_u1_hp1));
    DECLARE("GameState_ix0"                       , offsetof(GameState, ix0));
    DECLARE("GameState_m_ix1"                     , offsetof(GameState, m_ix1));
    DECLARE("GameState_m_i0"                      , offsetof(GameState, m_i0));
    DECLARE("GameState_m_enemyList"               , offsetof(GameState, m_enemyList));
    DECLARE("GameState_m_chipFolder"              , offsetof(GameState, m_chipFolder));
    DECLARE("GameState_m_battleInitHideObject"    , offsetof(GameState, m_battleInitHideObject));
    DECLARE("GameState_m_ix7_savedPosY"           , offsetof(GameState, m_ix7_savedPosY));
    DECLARE("GameState_m_ix8_savedPosX"           , offsetof(GameState, m_ix8_savedPosX));
    DECLARE("GameState_m_ix9_savedPos0"           , offsetof(GameState, m_ix9_savedPos0));
    DECLARE("GameState_m_ix10_savedDirection"     , offsetof(GameState, m_ix10_savedDirection));
    DECLARE("GameState_ix11"                      , offsetof(GameState, ix11));
    DECLARE("GameState_ix12"                      , offsetof(GameState, ix12));
    DECLARE("GameState_ix13"                      , offsetof(GameState, ix13));
    DECLARE("GameState_ix14"                      , offsetof(GameState, ix14));
    DECLARE("GameState_ix15"                      , offsetof(GameState, ix15));
    DECLARE("GameState_ix16"                      , offsetof(GameState, ix16));
    DECLARE("GameState_ix17"                      , offsetof(GameState, ix17));
    DECLARE("GameState_ix18"                      , offsetof(GameState, ix18));
    DECLARE("GameState_ix19"                      , offsetof(GameState, ix19));
    DECLARE("GameState_ix20"                      , offsetof(GameState, ix20));
    DECLARE("GameState_ix21"                      , offsetof(GameState, ix21));
    DECLARE("GameState_m_zenny"                   , offsetof(GameState, m_zenny));

    // Struct_Unk0C
    DECLARE("Struct_Unk0C_m_state0"                             , offsetof(Struct_Unk0C, m_state0));
    DECLARE("Struct_Unk0C_m_state1"                             , offsetof(Struct_Unk0C, m_state1));
    DECLARE("Struct_Unk0C_m_state2"                             , offsetof(Struct_Unk0C, m_state2));
    DECLARE("Struct_Unk0C_sx0"                                  , offsetof(Struct_Unk0C, sx0));
    DECLARE("Struct_Unk0C_b4"                                   , offsetof(Struct_Unk0C, b4));
    DECLARE("Struct_Unk0C_counter0"                             , offsetof(Struct_Unk0C, counter0));
    DECLARE("Struct_Unk0C_b6"                                   , offsetof(Struct_Unk0C, b6));
    DECLARE("Struct_Unk0C_b7"                                   , offsetof(Struct_Unk0C, b7));
    DECLARE("Struct_Unk0C_m_b8"                                 , offsetof(Struct_Unk0C, m_b8));
    DECLARE("Struct_Unk0C_m_bitField2"                          , offsetof(Struct_Unk0C, m_bitField2));
    DECLARE("Struct_Unk0C_m_b10"                                , offsetof(Struct_Unk0C, m_b10));
    DECLARE("Struct_Unk0C_m_b11_encounterEnemyCount"            , offsetof(Struct_Unk0C, m_b11_encounterEnemyCount));
    DECLARE("Struct_Unk0C_m_b12"                                , offsetof(Struct_Unk0C, m_b12));
    DECLARE("Struct_Unk0C_m_b13"                                , offsetof(Struct_Unk0C, m_b13));
    DECLARE("Struct_Unk0C_m_b14"                                , offsetof(Struct_Unk0C, m_b14));
    DECLARE("Struct_Unk0C_m_b15_backgroundId"                   , offsetof(Struct_Unk0C, m_b15_backgroundId));
    DECLARE("Struct_Unk0C_m_b16"                                , offsetof(Struct_Unk0C, m_b16));
    DECLARE("Struct_Unk0C_b17"                                  , offsetof(Struct_Unk0C, b17));
    DECLARE("Struct_Unk0C_m_customGaugeSpeed"                   , offsetof(Struct_Unk0C, m_customGaugeSpeed));
    DECLARE("Struct_Unk0C_m_b19"                                , offsetof(Struct_Unk0C, m_b19));
    DECLARE("Struct_Unk0C_m_b20"                                , offsetof(Struct_Unk0C, m_b20));
    DECLARE("Struct_Unk0C_b21"                                  , offsetof(Struct_Unk0C, b21));
    DECLARE("Struct_Unk0C_b22"                                  , offsetof(Struct_Unk0C, b22));
    DECLARE("Struct_Unk0C_m_multipleDeletionCount"              , offsetof(Struct_Unk0C, m_multipleDeletionCount));
    DECLARE("Struct_Unk0C_m_b24"                                , offsetof(Struct_Unk0C, m_b24));
    DECLARE("Struct_Unk0C_m_srcBattleHandCount"                 , offsetof(Struct_Unk0C, m_srcBattleHandCount));
    DECLARE("Struct_Unk0C_m_sioOtherMpId"                       , offsetof(Struct_Unk0C, m_sioOtherMpId));
    DECLARE("Struct_Unk0C_m_sioMultiplayerId"                   , offsetof(Struct_Unk0C, m_sioMultiplayerId));
    DECLARE("Struct_Unk0C_r0"                                   , offsetof(Struct_Unk0C, r0));
    DECLARE("Struct_Unk0C_r1"                                   , offsetof(Struct_Unk0C, r1));
    DECLARE("Struct_Unk0C_r2"                                   , offsetof(Struct_Unk0C, r2));
    DECLARE("Struct_Unk0C_m_r3"                                 , offsetof(Struct_Unk0C, m_r3));
    DECLARE("Struct_Unk0C_m_possibleBattleTime"                 , offsetof(Struct_Unk0C, m_possibleBattleTime));
    DECLARE("Struct_Unk0C_i0"                                   , offsetof(Struct_Unk0C, i0));
    DECLARE("Struct_Unk0C_i1"                                   , offsetof(Struct_Unk0C, i1));
    DECLARE("Struct_Unk0C_i2"                                   , offsetof(Struct_Unk0C, i2));
    DECLARE("Struct_Unk0C_u1"                                   , offsetof(Struct_Unk0C, u1));
    DECLARE("Struct_Unk0C_m_u2"                                 , offsetof(Struct_Unk0C, m_u2));
    DECLARE("Struct_Unk0C_i5"                                   , offsetof(Struct_Unk0C, i5));
    DECLARE("Struct_Unk0C_i6"                                   , offsetof(Struct_Unk0C, i6));
    DECLARE("Struct_Unk0C_i7"                                   , offsetof(Struct_Unk0C, i7));
    DECLARE("Struct_Unk0C_uu0"                                  , offsetof(Struct_Unk0C, uu0));
    DECLARE("Struct_Unk0C_m_customGaugeMeter"                   , offsetof(Struct_Unk0C, m_customGaugeMeter));
    DECLARE("Struct_Unk0C_m_i9"                                 , offsetof(Struct_Unk0C, m_i9));
    DECLARE("Struct_Unk0C_q0"                                   , offsetof(Struct_Unk0C, q0));
    DECLARE("Struct_Unk0C_m_possibleEncounterEnemyFieldDetail"  , offsetof(Struct_Unk0C, m_possibleEncounterEnemyFieldDetail));
    DECLARE("Struct_Unk0C_m_possibleEncounterEnemyIdList"       , offsetof(Struct_Unk0C, m_possibleEncounterEnemyIdList));
    DECLARE("Struct_Unk0C_u0"                                   , offsetof(Struct_Unk0C, u0));
    DECLARE("Struct_Unk0C_m_bitField00"                         , offsetof(Struct_Unk0C, m_bitField00));
    DECLARE("Struct_Unk0C_m_bitField0"                          , offsetof(Struct_Unk0C, m_bitField0));
    DECLARE("Struct_Unk0C_m_enemyList"                          , offsetof(Struct_Unk0C, m_enemyList));
    DECLARE("Struct_Unk0C_m_srcBattleHandIndexList"             , offsetof(Struct_Unk0C, m_srcBattleHandIndexList));
    DECLARE("Struct_Unk0C_m_srcBattleHandCodeList"              , offsetof(Struct_Unk0C, m_srcBattleHandCodeList));

    // Struct_Unk20
    DECLARE("Struct_Unk20_b0"                       , offsetof(Struct_Unk20, b0));
    DECLARE("Struct_Unk20_m_battleHandCount"        , offsetof(Struct_Unk20, m_battleHandCount));
    DECLARE("Struct_Unk20_m_moveCount"              , offsetof(Struct_Unk20, m_moveCount));
    DECLARE("Struct_Unk20_m_hitsTaken"              , offsetof(Struct_Unk20, m_hitsTaken));
    DECLARE("Struct_Unk20_b1"                       , offsetof(Struct_Unk20, b1));
    DECLARE("Struct_Unk20_b2"                       , offsetof(Struct_Unk20, b2));
    DECLARE("Struct_Unk20_u0"                       , offsetof(Struct_Unk20, u0));
    DECLARE("Struct_Unk20_b3"                       , offsetof(Struct_Unk20, b3));
    DECLARE("Struct_Unk20_m_b4_atk"                 , offsetof(Struct_Unk20, m_b4_atk));
    DECLARE("Struct_Unk20_m_b5_spd"                 , offsetof(Struct_Unk20, m_b5_spd));
    DECLARE("Struct_Unk20_m_b6_chg"                 , offsetof(Struct_Unk20, m_b6_chg));
    DECLARE("Struct_Unk20_b7"                       , offsetof(Struct_Unk20, b7));
    DECLARE("Struct_Unk20_b8"                       , offsetof(Struct_Unk20, b8));
    DECLARE("Struct_Unk20_b9"                       , offsetof(Struct_Unk20, b9));
    DECLARE("Struct_Unk20_m_b10_armor"              , offsetof(Struct_Unk20, m_b10_armor));
    DECLARE("Struct_Unk20_b11"                      , offsetof(Struct_Unk20, b11));
    DECLARE("Struct_Unk20_b12"                      , offsetof(Struct_Unk20, b12));
    DECLARE("Struct_Unk20_padd0"                    , offsetof(Struct_Unk20, padd0));
    DECLARE("Struct_Unk20_m_curKeyState"            , offsetof(Struct_Unk20, m_curKeyState));
    DECLARE("Struct_Unk20_m_toggleKeyState"         , offsetof(Struct_Unk20, m_toggleKeyState));
    DECLARE("Struct_Unk20_s4"                       , offsetof(Struct_Unk20, s4));
    DECLARE("Struct_Unk20_m_lastKeyState"           , offsetof(Struct_Unk20, m_lastKeyState));
    DECLARE("Struct_Unk20_m_u2_hp0"                 , offsetof(Struct_Unk20, m_u2_hp0));
    DECLARE("Struct_Unk20_m_u3_hp1"                 , offsetof(Struct_Unk20, m_u3_hp1));
    DECLARE("Struct_Unk20_padx1"                    , offsetof(Struct_Unk20, padx1));
    DECLARE("Struct_Unk20_m_battleHandIndexList"    , offsetof(Struct_Unk20, m_battleHandIndexList));
    DECLARE("Struct_Unk20_pad0"                     , offsetof(Struct_Unk20, pad0));
    DECLARE("Struct_Unk20_s5"                       , offsetof(Struct_Unk20, s5));
    DECLARE("Struct_Unk20_s6"                       , offsetof(Struct_Unk20, s6));
    DECLARE("Struct_Unk20_s7"                       , offsetof(Struct_Unk20, s7));
    DECLARE("Struct_Unk20_s8"                       , offsetof(Struct_Unk20, s8));

    // Text
    DECLARE("Text_m_isWriteText"                   , offsetof(Text, m_isWriteText));
    DECLARE("Text_m_textBlockIndex"                , offsetof(Text, m_textBlockIndex));
    DECLARE("Text_m_textBufferOffset"              , offsetof(Text, m_textBufferOffset));
    DECLARE("Text_m_scriptOptions"                 , offsetof(Text, m_scriptOptions));
    DECLARE("Text_m_dialogDelayType"               , offsetof(Text, m_dialogDelayType));
    DECLARE("Text_m_isScriptJump"                  , offsetof(Text, m_isScriptJump));
    DECLARE("Text_m_counter1"                      , offsetof(Text, m_counter1));
    DECLARE("Text_m_portraitPalIndex"              , offsetof(Text, m_portraitPalIndex));
    DECLARE("Text_m_nextDelay"                     , offsetof(Text, m_nextDelay));
    DECLARE("Text_m_commandParseDelay"             , offsetof(Text, m_commandParseDelay));
    DECLARE("Text_m_nextAnimationIndex"            , offsetof(Text, m_nextAnimationIndex));
    DECLARE("Text_m_currAnimationIndex"            , offsetof(Text, m_currAnimationIndex));
    DECLARE("Text_m_dialogDelayCounter"            , offsetof(Text, m_dialogDelayCounter));
    DECLARE("Text_m_textCol"                       , offsetof(Text, m_textCol));
    DECLARE("Text_m_textRow"                       , offsetof(Text, m_textRow));
    DECLARE("Text_m_layoutLineOffset"              , offsetof(Text, m_layoutLineOffset));
    DECLARE("Text_m_scriptParseDelay"              , offsetof(Text, m_scriptParseDelay));
    DECLARE("Text_m_dialogSkipDelay"               , offsetof(Text, m_dialogSkipDelay));
    DECLARE("Text_m_charShade"                     , offsetof(Text, m_charShade));
    DECLARE("Text_m_b14"                           , offsetof(Text, m_b14));
    DECLARE("Text_m_b15_optionFlag"                , offsetof(Text, m_b15_optionFlag));
    DECLARE("Text_m_b16"                           , offsetof(Text, m_b16));
    DECLARE("Text_m_b17"                           , offsetof(Text, m_b17));
    DECLARE("Text_m_curKeyState"                   , offsetof(Text, m_curKeyState));
    DECLARE("Text_m_heldKeyState"                  , offsetof(Text, m_heldKeyState));
    DECLARE("Text_m_toggleKeyState"                , offsetof(Text, m_toggleKeyState));
    DECLARE("Text_m_dialogArrowAnimCycle"          , offsetof(Text, m_dialogArrowAnimCycle));
    DECLARE("Text_m_arrowAnimFrame"                , offsetof(Text, m_arrowAnimFrame));
    DECLARE("Text_m_commandTextPointer"            , offsetof(Text, m_commandTextPointer));
    DECLARE("Text_m_textBlockPointer"              , offsetof(Text, m_textBlockPointer));
    DECLARE("Text_m_layoutTextPointer"             , offsetof(Text, m_layoutTextPointer));
    DECLARE("Text_m_dialogLayout"                  , offsetof(Text, m_dialogLayout));
    DECLARE("Text_m_itemIdList"                    , offsetof(Text, m_itemIdList));
    DECLARE("Text_m_textPointerAfterKeyPrint"      , offsetof(Text, m_textPointerAfterKeyPrint));
    DECLARE("Text_m_otherTextPointerAfterKeyPrint" , offsetof(Text, m_otherTextPointerAfterKeyPrint));
    DECLARE("Text_m_possibleBcdBuffer"             , offsetof(Text, m_possibleBcdBuffer));
    DECLARE("Text_m_b18"                           , offsetof(Text, m_b18));
    DECLARE("Text_b19"                             , offsetof(Text, b19));
    DECLARE("Text_b20"                             , offsetof(Text, b20));
    DECLARE("Text_b21"                             , offsetof(Text, b21));
    DECLARE("Text_m_textBufIndex"                  , offsetof(Text, m_textBufIndex));
    DECLARE("Text_m_otherTempTextBufIndex"         , offsetof(Text, m_otherTempTextBufIndex));
    DECLARE("Text_m_portrait"                      , offsetof(Text, m_portrait));

    //
    DECLARE("OamAttributeListNode_m_xyDetails"     , offsetof(OamAttributeListNode, m_xyDetails));
    DECLARE("OamAttributeListNode_m_tileDetail"    , offsetof(OamAttributeListNode, m_tileDetail));
    DECLARE("OamAttributeListNode_m_unused"        , offsetof(OamAttributeListNode, m_unused));
    DECLARE("OamAttributeListNode_m_nextIndex"     , offsetof(OamAttributeListNode, m_nextIndex));

    // Sprite
    DECLARE("Sprite_m_indexFrame"          , offsetof(Sprite, m_indexFrame));
    DECLARE("Sprite_m_indexSubFrame"       , offsetof(Sprite, m_indexSubFrame));
    DECLARE("Sprite_m_frameDelay"          , offsetof(Sprite, m_frameDelay));
    DECLARE("Sprite_m_frameFlags"          , offsetof(Sprite, m_frameFlags));
    DECLARE("Sprite_m_spriteFlags"         , offsetof(Sprite, m_spriteFlags));
    DECLARE("Sprite_m_srcPalIndex"         , offsetof(Sprite, m_srcPalIndex));
    DECLARE("Sprite_m_palIndexSubFrame"    , offsetof(Sprite, m_palIndexSubFrame));
    DECLARE("Sprite_m_indexOamList"        , offsetof(Sprite, m_indexOamList));
    DECLARE("Sprite_m_dstTileOffset"       , offsetof(Sprite, m_dstTileOffset));
    DECLARE("Sprite_m_u0"                  , offsetof(Sprite, m_u0));
    DECLARE("Sprite_m_posX"                , offsetof(Sprite, m_posX));
    DECLARE("Sprite_m_b7_lineOffRelated"   , offsetof(Sprite, m_b7_lineOffRelated));
    DECLARE("Sprite_m_u2"                  , offsetof(Sprite, m_u2));
    DECLARE("Sprite_m_u3_affineRelated_Lo" , offsetof(Sprite, m_u3_affineRelated_Lo));
    DECLARE("Sprite_m_u3_affineRelated_Hi" , offsetof(Sprite, m_u3_affineRelated_Hi));
    DECLARE("Sprite_m_tileAttributes"      , offsetof(Sprite, m_tileAttributes));
    DECLARE("Sprite__pad"                  , offsetof(Sprite, _pad));
    DECLARE("Sprite_m_spriteStart"         , offsetof(Sprite, m_spriteStart));
    DECLARE("Sprite_m_curFrame"            , offsetof(Sprite, m_curFrame));
    DECLARE("Sprite_m_curSubFrame"         , offsetof(Sprite, m_curSubFrame));
    DECLARE("Sprite_m_curTilesetHeader"    , offsetof(Sprite, m_curTilesetHeader));
    DECLARE("Sprite_m_i0"                  , offsetof(Sprite, m_i0));
    DECLARE("Sprite_m_b11"                 , offsetof(Sprite, m_b11));

    // SpriteLzDetails
    DECLARE("SpriteLzDetails_m_spriteCount"     , offsetof(struct SpriteLzDetails, m_spriteCount));
    DECLARE("SpriteLzDetails_m_indexList"       , offsetof(struct SpriteLzDetails, m_indexList));
    DECLARE("SpriteLzDetails_m_spritePtrList"   , offsetof(struct SpriteLzDetails, m_spritePtrList));
    DECLARE("SpriteLzDetails_m_next"            , offsetof(struct SpriteLzDetails, m_next));

    // EnemyDetail
    DECLARE("EnemyDetail_m_hp"                  , offsetof(struct EnemyDetail, m_hp));
    DECLARE("EnemyDetail_m_element"             , offsetof(struct EnemyDetail, m_element));
    DECLARE("EnemyDetail_m_lzSpriteIndex"       , offsetof(struct EnemyDetail, m_lzSpriteIndex));
    DECLARE("EnemyDetail_m_possibleVirusFamily" , offsetof(struct EnemyDetail, m_possibleVirusFamily));
    DECLARE("EnemyDetail_m_dropTable"           , offsetof(struct EnemyDetail, m_dropTable));

    // EnemySpawn
    DECLARE("EnemySpawn_m_id"                   , offsetof(struct EnemySpawn, m_id));
    DECLARE("EnemySpawn_m_x"                    , offsetof(struct EnemySpawn, m_x));
    DECLARE("EnemySpawn_m_y"                    , offsetof(struct EnemySpawn, m_y));

    // BattleType
    DECLARE("BattleType_0_Regular"          , 0);
    DECLARE("BattleType_1_Tutorial1"        , 1);
    DECLARE("BattleType_2_Tutorial2"        , 2);
    DECLARE("BattleType_3_RegularNoResult"  , 3);
    DECLARE("BattleType_4_Tutorial3"        , 4);
    DECLARE("BattleType_5_InvElecMan"       , 5);
    DECLARE("BattleType_6_FinalBoss"        , 6);
    DECLARE("BattleType_7_Boss"             , 7);
    DECLARE("BattleType_8_Save"             , 8);
    DECLARE("BattleType_9"                  , 9);

    // Demo
    DECLARE("Demo_m_state0"                 , offsetof(struct Demo, m_state0));
    DECLARE("Demo_m_state1"                 , offsetof(struct Demo, m_state1));
    DECLARE("Demo_m_b2"                     , offsetof(struct Demo, m_b2));
    DECLARE("Demo_m_demoMessageTimer"       , offsetof(struct Demo, m_demoMessageTimer));
    DECLARE("Demo_m_b6"                     , offsetof(struct Demo, m_b6));

    // Demo_State_0
    DECLARE("D_State_0_State0"                  , 0);
    DECLARE("D_State_0_State1"                  , 4);
    DECLARE("D_State_0_State2_InitializeGame"   , 8);

    // Demo_State_1
    DECLARE("D_State_1_State0"                  , 0);
    DECLARE("D_State_1_State1"                  , 4);
    DECLARE("D_State_1_State2"                  , 8);
    DECLARE("D_State_1_State3"                  , 12);
    DECLARE("D_State_1_State4"                  , 16);
    DECLARE("D_State_1_State5"                  , 20);
    
    // FadeType
    DECLARE("FT_None"                           , 0);
    DECLARE("FT_FadeInFromWhite"                , 1);
    DECLARE("FT_FadeOutToWhite"                 , 2);
    DECLARE("FT_FadeInFromBlack"                , 3);
    DECLARE("FT_FadeOutToBlack"                 , 4);
    DECLARE("FT_FadeInFromBlackExceptSpritesBG0", 5);
    DECLARE("FT_DarkenExceptSpritesBG0"         , 6);
    DECLARE("FT_FadeInFromBlackExceptBG0"       , 7);
    DECLARE("FT_FadeOutToBlackExceptBG0"        , 8);
    DECLARE("FT_FadeInFromWhiteExceptBG0"       , 9);
    DECLARE("FT_FadeOutToWhiteExceptBG0"        , 10);
    DECLARE("FT_FadeInFromBlackExceptBG3"       , 11);
    DECLARE("FT_DarkenExceptBG3"                , 12);
    DECLARE("FT_FadeInAlphaBlendBG0"            , 13);
    DECLARE("FT_FadeOutAlphaBlendBG0"           , 14);

    // BgControlType
    DECLARE("BGC_Standard"                      , 0);
    DECLARE("BGC_OnlyBg0"                       , 1);
    DECLARE("BGC_OnlyBg01"                      , 2);
    DECLARE("BGC_All_4bpp"                      , 3);
    DECLARE("BGC_OnlyBg012"                     , 4);
    DECLARE("BGC_All_8bpp"                      , 5);
    DECLARE("BGC_All_Bg3_8bpp"                  , 6);

    // Manager_State
    DECLARE("MS_State0"                         , 0);
    DECLARE("MS_State1"                         , 4);
    DECLARE("MS_State2"                         , 8);
    DECLARE("MS_State3"                         , 12);
    DECLARE("MS_State4_Demo"                    , 16);
    DECLARE("MS_State5_Initial"                 , 20);
    DECLARE("MS_State6"                         , 24);
    DECLARE("MS_State7"                         , 28);
    DECLARE("MS_State8_GameOver"                , 32);
    DECLARE("MS_State9"                         , 36);
    DECLARE("MS_StateA"                         , 40);

    // DispCnt
    DECLARE("DISPCNT_MODE0"                     , 0);
    DECLARE("DISPCNT_MODE1"                     , 1);
    DECLARE("DISPCNT_MODE2"                     , 2);
    DECLARE("DISPCNT_MODE3"                     , 3);
    DECLARE("DISPCNT_MODE4"                     , 4);
    DECLARE("DISPCNT_MODE5"                     , 5);
    DECLARE("DISPCNT_FRMSEL"                    , 16);
    DECLARE("DISPCNT_HFREE"                     , 32);
    DECLARE("DISPCNT_OMAP1D"                    , 64);
    DECLARE("DISPCNT_FORCEBLANK"                , 128);
    DECLARE("DISPCNT_BG0"                       , 256);
    DECLARE("DISPCNT_BG1"                       , 512);
    DECLARE("DISPCNT_BG2"                       , 1024);
    DECLARE("DISPCNT_BG3"                       , 2048);
    DECLARE("DISPCNT_BGALL"                     , 3840);
    DECLARE("DISPCNT_OBJ"                       , 4096);
    DECLARE("DISPCNT_WIN0"                      , 8192);
    DECLARE("DISPCNT_WIN1"                      , 16384);
    DECLARE("DISPCNT_OBJWIN"                    , 32768);

    // ChipId
    DECLARE("CD_Buster"                         , 0);
    DECLARE("CD_Cannon"                         , 1);
    DECLARE("CD_HiCannon"                       , 2);
    DECLARE("CD_M_Cannon"                       , 3);
    DECLARE("CD_Sword"                          , 4);
    DECLARE("CD_WideSwrd"                       , 5);
    DECLARE("CD_LongSwrd"                       , 6);
    DECLARE("CD_LilBomb"                        , 7);
    DECLARE("CD_CrosBomb"                       , 8);
    DECLARE("CD_BigBomb"                        , 9);
    DECLARE("CD_Spreader"                       , 10);
    DECLARE("CD_Bubbler"                        , 11);
    DECLARE("CD_Heater"                         , 12);
    DECLARE("CD_MiniBomb"                       , 13);
    DECLARE("CD_Shotgun"                        , 14);
    DECLARE("CD_CrossGun"                       , 15);
    DECLARE("CD_ShokWave"                       , 16);
    DECLARE("CD_SoniWave"                       , 17);
    DECLARE("CD_DynaWave"                       , 18);
    DECLARE("CD_FireTowr"                       , 19);
    DECLARE("CD_AquaTowr"                       , 20);
    DECLARE("CD_WoodTowr"                       , 21);
    DECLARE("CD_Quake1"                         , 22);
    DECLARE("CD_Quake2"                         , 23);
    DECLARE("CD_Quake3"                         , 24);
    DECLARE("CD_FireSwrd"                       , 25);
    DECLARE("CD_ElecSwrd"                       , 26);
    DECLARE("CD_AquaSwrd"                       , 27);
    DECLARE("CD_GutsPnch"                       , 28);
    DECLARE("CD_IcePunch"                       , 29);
    DECLARE("CD_FtrSword"                       , 30);
    DECLARE("CD_Dash"                           , 31);
    DECLARE("CD_KngtSwrd"                       , 32);
    DECLARE("CD_HeroSwrd"                       , 33);
    DECLARE("CD_MetGuard"                       , 34);
    DECLARE("CD_TriArrow"                       , 37);
    DECLARE("CD_TriSpear"                       , 38);
    DECLARE("CD_TriLance"                       , 39);
    DECLARE("CD_Typhoon"                        , 40);
    DECLARE("CD_Huricane"                       , 41);
    DECLARE("CD_Cyclone"                        , 42);
    DECLARE("CD_Howitzer"                       , 43);
    DECLARE("CD_Thunder1"                       , 44);
    DECLARE("CD_Thunder2"                       , 45);
    DECLARE("CD_Thunder3"                       , 46);
    DECLARE("CD_Snakegg1"                       , 49);
    DECLARE("CD_Snakegg2"                       , 50);
    DECLARE("CD_Snakegg3"                       , 51);
    DECLARE("CD_Hammer"                         , 52);
    DECLARE("CD_BodyBurn"                       , 55);
    DECLARE("CD_Ratton1"                        , 58);
    DECLARE("CD_Ratton2"                        , 59);
    DECLARE("CD_Ratton3"                        , 60);
    DECLARE("CD_Lockon1"                        , 61);
    DECLARE("CD_Lockon2"                        , 62);
    DECLARE("CD_Lockon3"                        , 63);
    DECLARE("CD_X_Panel1"                       , 64);
    DECLARE("CD_X_Panel3"                       , 65);
    DECLARE("CD_Recov10"                        , 67);
    DECLARE("CD_Recov30"                        , 68);
    DECLARE("CD_Recov50"                        , 69);
    DECLARE("CD_Recov80"                        , 70);
    DECLARE("CD_Recov120"                       , 71);
    DECLARE("CD_Recov150"                       , 72);
    DECLARE("CD_Recov200"                       , 73);
    DECLARE("CD_Recov300"                       , 74);
    DECLARE("CD_Steal"                          , 76);
    DECLARE("CD_Geddon1"                        , 79);
    DECLARE("CD_Geddon2"                        , 80);
    DECLARE("CD_Escape"                         , 82);
    DECLARE("CD_Interrupt"                      , 83);
    DECLARE("CD_LifeAura"                       , 84);
    DECLARE("CD_AquaAura"                       , 85);
    DECLARE("CD_FireAura"                       , 86);
    DECLARE("CD_WoodAura"                       , 87);
    DECLARE("CD_Repair"                         , 88);
    DECLARE("CD_Cloud"                          , 91);
    DECLARE("CD_Cloudier"                       , 92);
    DECLARE("CD_Cloudest"                       , 93);
    DECLARE("CD_IceCube"                        , 94);
    DECLARE("CD_RockCube"                       , 95);
    DECLARE("CD_TimeBom1"                       , 97);
    DECLARE("CD_TimeBom2"                       , 98);
    DECLARE("CD_TimeBom3"                       , 99);
    DECLARE("CD_Invis1"                         , 100);
    DECLARE("CD_Invis2"                         , 101);
    DECLARE("CD_Invis3"                         , 102);
    DECLARE("CD_IronBody"                       , 103);
    DECLARE("CD_Remobit1"                       , 105);
    DECLARE("CD_Remobit2"                       , 106);
    DECLARE("CD_Remobit3"                       , 107);
    DECLARE("CD_BstrGard"                       , 108);
    DECLARE("CD_BstrBomb"                       , 109);
    DECLARE("CD_BstrSwrd"                       , 110);
    DECLARE("CD_BstrPnch"                       , 111);
    DECLARE("CD_RingZap1"                       , 112);
    DECLARE("CD_RingZap2"                       , 113);
    DECLARE("CD_RingZap3"                       , 114);
    DECLARE("CD_Candle1"                        , 115);
    DECLARE("CD_Candle2"                        , 116);
    DECLARE("CD_Candle3"                        , 117);
    DECLARE("CD_SloGauge"                       , 118);
    DECLARE("CD_FstGauge"                       , 119);
    DECLARE("CD_Drain1"                         , 121);
    DECLARE("CD_Drain2"                         , 122);
    DECLARE("CD_Drain3"                         , 123);
    DECLARE("CD_Mine1"                          , 124);
    DECLARE("CD_Mine2"                          , 125);
    DECLARE("CD_Mine3"                          , 126);
    DECLARE("CD_Gaia1"                          , 127);
    DECLARE("CD_Gaia2"                          , 128);
    DECLARE("CD_Gaia3"                          , 129);
    DECLARE("CD_BblWrap1"                       , 130);
    DECLARE("CD_BblWrap2"                       , 131);
    DECLARE("CD_BblWrap3"                       , 132);
    DECLARE("CD_Wave"                           , 133);
    DECLARE("CD_RedWave"                        , 134);
    DECLARE("CD_BigWave"                        , 135);
    DECLARE("CD_Muramasa"                       , 136);
    DECLARE("CD_Dropdown"                       , 137);
    DECLARE("CD_Popup"                          , 138);
    DECLARE("CD_Dynamyt1"                       , 139);
    DECLARE("CD_Dynamyt2"                       , 140);
    DECLARE("CD_Dynamyt3"                       , 141);
    DECLARE("CD_Anubis"                         , 142);
    DECLARE("CD_IronShld"                       , 145);
    DECLARE("CD_LeafShld"                       , 146);
    DECLARE("CD_Barrier"                        , 147);
    DECLARE("CD_PharoMan"                       , 148);
    DECLARE("CD_PharoMn2"                       , 149);
    DECLARE("CD_PharoMn3"                       , 150);
    DECLARE("CD_ShadoMan"                       , 151);
    DECLARE("CD_ShadoMn2"                       , 152);
    DECLARE("CD_ShadoMn3"                       , 153);
    DECLARE("CD_MagicMan"                       , 157);
    DECLARE("CD_MagicMn2"                       , 158);
    DECLARE("CD_MagicMn3"                       , 159);
    DECLARE("CD_Roll"                           , 160);
    DECLARE("CD_Roll2"                          , 161);
    DECLARE("CD_Roll3"                          , 162);
    DECLARE("CD_GutsMan"                        , 163);
    DECLARE("CD_GutsMan2"                       , 164);
    DECLARE("CD_GutsMan3"                       , 165);
    DECLARE("CD_ProtoMan"                       , 166);
    DECLARE("CD_ProtoMn2"                       , 167);
    DECLARE("CD_ProtoMn3"                       , 168);
    DECLARE("CD_WoodMan"                        , 169);
    DECLARE("CD_WoodMan2"                       , 170);
    DECLARE("CD_WoodMan3"                       , 171);
    DECLARE("CD_FireMan"                        , 172);
    DECLARE("CD_FireMan2"                       , 173);
    DECLARE("CD_FireMan3"                       , 174);
    DECLARE("CD_NumbrMan"                       , 175);
    DECLARE("CD_NumbrMn2"                       , 176);
    DECLARE("CD_NumbrMn3"                       , 177);
    DECLARE("CD_StoneMan"                       , 178);
    DECLARE("CD_StoneMn2"                       , 179);
    DECLARE("CD_StoneMn3"                       , 180);
    DECLARE("CD_IceMan"                         , 181);
    DECLARE("CD_IceMan2"                        , 182);
    DECLARE("CD_IceMan3"                        , 183);
    DECLARE("CD_SkullMan"                       , 184);
    DECLARE("CD_SkullMn2"                       , 185);
    DECLARE("CD_SkullMn3"                       , 186);
    DECLARE("CD_ColorMan"                       , 187);
    DECLARE("CD_ColorMn2"                       , 188);
    DECLARE("CD_ColorMn3"                       , 189);
    DECLARE("CD_BombMan"                        , 190);
    DECLARE("CD_BombMan2"                       , 191);
    DECLARE("CD_BombMan3"                       , 192);
    DECLARE("CD_SharkMan"                       , 193);
    DECLARE("CD_SharkMn2"                       , 194);
    DECLARE("CD_SharkMn3"                       , 195);
    DECLARE("CD_ElecMan"                        , 196);
    DECLARE("CD_ElecMan2"                       , 197);
    DECLARE("CD_ElecMan3"                       , 198);
    DECLARE("CD_Bass"                           , 199);

    // ChipCode
    DECLARE("CC_A"                              , 0);
    DECLARE("CC_B"                              , 1);
    DECLARE("CC_C"                              , 2);
    DECLARE("CC_D"                              , 3);
    DECLARE("CC_E"                              , 4);
    DECLARE("CC_F"                              , 5);
    DECLARE("CC_G"                              , 6);
    DECLARE("CC_H"                              , 7);
    DECLARE("CC_I"                              , 8);
    DECLARE("CC_J"                              , 9);
    DECLARE("CC_K"                              , 10);
    DECLARE("CC_L"                              , 11);
    DECLARE("CC_M"                              , 12);
    DECLARE("CC_N"                              , 13);
    DECLARE("CC_O"                              , 14);
    DECLARE("CC_P"                              , 15);
    DECLARE("CC_Q"                              , 16);
    DECLARE("CC_R"                              , 17);
    DECLARE("CC_S"                              , 18);
    DECLARE("CC_T"                              , 19);
    DECLARE("CC_U"                              , 20);
    DECLARE("CC_V"                              , 21);
    DECLARE("CC_W"                              , 22);
    DECLARE("CC_X"                              , 23);
    DECLARE("CC_Y"                              , 24);
    DECLARE("CC_Z"                              , 25);

    // ElementId
    DECLARE("EL_None"                           , 0);
    DECLARE("EL_Elec"                           , 1);
    DECLARE("EL_Fire"                           , 2);
    DECLARE("EL_Water"                          , 3);
    DECLARE("EL_Wood"                           , 4);
}
