    .include "constants.inc"
    .include "macros.inc"

    .text

global_label sprite_battle_megaman
    .incbin "images/sprites/1E0020.sprite"
global_label sprite_battle_mettaur
    .incbin "images/sprites/1EF5FC.sprite.lz"
global_label sprite_battle_woodman
    .incbin "images/sprites/1F0C38.sprite"
global_label sprite_woodman
    .incbin "images/sprites/1F7D90.sprite"
global_label sprite_lan
    .incbin "images/sprites/1F8298.sprite"
global_label sprite_yai
    .incbin "images/sprites/20BC70.sprite"
global_label sprite_dex
    .incbin "images/sprites/20EE08.sprite"
global_label sprite_mari
    .incbin "images/sprites/213EBC.sprite"
global_label sprite_masa
    .incbin "images/sprites/217818.sprite"
global_label sprite_megaman
    .incbin "images/sprites/217DF8.sprite"
global_label sprite_higsby
    .incbin "images/sprites/227474.sprite"
global_label sprite_chaud
    .incbin "images/sprites/22CF28.sprite"
global_label sprite_mayl
    .incbin "images/sprites/230DE0.sprite"
global_label sprite_boy2
    .incbin "images/sprites/234FB4.sprite"
global_label sprite_boy1
    .incbin "images/sprites/239144.sprite"
global_label sprite_car
    .incbin "images/sprites/23B4A8.sprite"
global_label sprite_battle_canodumb
    .incbin "images/sprites/23CB58.sprite.lz"
global_label sprite_battle_fireman
    .incbin "images/sprites/23D858.sprite"
global_label sprite_lan_bed
    .incbin "images/sprites/24C1D0.sprite.lz"
global_label sprite_haruka
    .incbin "images/sprites/24CFCC.sprite"
global_label sprite_battle_vulgear
    .incbin "images/sprites/25226C.sprite.lz"
global_label sprite_match
    .incbin "images/sprites/253DFC.sprite"
global_label sprite_prog1
    .incbin "images/sprites/255004.sprite"
global_label sprite_fireman
    .incbin "images/sprites/25685C.sprite"
global_label sprite_oldman
    .incbin "images/sprites/257978.sprite"
global_label sprite_woman2
    .incbin "images/sprites/25A1F4.sprite"
global_label sprite_man2
    .incbin "images/sprites/25ADB4.sprite"
global_label sprite_woman1
    .incbin "images/sprites/25E238.sprite"
global_label sprite_girl1
    .incbin "images/sprites/260308.sprite"
global_label sprite_girl2
    .incbin "images/sprites/261EB0.sprite"
global_label sprite_man1
    .incbin "images/sprites/2645F8.sprite"
global_label sprite_battle_beetank
    .incbin "images/sprites/266C28.sprite.lz"
global_label sprite_battle_spooky
    .incbin "images/sprites/2680E4.sprite.lz"
global_label sprite_battle_flappy
    .incbin "images/sprites/26A5AC.sprite"
global_label sprite_battle_gutsman
    .incbin "images/sprites/26EA74.sprite"
global_label sprite_numberman
    .incbin "images/sprites/2769A4.sprite"
global_label sprite_battle_numberman
    .incbin "images/sprites/279D18.sprite"
global_label sprite_battle_hardhead
    .incbin "images/sprites/280B9C.sprite.lz"
global_label sprite_battle_fishy
    .incbin "images/sprites/281A20.sprite.lz"
global_label sprite_battle_puffy
    .incbin "images/sprites/28256C.sprite.lz"
global_label sprite_battle_swordy
    .incbin "images/sprites/283128.sprite.lz"
global_label sprite_battle_handy
    .incbin "images/sprites/2846BC.sprite.lz"
global_label sprite_battle_iceman
    .incbin "images/sprites/285DA8.sprite"
global_label sprite_ticketer
    .incbin "images/sprites/2899DC.sprite"
global_label sprite_battle_stoneman
    .incbin "images/sprites/28A53C.sprite"
global_label sprite_battle_piranha
    .incbin "images/sprites/29ADD0.sprite.lz"
global_label sprite_battle_cloudy
    .incbin "images/sprites/29BFE8.sprite.lz"
global_label sprite_official2
    .incbin "images/sprites/29D8E8.sprite"
global_label sprite_official3
    .incbin "images/sprites/29E4E8.sprite"
global_label sprite_battle_coldbear
    .incbin "images/sprites/29F008.sprite.lz"
global_label sprite_scientist
    .incbin "images/sprites/29FFB0.sprite"
global_label sprite_battle_froshell
    .incbin "images/sprites/2A2110.sprite.lz"
global_label sprite_official1
    .incbin "images/sprites/2A2C3C.sprite"
global_label sprite_protoman
    .incbin "images/sprites/2A37FC.sprite"
global_label sprite_oldwoman
    .incbin "images/sprites/2A7EC0.sprite"
global_label sprite_stoneman
    .incbin "images/sprites/2A9D00.sprite"
global_label sprite_battle_ratty
    .incbin "images/sprites/2AA86C.sprite.lz"
global_label sprite_battle_jelly
    .incbin "images/sprites/2AB9DC.sprite.lz"
global_label sprite_iceman
    .incbin "images/sprites/2AC184.sprite"
global_label sprite_battle_miney
    .incbin "images/sprites/2AF868.sprite.lz"
global_label sprite_navi
    .incbin "images/sprites/2B0DF4.sprite"
global_label sprite_battle_ammonicule
    .incbin "images/sprites/2B13F4.sprite.lz"
global_label sprite_battle_effect_bubble
    .incbin "images/sprites/2B19E8.sprite"
global_label sprite_battle_skullman
    .incbin "images/sprites/2B244C.sprite"
global_label sprite_madd
    .incbin "images/sprites/2B8528.sprite"
global_label sprite_battle_colorman
    .incbin "images/sprites/2B9EE8.sprite"
global_label sprite_battle_protoman
    .incbin "images/sprites/2C00D8.sprite"
global_label sprite_roll
    .incbin "images/sprites/2C60B8.sprite"
global_label sprite_colorman
    .incbin "images/sprites/2CAEB4.sprite"
global_label sprite_billy
    .incbin "images/sprites/2CCBE4.sprite.lz"
global_label sprite_battle_prog
    .incbin "images/sprites/2CD91C.sprite.lz"
global_label sprite_battle_remobit
    .incbin "images/sprites/2CE3E4.sprite"
global_label sprite_battle_popper
    .incbin "images/sprites/2CF330.sprite.lz"
global_label sprite_battle_gaia
    .incbin "images/sprites/2CF8F8.sprite.lz"
global_label sprite_wily
    .incbin "images/sprites/2D0B18.sprite"
global_label sprite_battle_magicman
    .incbin "images/sprites/2D57EC.sprite"
global_label sprite_zap
    .incbin "images/sprites/2D7F34.sprite"
global_label sprite_battle_satella
    .incbin "images/sprites/2DAE9C.sprite"
    .incbin "images/sprites/2DD514.sprite"
global_label sprite_yuichiro
    .incbin "images/sprites/2DD8BC.sprite"
global_label sprite_battle_megalian_body
    .incbin "images/sprites/2DF504.sprite.lz"
global_label sprite_official4
    .incbin "images/sprites/2E01A4.sprite"
global_label sprite_waitress
    .incbin "images/sprites/2E213C.sprite"
global_label sprite_battle_elecman
    .incbin "images/sprites/2E4244.sprite"
global_label sprite_elecman
    .incbin "images/sprites/2E7E78.sprite"
global_label sprite_miyu_sit
    .incbin "images/sprites/2EBF94.sprite"
global_label sprite_battle_bombman
    .incbin "images/sprites/2EC140.sprite"
global_label sprite_glyde
    .incbin "images/sprites/2F0854.sprite"
global_label sprite_battle_fanner
    .incbin "images/sprites/2F2B3C.sprite.lz"
global_label sprite_battle_candevil
    .incbin "images/sprites/2F3510.sprite.lz"
global_label sprite_bombman
    .incbin "images/sprites/2F4530.sprite"
global_label sprite_battle_pharaohman
    .incbin "images/sprites/2F5E30.sprite"
global_label sprite_yahoot
    .incbin "images/sprites/2F6458.sprite"
global_label sprite_gutsman
    .incbin "images/sprites/2F7F30.sprite"
global_label sprite_battle_shadowman
    .incbin "images/sprites/2F9888.sprite"
global_label sprite_battle_roll
    .incbin "images/sprites/2FD214.sprite"
global_label sprite_battle_bigsnake_head
    .incbin "images/sprites/300220.sprite.lz"
global_label sprite_battle_mole
    .incbin "images/sprites/300BA0.sprite.lz"
global_label sprite_battle_poitton
    .incbin "images/sprites/3019D4.sprite.lz"
global_label sprite_magicman
    .incbin "images/sprites/3024B8.sprite"
global_label sprite_battle_lifevirus
    .incbin "images/sprites/306804.sprite.lz"
global_label sprite_sal
    .incbin "images/sprites/30A9A4.sprite"
global_label sprite_battle_mosqurito
    .incbin "images/sprites/30AED4.sprite.lz"
global_label sprite_battle_bass
    .incbin "images/sprites/30B520.sprite"
    .incbin "images/sprites/310600.sprite"
    .incbin "images/sprites/311AC0.sprite"
    .incbin "images/sprites/3125BC.sprite"
    .incbin "images/sprites/31429C.sprite"
    .incbin "images/sprites/314740.sprite"
    .incbin "images/sprites/315C38.sprite"
    .incbin "images/sprites/316960.sprite"
    .incbin "images/sprites/3172A8.sprite"
    .incbin "images/sprites/31D1AC.sprite"
    .incbin "images/sprites/31E6A8.sprite"
    .incbin "images/sprites/31F390.sprite"
    .incbin "images/sprites/32069C.sprite"
    .incbin "images/sprites/321244.sprite"
    .incbin "images/sprites/322404.sprite"
    .incbin "images/sprites/323CFC.sprite"
    .incbin "images/sprites/327A38.sprite"
    .incbin "images/sprites/329330.sprite"
    .incbin "images/sprites/32BE88.sprite"
    .incbin "images/sprites/32D8A0.sprite"
    .incbin "images/sprites/32E3A8.sprite"
    .incbin "images/sprites/32F4D0.sprite"
    .incbin "images/sprites/332550.sprite"
    .incbin "images/sprites/33EE04.sprite"
    .incbin "images/sprites/33F9DC.sprite"
    .incbin "images/sprites/340EEC.sprite"
    .incbin "images/sprites/3419F8.sprite"
    .incbin "images/sprites/3435E4.sprite"
    .incbin "images/sprites/3456B0.sprite"
    .incbin "images/sprites/345824.sprite"
    .incbin "images/sprites/34723C.sprite"
    .incbin "images/sprites/348B2C.sprite"
    .incbin "images/sprites/349F04.sprite"
    .incbin "images/sprites/34A59C.sprite"
    .incbin "images/sprites/34C8B4.sprite"
    .incbin "images/sprites/3558B8.sprite"
    .incbin "images/sprites/357224.sprite"
    .incbin "images/sprites/357304.sprite"
    .incbin "images/sprites/3576AC.sprite"
    .incbin "images/sprites/358164.sprite"
    .incbin "images/sprites/3590FC.sprite"
    .incbin "images/sprites/359CD4.sprite"
    .incbin "images/sprites/35A7C8.sprite"
    .incbin "images/sprites/35B75C.sprite"
    .incbin "images/sprites/35C194.sprite"
    .incbin "images/sprites/35C670.sprite"
    .incbin "images/sprites/35D570.sprite"
    .incbin "images/sprites/35E3FC.sprite"
    .incbin "images/sprites/35ECEC.sprite"
    .incbin "images/sprites/35FCAC.sprite"
    .incbin "images/sprites/361EEC.sprite"
    .incbin "images/sprites/3623DC.sprite"
    .incbin "images/sprites/363360.sprite"
    .incbin "images/sprites/36350C.sprite"
    .incbin "images/sprites/3636AC.sprite"
    .incbin "images/sprites/3644D0.sprite"
    .incbin "images/sprites/365028.sprite"
    .incbin "images/sprites/365D18.sprite"
    .incbin "images/sprites/366D44.sprite"
    .incbin "images/sprites/367570.sprite"
    .incbin "images/sprites/3678E0.sprite"
    .incbin "images/sprites/368270.sprite"
    .incbin "images/sprites/3689A8.sprite"
    .incbin "images/sprites/36A384.sprite"
    .incbin "images/sprites/36AB8C.sprite"
    .incbin "images/sprites/36B708.sprite"
    .incbin "images/sprites/36BF78.sprite"
    .incbin "images/sprites/36D100.sprite"
    .incbin "images/sprites/36EBEC.sprite"
    .incbin "images/sprites/36F350.sprite"
    .incbin "images/sprites/36FDC4.sprite"
    .incbin "images/sprites/370034.sprite"
    .incbin "images/sprites/3714CC.sprite"
    .incbin "images/sprites/3727D0.sprite"
    .incbin "images/sprites/375958.sprite"
    .incbin "images/sprites/375FB4.sprite"
    .incbin "images/sprites/377988.sprite"
    .incbin "images/sprites/377E50.sprite"
    .incbin "images/sprites/378878.sprite"
    .incbin "images/sprites/379330.sprite"
    .incbin "images/sprites/379A40.sprite"
    .incbin "images/sprites/37A980.sprite"
    .incbin "images/sprites/37BD4C.sprite"
    .incbin "images/sprites/37C080.sprite"
    .incbin "images/sprites/37C85C.sprite"
    .incbin "images/sprites/37CB30.sprite"
    .incbin "images/sprites/37D894.sprite"
    .incbin "images/sprites/37E034.sprite"
    .incbin "images/sprites/37E0B4.sprite"
    .incbin "images/sprites/37E4AC.sprite"
    .incbin "images/sprites/37E898.sprite"
    .incbin "images/sprites/380EC8.sprite"
    .incbin "images/sprites/383518.sprite"
    .incbin "images/sprites/383628.sprite"
    .incbin "images/sprites/384E9C.sprite"
    .incbin "images/sprites/3854C8.sprite"
    .incbin "images/sprites/38629C.sprite"
    .incbin "images/sprites/387870.sprite"
    .incbin "images/sprites/388120.sprite"
    .incbin "images/sprites/388678.sprite"
    .incbin "images/sprites/389400.sprite.lz"
    .incbin "images/sprites/3895A4.sprite.lz"
    .incbin "images/sprites/389894.sprite.lz"
    .incbin "images/sprites/389C78.sprite.lz"
    .incbin "images/sprites/38A030.sprite"
    .incbin "images/sprites/38AF2C.sprite"
    .incbin "images/sprites/38B898.sprite.lz"
    .incbin "images/sprites/38B9DC.sprite.lz"
    .incbin "images/sprites/38BB98.sprite"
    .incbin "images/sprites/38D5A0.sprite"
    .incbin "images/sprites/38E5A0.sprite"
    .incbin "images/sprites/38FC34.sprite"
    .incbin "images/sprites/391344.sprite"
    .incbin "images/sprites/3929F0.sprite"
    .incbin "images/sprites/392B5C.sprite.lz"
    .incbin "images/sprites/392FB0.sprite.lz"
    .incbin "images/sprites/39316C.sprite.lz"
    .incbin "images/sprites/393308.sprite.lz"
    .incbin "images/sprites/393420.sprite.lz"
    .incbin "images/sprites/393AD4.sprite"
    .incbin "images/sprites/3963DC.sprite"
    .incbin "images/sprites/397144.sprite.lz"
    .incbin "images/sprites/397934.sprite.lz"
    .incbin "images/sprites/397C90.sprite"
    .incbin "images/sprites/398F70.sprite"
    .incbin "images/sprites/39AB78.sprite.lz"
    .incbin "images/sprites/39AD44.sprite.lz"
    .incbin "images/sprites/39AE5C.sprite.lz"
    .incbin "images/sprites/39AF64.sprite.lz"
    .incbin "images/sprites/39B260.sprite.lz"
    .incbin "images/sprites/39B8B4.sprite.lz"
    .incbin "images/sprites/39BB88.sprite.lz"
    .incbin "images/sprites/39BF24.sprite.lz"
    .incbin "images/sprites/39C204.sprite.lz"
    .incbin "images/sprites/39C2F4.sprite.lz"
    .incbin "images/sprites/39C4FC.sprite.lz"
    .incbin "images/sprites/39C734.sprite.lz"
    .incbin "images/sprites/39C8AC.sprite.lz"
    .incbin "images/sprites/39C9C0.sprite"
    .incbin "images/sprites/39DC0C.sprite.lz"
    .incbin "images/sprites/39DD0C.sprite.lz"
    .incbin "images/sprites/39E0DC.sprite"
    .incbin "images/sprites/39E5C0.sprite"
    .incbin "images/sprites/39EB44.sprite"
    .incbin "images/sprites/39F118.sprite"
    .incbin "images/sprites/39F968.sprite"
    .incbin "images/sprites/3A0284.sprite"
    .incbin "images/sprites/3A04D0.sprite"
    .incbin "images/sprites/3A1050.sprite.lz"
    .incbin "images/sprites/3A1154.sprite"
    .incbin "images/sprites/3A1608.sprite.lz"
    .incbin "images/sprites/3A1870.sprite.lz"
    .incbin "images/sprites/3A27A4.sprite.lz"
    .incbin "images/sprites/3A2B00.sprite.lz"
    .incbin "images/sprites/3A3C1C.sprite"
    .incbin "images/sprites/3A3E40.sprite"
    .incbin "images/sprites/3A49E0.sprite"
    .incbin "images/sprites/3A50A4.sprite"
    .incbin "images/sprites/3A5730.sprite"
    .incbin "images/sprites/3A5EDC.sprite"
    .incbin "images/sprites/3A61A8.sprite"
    .incbin "images/sprites/3A6444.sprite.lz"
    .incbin "images/sprites/3A698C.sprite.lz"
global_label sprite_battle_sharkman_fin
    .incbin "images/sprites/3A6D20.sprite"
    .incbin "images/sprites/3AAFE4.sprite"
    .incbin "images/sprites/3ABE70.sprite.lz"
    .incbin "images/sprites/3AC31C.sprite"
    .incbin "images/sprites/3AC778.sprite.lz"
    .incbin "images/sprites/3AC8E8.sprite"
    .incbin "images/sprites/3ACFE0.sprite"
    .incbin "images/sprites/3AD428.sprite.lz"
    .incbin "images/sprites/3AD644.sprite.lz"
    .incbin "images/sprites/3AD838.sprite.lz"
    .incbin "images/sprites/3ADA50.sprite.lz"
    .incbin "images/sprites/3ADB44.sprite"
    .incbin "images/sprites/3ADFD4.sprite.lz"
    .incbin "images/sprites/3AE1DC.sprite.lz"
    .incbin "images/sprites/3AE330.sprite.lz"
    .incbin "images/sprites/3AE450.sprite.lz"
    .incbin "images/sprites/3AE5D8.sprite.lz"
    .incbin "images/sprites/3AE810.sprite.lz"
    .incbin "images/sprites/3AE95C.sprite.lz"
    .incbin "images/sprites/3AEC30.sprite.lz"
    .incbin "images/sprites/3AF4E8.sprite.lz"
    .incbin "images/sprites/3AFE10.sprite.lz"
    .incbin "images/sprites/3B01B8.sprite.lz"

    .incbin "data/maps/offline/ACDC_Elementary/map_56A038.tilesetz" @ 0x3B0298
    .incbin "data/maps/offline/ACDC_Elementary/map_56A038.palettez" @ 0x3B3230
    .incbin "data/maps/offline/ACDC_Elementary/map_56A038.tilemapz" @ 0x3B33D4
    .incbin "data/maps/offline/ACDC_Elementary/map_56AAD4.tilemapz" @ 0x3B4054
    .incbin "data/maps/offline/ACDC_Elementary/map_56B55C.palettez" @ 0x3B4CF4
    .incbin "data/maps/offline/ACDC_Elementary/map_56B55C.tilesetz" @ 0x3B4E98 <- check
    .incbin "data/maps/offline/ACDC_Elementary/map_56B55C.tilemapz" @ 0x3B7980
    .incbin "data/maps/offline/ACDC_Elementary/map_56C38C.tilesetz" @ 0x3B9148
    .incbin "data/maps/offline/ACDC_Elementary/map_56C38C.palettez" @ 0x3BBEC0 <- check
    .incbin "data/maps/offline/ACDC_Elementary/map_56C38C.tilemapz" @ 0x3BC064
    .incbin "data/maps/offline/ACDC_Elementary/map_56C880.palettez" @ 0x3BF0B4
    .incbin "data/maps/offline/ACDC_Elementary/map_56C880.tilemapz" @ 0x3BF258
    .incbin "data/maps/offline/ACDC_Elementary/map_56D314.palettez" @ 0x3BFEF0
    .incbin "data/maps/offline/ACDC_Elementary/map_56D314.tilemapz" @ 0x3C0094
    .incbin "data/maps/offline/ACDC_Elementary/map_56DD8C.palettez" @ 0x3C0D04
    .incbin "data/maps/offline/ACDC_Elementary/map_56DD8C.tilemapz" @ 0x3C0EA8
    .incbin "data/maps/offline/ACDC_Elementary/map_56E684.tilesetz" @ 0x3C1CA8
    .incbin "data/maps/offline/ACDC_Elementary/map_56E684.palettez" @ 0x3C434C
    .incbin "data/maps/offline/ACDC_Elementary/map_56E684.tilemapz" @ 0x3C44F0
    .incbin "data/maps/offline/ACDC_Elementary/map_56E94C.tilemapz" @ 0x3C51D4
    .incbin "data/maps/offline/ACDC_Elementary/map_56EEA0.palettez" @ 0x3C8280
    .incbin "data/maps/offline/ACDC_Elementary/map_56EEA0.tilemapz" @ 0x3C8424
    .incbin "data/maps/offline/ACDC_Elementary/map_56F084.tilesetz" @ 0x3C8F94
    .incbin "data/maps/offline/ACDC_Elementary/map_56F084.palettez" @ 0x3CBF18
    .incbin "data/maps/offline/ACDC_Elementary/map_56F084.tilemapz" @ 0x3CC0BC
    .incbin "data/maps/offline/ACDC_Elementary/map_56F604.tilesetz" @ 0x3CD220
    .incbin "data/maps/offline/ACDC_Elementary/map_56F604.palettez" @ 0x3CFBD0
    .incbin "data/maps/offline/ACDC_Elementary/map_56F604.tilemapz" @ 0x3CFD74
    .incbin "data/maps/offline/ACDC_Elementary/map_5707EC.palettez" @ 0x3D10CC
    .incbin "data/maps/offline/ACDC_Elementary/map_5707EC.tilemapz" @ 0x3D1270
    .incbin "data/maps/offline/ACDC_Town/map_570A60.tilesetz" @ 0x3D22F0
    .incbin "data/maps/offline/ACDC_Town/map_570A60.palettez" @ 0x3D8104
    .incbin "data/maps/offline/ACDC_Town/map_570A60.tilemapz" @ 0x3D82A8
    .incbin "data/maps/offline/ACDC_Town/map_574080.tilesetz" @ 0x3DD8FC
    .incbin "data/maps/offline/ACDC_Town/map_574080.palettez" @ 0x3E1FC0
    .incbin "data/maps/offline/ACDC_Town/map_574080.tilemapz" @ 0x3E2164
    .incbin "data/maps/offline/ACDC_Town/map_574A2C.tilesetz" @ 0x3E3CC4
    .incbin "data/maps/offline/ACDC_Town/map_574A2C.palettez" @ 0x3E6678
    .incbin "data/maps/offline/ACDC_Town/map_574A2C.tilemapz" @ 0x3E681C
    .incbin "data/maps/offline/ACDC_Town/map_5751D0.tilesetz" @ 0x3E7718
    .incbin "data/maps/offline/ACDC_Town/map_5751D0.palettez" @ 0x3E9500
    .incbin "data/maps/offline/ACDC_Town/map_5751D0.tilemapz" @ 0x3E96A4
    .incbin "data/maps/offline/ACDC_Town/map_5754A8.tilesetz" @ 0x3EA180
    .incbin "data/maps/offline/ACDC_Town/map_5754A8.palettez" @ 0x3EC5F0
    .incbin "data/maps/offline/ACDC_Town/map_5754A8.tilemapz" @ 0x3EC794
    .incbin "data/maps/offline/ACDC_Town/map_575C98.tilesetz" @ 0x3ED76C
    .incbin "data/maps/offline/ACDC_Town/map_575C98.palettez" @ 0x3EF004
    .incbin "data/maps/offline/ACDC_Town/map_575C98.tilemapz" @ 0x3EF1A8
    .incbin "data/maps/offline/ACDC_Town/map_5761A8.tilesetz" @ 0x3EFBD4
    .incbin "data/maps/offline/ACDC_Town/map_5761A8.palettez" @ 0x3F2310
    .incbin "data/maps/offline/ACDC_Town/map_5761A8.tilemapz" @ 0x3F24B4
    .incbin "data/maps/offline/ACDC_Town/map_57663C.tilesetz" @ 0x3F308C
    .incbin "data/maps/offline/ACDC_Town/map_57663C.palettez" @ 0x3F600C
    .incbin "data/maps/offline/ACDC_Town/map_57663C.tilemapz" @ 0x3F61B0
    .incbin "data/maps/offline/ACDC_Town/map_576C60.tilesetz" @ 0x3F715C
    .incbin "data/maps/offline/ACDC_Town/map_576C60.palettez" @ 0x3F9D04
    .incbin "data/maps/offline/ACDC_Town/map_576C60.tilemapz" @ 0x3F9EA8
    .incbin "data/maps/offline/ACDC_Town/map_577280.tilesetz" @ 0x3FACE4
    .incbin "data/maps/offline/ACDC_Town/map_577280.palettez" @ 0x3FEE84
    .incbin "data/maps/offline/ACDC_Town/map_577280.tilemapz" @ 0x3FF028
    .incbin "data/maps/offline/ACDC_Town/map_577770.palettez" @ 0x4005B0
    .incbin "data/maps/offline/ACDC_Town/map_577770.tilemapz" @ 0x400754
    .incbin "data/maps/offline/Govt_Complex/map_57793C.tilesetz" @ 0x401ABC
    .incbin "data/maps/offline/Govt_Complex/map_57793C.palettez" @ 0x405374
    .incbin "data/maps/offline/Govt_Complex/map_57793C.tilemapz" @ 0x405518
    .incbin "data/maps/offline/Govt_Complex/map_578BB8.palettez" @ 0x40A4A0
    .incbin "data/maps/offline/Govt_Complex/map_578BB8.tilemapz" @ 0x40A644
    .incbin "data/maps/offline/Govt_Complex/map_578FB0.tilesetz" @ 0x40BDD0
    .incbin "data/maps/offline/Govt_Complex/map_578FB0.palettez" @ 0x40E520
    .incbin "data/maps/offline/Govt_Complex/map_578FB0.tilemapz" @ 0x40E6C4
    .incbin "data/maps/offline/Govt_Complex/map_57A3B0.tilesetz" @ 0x410FA4
    .incbin "data/maps/offline/Govt_Complex/map_57A3B0.palettez" @ 0x41338C
    .incbin "data/maps/offline/Govt_Complex/map_57A3B0.tilemapz" @ 0x413530
    .incbin "data/maps/offline/Govt_Complex/map_57B814.tilesetz" @ 0x415D74
    .incbin "data/maps/offline/Govt_Complex/map_57B814.palettez" @ 0x41640C
    .incbin "data/maps/offline/Govt_Complex/map_57B814.tilemapz" @ 0x4165B0
    .incbin "data/maps/offline/Govt_Complex/map_57C4A0.tilesetz" @ 0x4176B8
    .incbin "data/maps/offline/Govt_Complex/map_57C4A0.palettez" @ 0x419D04
    .incbin "data/maps/offline/Govt_Complex/map_57C4A0.tilemapz" @ 0x419EA8
    .incbin "data/maps/offline/Govt_Complex/map_57D2A8.tilesetz" @ 0x41C27C
    .incbin "data/maps/offline/Govt_Complex/map_57D2A8.palettez" @ 0x41D8F0
    .incbin "data/maps/offline/Govt_Complex/map_57D2A8.tilemapz" @ 0x41DA94
    .incbin "data/maps/offline/Govt_Complex/map_57DAA8.tilesetz" @ 0x41F390
    .incbin "data/maps/offline/Govt_Complex/map_57DAA8.palettez" @ 0x420B50
    .incbin "data/maps/offline/Govt_Complex/map_57DAA8.tilemapz" @ 0x420CF4
    .incbin "data/maps/offline/Govt_Complex/map_57E6DC.tilesetz" @ 0x42344C
    .incbin "data/maps/offline/Govt_Complex/map_57E6DC.palettez" @ 0x426324
    .incbin "data/maps/offline/Govt_Complex/map_57E6DC.tilemapz" @ 0x4264C8
    .incbin "data/maps/offline/Govt_Complex/map_57E994.palettez" @ 0x428498
    .incbin "data/maps/offline/Govt_Complex/map_57E994.tilemapz" @ 0x42863C
    .incbin "data/maps/offline/DenTown/map_57F160.tilesetz" @ 0x42BDB8
    .incbin "data/maps/offline/DenTown/map_57F160.palettez" @ 0x42ED5C
    .incbin "data/maps/offline/DenTown/map_57F160.tilemapz" @ 0x42EF00
    .incbin "data/maps/offline/DenTown/map_581924.palettez" @ 0x432970
    .incbin "data/maps/offline/DenTown/map_581924.tilemapz" @ 0x432B14
    .incbin "data/maps/offline/DenTown/map_581D30.tilesetz" @ 0x43423C
    .incbin "data/maps/offline/DenTown/map_581D30.palettez" @ 0x438430
    .incbin "data/maps/offline/DenTown/map_581D30.tilemapz" @ 0x4385D4
    .incbin "data/maps/offline/DenTown/map_583404.palettez" @ 0x43A984
    .incbin "data/maps/offline/DenTown/map_583404.tilemapz" @ 0x43AB28
    .incbin "data/maps/offline/DenTown/map_584CC0.palettez" @ 0x43CE70
    .incbin "data/maps/offline/DenTown/map_584CC0.tilemapz" @ 0x43D014
    .incbin "data/maps/offline/DenTown/map_5864D0.palettez" @ 0x43F534
    .incbin "data/maps/offline/DenTown/map_5864D0.tilemapz" @ 0x43F6D8
    .incbin "data/maps/offline/DenTown/map_587ACC.tilesetz" @ 0x441810
    .incbin "data/maps/offline/DenTown/map_587ACC.palettez" @ 0x443618
    .incbin "data/maps/offline/DenTown/map_587ACC.tilemapz" @ 0x4437BC
    .incbin "data/maps/offline/DenTown/map_587E00.tilesetz" @ 0x4442B0
    .incbin "data/maps/offline/DenTown/map_587E00.palettez" @ 0x44531C
    .incbin "data/maps/offline/DenTown/map_587E00.tilemapz" @ 0x4454C0
    .incbin "data/maps/offline/SciLab/map_58853C.tilesetz" @ 0x445F98
    .incbin "data/maps/offline/SciLab/map_58853C.palettez" @ 0x447BB8
    .incbin "data/maps/offline/SciLab/map_58853C.tilemapz" @ 0x447D5C
    .incbin "data/maps/offline/SciLab/map_588C00.tilesetz" @ 0x44A1C4
    .incbin "data/maps/offline/SciLab/map_588C00.palettez" @ 0x44CB4C
    .incbin "data/maps/offline/SciLab/map_588C00.tilemapz" @ 0x44CCF0
    .incbin "data/maps/offline/SciLab/map_58A988.palettez" @ 0x44F584
    .incbin "data/maps/offline/SciLab/map_58A988.tilemapz" @ 0x44F728
    .incbin "data/maps/offline/SciLab/map_58AFF0.palettez" @ 0x451AFC
    .incbin "data/maps/offline/SciLab/map_58AFF0.tilemapz" @ 0x451CA0
    .incbin "data/maps/offline/SciLab/map_58B330.palettez" @ 0x4537D8
    .incbin "data/maps/offline/SciLab/map_58B330.tilemapz" @ 0x45397C
    .incbin "data/maps/offline/SciLab/map_58BCB0.tilesetz" @ 0x454EEC
    .incbin "data/maps/offline/SciLab/map_58BCB0.palettez" @ 0x45673C
    .incbin "data/maps/offline/SciLab/map_58BCB0.tilemapz" @ 0x4568E0
    .incbin "data/maps/offline/WWW_Base/map_58BFF8.tilesetz" @ 0x458D1C
    .incbin "data/maps/offline/WWW_Base/map_58BFF8.palettez" @ 0x45C3EC
    .incbin "data/maps/offline/WWW_Base/map_58BFF8.tilemapz" @ 0x45C590
    .incbin "data/maps/offline/WWW_Base/map_58D42C.tilesetz" @ 0x45E93C
    .incbin "data/maps/offline/WWW_Base/map_58D42C.palettez" @ 0x462CC4
    .incbin "data/maps/offline/WWW_Base/map_58D42C.tilemapz" @ 0x462E68
    .incbin "data/maps/offline/WWW_Base/map_58DCA8.tilesetz" @ 0x465260
    .incbin "data/maps/offline/WWW_Base/map_58DCA8.palettez" @ 0x468E34
    .incbin "data/maps/offline/WWW_Base/map_58DCA8.tilemapz" @ 0x468FD8
    .incbin "data/maps/offline/WWW_Base/map_58E4D4.tilesetz" @ 0x46B200
    .incbin "data/maps/offline/WWW_Base/map_58E4D4.palettez" @ 0x46C410
    .incbin "data/maps/offline/WWW_Base/map_58E4D4.tilemapz" @ 0x46C5B4
    .incbin "data/maps/offline/WWW_Base/map_58EAA4.palettez" @ 0x46D578
    .incbin "data/maps/offline/WWW_Base/map_58EAA4.tilemapz" @ 0x46D71C
    .incbin "data/maps/offline/WWW_Base/map_58F058.palettez" @ 0x46E6B0
    .incbin "data/maps/offline/WWW_Base/map_58F058.tilemapz" @ 0x46E854
    .incbin "data/maps/online/SchoolComp/map_58F5C8.tilesetz" @ 0x46F8A8
    .incbin "data/maps/online/SchoolComp/map_58F5C8.palettez" @ 0x472B84
    .incbin "data/maps/online/SchoolComp/map_58F5C8.tilemapz" @ 0x472D28
    .incbin "data/maps/online/SchoolComp/map_590FF8.tilesetz" @ 0x475A74
    .incbin "data/maps/online/SchoolComp/map_590FF8.palettez" @ 0x478820
    .incbin "data/maps/online/SchoolComp/map_590FF8.tilemapz" @ 0x4789C4
    .incbin "data/maps/online/SchoolComp/map_593D9C.palettez" @ 0x47B634
    .incbin "data/maps/online/SchoolComp/map_593D9C.tilemapz" @ 0x47B7D8
    .incbin "data/maps/online/SchoolComp/map_5949D8.palettez" @ 0x47E290
    .incbin "data/maps/online/SchoolComp/map_5949D8.tilemapz" @ 0x47E434
    .incbin "data/maps/online/SchoolComp/map_595F10.palettez" @ 0x481450
    .incbin "data/maps/online/SchoolComp/map_595F10.tilemapz" @ 0x4815F4
    .incbin "data/maps/online/OvenComp/map_596C9C.tilesetz" @ 0x483F78
    .incbin "data/maps/online/OvenComp/map_596C9C.palettez" @ 0x487718
    .incbin "data/maps/online/OvenComp/map_596C9C.tilemapz" @ 0x4878BC
    .incbin "data/maps/online/OvenComp/map_5985C4.tilemapz" @ 0x48BB6C
    .incbin "data/maps/online/WaterworksComp/map_599A28.tilesetz" @ 0x48EE68
    .incbin "data/maps/online/WaterworksComp/map_599A28.palettez" @ 0x4955C4
    .incbin "data/maps/online/WaterworksComp/map_599A28.tilemapz" @ 0x495768
    .incbin "data/maps/online/WaterworksComp/map_59BD44.tilemapz" @ 0x49A91C
    .incbin "data/maps/online/WaterworksComp/map_59EBA0.tilemapz" @ 0x49EC7C
    .incbin "data/maps/online/WaterworksComp/map_5A427C.tilesetz" @ 0x4A4264
    .incbin "data/maps/online/WaterworksComp/map_5A427C.palettez" @ 0x4A99D0
    .incbin "data/maps/online/WaterworksComp/map_5A427C.tilemapz" @ 0x4A9B74
    .incbin "data/maps/online/WaterworksComp/map_5A9F50.tilesetz" @ 0x4AF050
    .incbin "data/maps/online/WaterworksComp/map_5A9F50.palettez" @ 0x4B26C4
    .incbin "data/maps/online/WaterworksComp/map_5A9F50.tilemapz" @ 0x4B2868
    .incbin "data/maps/online/WaterworksComp/map_5B1478.palettez" @ 0x4B6EE0
    .incbin "data/maps/online/WaterworksComp/map_5B1478.tilemapz" @ 0x4B7084
    .incbin "data/maps/online/TrafficLight_Comp/map_5B64D0.tilesetz" @ 0x4BBFB0
    .incbin "data/maps/online/TrafficLight_Comp/map_5B64D0.palettez" @ 0x4BDB30
    .incbin "data/maps/online/TrafficLight_Comp/map_5B64D0.tilemapz" @ 0x4BDCD4
    .incbin "data/maps/online/TrafficLight_Comp/map_5B82F4.tilemapz" @ 0x4C16F0
    .incbin "data/maps/online/TrafficLight_Comp/map_5BA740.tilemapz" @ 0x4C5284
    .incbin "data/maps/online/TrafficLight_Comp/map_5BE13C.tilemapz" @ 0x4C9438
    .incbin "data/maps/online/TrafficLight_Comp/map_5C05DC.tilemapz" @ 0x4CCC70
    .incbin "data/maps/online/Power_Plant_Comp/map_5C2A2C.tilesetz" @ 0x4D16FC
    .incbin "data/maps/online/Power_Plant_Comp/map_5C2A2C.palettez" @ 0x4D3868
    .incbin "data/maps/online/Power_Plant_Comp/map_5C2A2C.tilemapz" @ 0x4D3A0C
    .incbin "data/maps/online/Power_Plant_Comp/map_5C7B08.tilemapz" @ 0x4D8530
    .incbin "data/maps/online/Power_Plant_Comp/map_5C9FF8.tilemapz" @ 0x4DCF48
    .incbin "data/maps/online/Power_Plant_Comp/map_5CD228.tilemapz" @ 0x4E1AE8
    .incbin "data/maps/online/WWW_Comp/map_5CFF6C.tilemapz" @ 0x4E63AC
    .incbin "data/maps/online/WWW_Comp/map_5D1B54.palettez" @ 0x4EAFBC
    .incbin "data/maps/online/WWW_Comp/map_5D1B54.tilemapz" @ 0x4EB160
    .incbin "data/maps/online/WWW_Comp/map_5D57A8.tilemapz" @ 0x4EEFC0
    .incbin "data/maps/online/WWW_Comp/map_5D9F4C.tilemapz" @ 0x4F3DE0
    .incbin "data/maps/online/WWW_Comp/map_5DB4A8.tilemapz" @ 0x4F8438
    .incbin "data/maps/online/WWW_Comp/map_5DE704.tilesetz" @ 0x4FCBA4
    .incbin "data/maps/online/WWW_Comp/map_5DE704.palettez" @ 0x4FDCFC
    .incbin "data/maps/online/WWW_Comp/map_5DE704.tilemapz" @ 0x4FDEA0
    .incbin "data/maps/online/ACDC_HP/map_5DED58.tilesetz" @ 0x500FD4
    .incbin "data/maps/online/ACDC_HP/map_5DED58.palettez" @ 0x502C60
    .incbin "data/maps/online/ACDC_HP/map_5DED58.tilemapz" @ 0x502E04
    .incbin "data/maps/online/ACDC_HP/map_5DEFE4.tilemapz" @ 0x503934
    .incbin "data/maps/online/ACDC_HP/map_5DEFE4.palettez" @ 0x506384
    .incbin "data/maps/online/ACDC_HP/map_5E0C24.tilemapz" @ 0x506528
    .incbin "data/maps/online/ACDC_HP/map_5E0C24.palettez" @ 0x5087D4
    .incbin "data/maps/online/ACDC_HP/map_5E1C18.tilemapz" @ 0x508978
    .incbin "data/maps/online/ACDC_HP/map_5E1C18.palettez" @ 0x50C900
    .incbin "data/maps/online/Govt_Complex_HP/map_5E22A8.tilesetz" @ 0x50CAA4
    .incbin "data/maps/online/Govt_Complex_HP/map_5E22A8.palettez" @ 0x50DC6C
    .incbin "data/maps/online/Govt_Complex_HP/map_5E22A8.tilemapz" @ 0x50DE10
    .incbin "data/maps/online/Govt_Complex_HP/map_5E27D8.tilemapz" @ 0x50F498
    .incbin "data/maps/online/Govt_Complex_HP/map_5E27D8.palettez" @ 0x511580
    .incbin "data/maps/online/DenTown_HP/map_5E2F20.tilemapz" @ 0x511724
    .incbin "data/maps/online/DenTown_HP/map_5E2F20.palettez" @ 0x51398C
    .incbin "data/maps/online/Govt_Complex_HP_2/map_5E384C.tilemapz" @ 0x513B30
    .incbin "data/maps/online/Govt_Complex_HP_2/map_5E384C.palettez" @ 0x517C78
    .incbin "data/maps/online/Other/Generic.tilemapz" @ 0x517E1C
    .incbin "data/maps/online/Other/Generic.palettez" @ 0x51A1C4
    .incbin "data/maps/online/Internet/map_5E4604.tilesetz" @ 0x51A368
    .incbin "data/maps/online/Internet/map_5E4604.palettez" @ 0x51E23C
    .incbin "data/maps/online/Internet/map_5E4604.tilemapz" @ 0x51E3E0
    .incbin "data/maps/online/Internet/map_5E774C.tilemapz" @ 0x523568
    .incbin "data/maps/online/Internet/map_5ED608.tilemapz" @ 0x528AE8
    .incbin "data/maps/online/Internet/map_5F1E54.tilemapz" @ 0x52D57C
    .incbin "data/maps/online/Internet/map_5F5548.tilemapz" @ 0x531ED4
    .incbin "data/maps/online/Internet/map_5F8100.tilemapz" @ 0x53614C
    .incbin "data/maps/online/Internet/map_5FA53C.tilemapz" @ 0x53A4C8
    .incbin "data/maps/online/Internet/map_5FCB14.tilemapz" @ 0x53E484
    .incbin "data/maps/online/Internet/map_5FFEE0.tilemapz" @ 0x542204
    .incbin "data/maps/online/Internet/map_6017A8.tilemapz" @ 0x545C3C
    .incbin "data/maps/online/Internet/map_604AB4.tilemapz" @ 0x549A60
    .incbin "data/maps/online/Internet/map_6074E0.tilemapz" @ 0x54DF24
    .incbin "data/maps/online/Internet/map_609B64.tilemapz" @ 0x551D84
    .incbin "data/maps/online/Internet/map_60AD44.tilemapz" @ 0x55564C
    .incbin "data/maps/online/Internet/map_60DE5C.tilemapz" @ 0x559694
    .incbin "data/maps/online/Internet/map_6109C0.tilemapz" @ 0x55CF88
    .incbin "data/maps/battle/NumberMan.tilesetz" @ 0x561434
    .incbin "data/maps/battle/NumberMan.palettez" @ 0x561650
    .incbin "data/maps/battle/NumberMan.tilemapz" @ 0x561774
    .incbin "data/maps/battle/FireMan.tilesetz" @ 0x561C78
    .incbin "data/maps/battle/FireMan.palettez" @ 0x561E84
    .incbin "data/maps/battle/FireMan.tilemapz" @ 0x561FA8
    .incbin "data/maps/battle/IceMan.tilesetz" @ 0x562478
    .incbin "data/maps/battle/IceMan.palettez" @ 0x562674
    .incbin "data/maps/battle/IceMan.tilemapz" @ 0x562798
    .incbin "data/maps/battle/ColorMan.tilesetz" @ 0x562C6C
    .incbin "data/maps/battle/ColorMan.palettez" @ 0x562EE4
    .incbin "data/maps/battle/ColorMan.tilemapz" @ 0x563008
    .incbin "data/maps/battle/ElecMan.tilesetz" @ 0x563500
    .incbin "data/maps/battle/ElecMan.palettez" @ 0x5637A8
    .incbin "data/maps/battle/ElecMan.tilemapz" @ 0x5638CC
    .incbin "data/maps/battle/WWW.tilesetz" @ 0x563E24
    .incbin "data/maps/battle/WWW.palettez" @ 0x563FEC
    .incbin "data/maps/battle/WWW.tilemapz" @ 0x564110
    .incbin "data/maps/battle/Internet.tilesetz" @ 0x564654
    .incbin "data/maps/battle/Internet.palettez" @ 0x5648D0
    .incbin "data/maps/battle/Internet.tilemapz" @ 0x5649F4
    .incbin "data/maps/battle/Generic.tilesetz" @ 0x564EF4
    .incbin "data/maps/battle/Generic.palettez" @ 0x565124
    .incbin "data/maps/battle/Generic.tilemapz" @ 0x565248
    .incbin "data/maps/battle/LanHP.tilesetz" @ 0x565750
    .incbin "data/maps/battle/LanHP.palettez" @ 0x5659AC
    .incbin "data/maps/battle/LanHP.tilemapz" @ 0x565AD0
    .incbin "data/maps/battle/MaylHP.tilesetz" @ 0x565FD8
    .incbin "data/maps/battle/MaylHP.palettez" @ 0x566260
    .incbin "data/maps/battle/MaylHP.tilemapz" @ 0x566384
    .incbin "data/maps/battle/YaiHP.tilesetz" @ 0x566898
    .incbin "data/maps/battle/YaiHP.palettez" @ 0x566A7C
    .incbin "data/maps/battle/YaiHP.tilemapz" @ 0x566BA0
    .incbin "data/maps/battle/DexHP.tilesetz" @ 0x5670B0
    .incbin "data/maps/battle/DexHP.palettez" @ 0x567410
    .incbin "data/maps/battle/DexHP.tilemapz" @ 0x567534
    .incbin "data/maps/battle/HikariHP.tilesetz" @ 0x567AA4
    .incbin "data/maps/battle/HikariHP.palettez" @ 0x567CD4
    .incbin "data/maps/battle/HikariHP.tilemapz" @ 0x567DF8
    .incbin "data/maps/battle/SalHP.tilesetz" @ 0x568300
    .incbin "data/maps/battle/SalHP.palettez" @ 0x5684C0
    .incbin "data/maps/battle/SalHP.tilemapz" @ 0x5685E4
    .incbin "data/maps/battle/MiyuHP.tilesetz" @ 0x568AF0
    .incbin "data/maps/battle/MiyuHP.palettez" @ 0x568CB4
    .incbin "data/maps/battle/MiyuHP.tilemapz" @ 0x568DD8
    .incbin "data/maps/battle/MasaHP.tilesetz" @ 0x5692E8
    .incbin "data/maps/battle/MasaHP.palettez" @ 0x56939C
    .incbin "data/maps/battle/MasaHP.tilemapz" @ 0x5694C0
    .incbin "data/maps/battle/LifeVirus.tilesetz" @ 0x56999C
    .incbin "data/maps/battle/LifeVirus.palettez" @ 0x569A40
    .incbin "data/maps/battle/LifeVirus.tilemapz" @ 0x569B64

    .incbin "data/maps/offline/ACDC_Elementary/map_56A038.scb" @ 0x56A038
    .incbin "data/maps/offline/ACDC_Elementary/map_56AAD4.scb" @ 0x56AAD4
    .incbin "data/maps/offline/ACDC_Elementary/map_56B55C.scb" @ 0x56B55C
    .incbin "data/maps/offline/ACDC_Elementary/map_56C38C.scb" @ 0x56C38C
    .incbin "data/maps/offline/ACDC_Elementary/map_56C880.scb" @ 0x56C880
    .incbin "data/maps/offline/ACDC_Elementary/map_56D314.scb" @ 0x56D314
    .incbin "data/maps/offline/ACDC_Elementary/map_56DD8C.scb" @ 0x56DD8C
    .incbin "data/maps/offline/ACDC_Elementary/map_56E684.scb" @ 0x56E684
    .incbin "data/maps/offline/ACDC_Elementary/map_56E94C.scb" @ 0x56E94C
    .incbin "data/maps/offline/ACDC_Elementary/map_56EEA0.scb" @ 0x56EEA0
    .incbin "data/maps/offline/ACDC_Elementary/map_56F084.scb" @ 0x56F084
    .incbin "data/maps/offline/ACDC_Elementary/map_56F604.scb" @ 0x56F604
    .incbin "data/maps/offline/ACDC_Elementary/map_5707EC.scb" @ 0x5707EC
    .incbin "data/maps/offline/ACDC_Town/map_570A60.scb" @ 0x570A60
    .incbin "data/maps/offline/ACDC_Town/map_574080.scb" @ 0x574080
    .incbin "data/maps/offline/ACDC_Town/map_574A2C.scb" @ 0x574A2C
    .incbin "data/maps/offline/ACDC_Town/map_5751D0.scb" @ 0x5751D0
    .incbin "data/maps/offline/ACDC_Town/map_5754A8.scb" @ 0x5754A8
    .incbin "data/maps/offline/ACDC_Town/map_575C98.scb" @ 0x575C98
    .incbin "data/maps/offline/ACDC_Town/map_5761A8.scb" @ 0x5761A8
    .incbin "data/maps/offline/ACDC_Town/map_57663C.scb" @ 0x57663C
    .incbin "data/maps/offline/ACDC_Town/map_576C60.scb" @ 0x576C60
    .incbin "data/maps/offline/ACDC_Town/map_577280.scb" @ 0x577280
    .incbin "data/maps/offline/ACDC_Town/map_577770.scb" @ 0x577770
    .incbin "data/maps/offline/Govt_Complex/map_57793C.scb" @ 0x57793C
    .incbin "data/maps/offline/Govt_Complex/map_578BB8.scb" @ 0x578BB8
    .incbin "data/maps/offline/Govt_Complex/map_578FB0.scb" @ 0x578FB0
    .incbin "data/maps/offline/Govt_Complex/map_57A3B0.scb" @ 0x57A3B0
    .incbin "data/maps/offline/Govt_Complex/map_57B814.scb" @ 0x57B814
    .incbin "data/maps/offline/Govt_Complex/map_57C4A0.scb" @ 0x57C4A0
    .incbin "data/maps/offline/Govt_Complex/map_57D2A8.scb" @ 0x57D2A8
    .incbin "data/maps/offline/Govt_Complex/map_57DAA8.scb" @ 0x57DAA8
    .incbin "data/maps/offline/Govt_Complex/map_57E6DC.scb" @ 0x57E6DC
    .incbin "data/maps/offline/Govt_Complex/map_57E994.scb" @ 0x57E994
    .incbin "data/maps/offline/DenTown/map_57F160.scb" @ 0x57F160
    .incbin "data/maps/offline/DenTown/map_581924.scb" @ 0x581924
    .incbin "data/maps/offline/DenTown/map_581D30.scb" @ 0x581D30
    .incbin "data/maps/offline/DenTown/map_583404.scb" @ 0x583404
    .incbin "data/maps/offline/DenTown/map_584CC0.scb" @ 0x584CC0
    .incbin "data/maps/offline/DenTown/map_5864D0.scb" @ 0x5864D0
    .incbin "data/maps/offline/DenTown/map_587ACC.scb" @ 0x587ACC
    .incbin "data/maps/offline/DenTown/map_587E00.scb" @ 0x587E00
    .incbin "data/maps/offline/SciLab/map_58853C.scb" @ 0x58853C
    .incbin "data/maps/offline/SciLab/map_588C00.scb" @ 0x588C00
    .incbin "data/maps/offline/SciLab/map_58A988.scb" @ 0x58A988
    .incbin "data/maps/offline/SciLab/map_58AFF0.scb" @ 0x58AFF0
    .incbin "data/maps/offline/SciLab/map_58B330.scb" @ 0x58B330
    .incbin "data/maps/offline/SciLab/map_58BCB0.scb" @ 0x58BCB0
    .incbin "data/maps/offline/WWW_Base/map_58BFF8.scb" @ 0x58BFF8
    .incbin "data/maps/offline/WWW_Base/map_58D42C.scb" @ 0x58D42C
    .incbin "data/maps/offline/WWW_Base/map_58DCA8.scb" @ 0x58DCA8
    .incbin "data/maps/offline/WWW_Base/map_58E4D4.scb" @ 0x58E4D4
    .incbin "data/maps/offline/WWW_Base/map_58EAA4.scb" @ 0x58EAA4
    .incbin "data/maps/offline/WWW_Base/map_58F058.scb" @ 0x58F058
    .incbin "data/maps/online/SchoolComp/map_58F5C8.scb" @ 0x58F5C8
    .incbin "data/maps/online/SchoolComp/map_590FF8.scb" @ 0x590FF8
    .incbin "data/maps/online/SchoolComp/map_593D9C.scb" @ 0x593D9C
    .incbin "data/maps/online/SchoolComp/map_5949D8.scb" @ 0x5949D8
    .incbin "data/maps/online/SchoolComp/map_595F10.scb" @ 0x595F10
    .incbin "data/maps/online/OvenComp/map_596C9C.scb" @ 0x596C9C
    .incbin "data/maps/online/OvenComp/map_5985C4.scb" @ 0x5985C4
    .incbin "data/maps/online/WaterworksComp/map_599A28.scb" @ 0x599A28
    .incbin "data/maps/online/WaterworksComp/map_59BD44.scb" @ 0x59BD44
    .incbin "data/maps/online/WaterworksComp/map_59EBA0.scb" @ 0x59EBA0
    .incbin "data/maps/online/WaterworksComp/map_5A427C.scb" @ 0x5A427C
    .incbin "data/maps/online/WaterworksComp/map_5A9F50.scb" @ 0x5A9F50
    .incbin "data/maps/online/WaterworksComp/map_5B1478.scb" @ 0x5B1478
    .incbin "data/maps/online/TrafficLight_Comp/map_5B64D0.scb" @ 0x5B64D0
    .incbin "data/maps/online/TrafficLight_Comp/map_5B82F4.scb" @ 0x5B82F4
    .incbin "data/maps/online/TrafficLight_Comp/map_5BA740.scb" @ 0x5BA740
    .incbin "data/maps/online/TrafficLight_Comp/map_5BE13C.scb" @ 0x5BE13C
    .incbin "data/maps/online/TrafficLight_Comp/map_5C05DC.scb" @ 0x5C05DC
    .incbin "data/maps/online/Power_Plant_Comp/map_5C2A2C.scb" @ 0x5C2A2C
    .incbin "data/maps/online/Power_Plant_Comp/map_5C7B08.scb" @ 0x5C7B08
    .incbin "data/maps/online/Power_Plant_Comp/map_5C9FF8.scb" @ 0x5C9FF8
    .incbin "data/maps/online/Power_Plant_Comp/map_5CD228.scb" @ 0x5CD228
    .incbin "data/maps/online/WWW_Comp/map_5CFF6C.scb" @ 0x5CFF6C
    .incbin "data/maps/online/WWW_Comp/map_5D1B54.scb" @ 0x5D1B54
    .incbin "data/maps/online/WWW_Comp/map_5D57A8.scb" @ 0x5D57A8
    .incbin "data/maps/online/WWW_Comp/map_5D9F4C.scb" @ 0x5D9F4C
    .incbin "data/maps/online/WWW_Comp/map_5DB4A8.scb" @ 0x5DB4A8
    .incbin "data/maps/online/WWW_Comp/map_5DE704.scb" @ 0x5DE704
    .incbin "data/maps/online/ACDC_HP/map_5DED58.scb" @ 0x5DED58
    .incbin "data/maps/online/ACDC_HP/map_5DEFE4.scb" @ 0x5DEFE4
    .incbin "data/maps/online/ACDC_HP/map_5E0C24.scb" @ 0x5E0C24
    .incbin "data/maps/online/ACDC_HP/map_5E1C18.scb" @ 0x5E1C18
    .incbin "data/maps/online/Govt_Complex_HP/map_5E22A8.scb" @ 0x5E22A8
    .incbin "data/maps/online/Govt_Complex_HP/map_5E27D8.scb" @ 0x5E27D8
    .incbin "data/maps/online/DenTown_HP/map_5E2F20.scb" @ 0x5E2F20
    .incbin "data/maps/online/Govt_Complex_HP_2/map_5E384C.scb" @ 0x5E384C
    .incbin "data/maps/online/Other/Generic.scb" @ 0x5E41F8
    .incbin "data/maps/online/Internet/map_5E4604.scb" @ 0x5E4604
    .incbin "data/maps/online/Internet/map_5E774C.scb" @ 0x5E774C
    .incbin "data/maps/online/Internet/map_5ED608.scb" @ 0x5ED608
    .incbin "data/maps/online/Internet/map_5F1E54.scb" @ 0x5F1E54
    .incbin "data/maps/online/Internet/map_5F5548.scb" @ 0x5F5548
    .incbin "data/maps/online/Internet/map_5F8100.scb" @ 0x5F8100
    .incbin "data/maps/online/Internet/map_5FA53C.scb" @ 0x5FA53C
    .incbin "data/maps/online/Internet/map_5FCB14.scb" @ 0x5FCB14
    .incbin "data/maps/online/Internet/map_5FFEE0.scb" @ 0x5FFEE0
    .incbin "data/maps/online/Internet/map_6017A8.scb" @ 0x6017A8
    .incbin "data/maps/online/Internet/map_604AB4.scb" @ 0x604AB4
    .incbin "data/maps/online/Internet/map_6074E0.scb" @ 0x6074E0
    .incbin "data/maps/online/Internet/map_609B64.scb" @ 0x609B64
    .incbin "data/maps/online/Internet/map_60AD44.scb" @ 0x60AD44
    .incbin "data/maps/online/Internet/map_60DE5C.scb" @ 0x60DE5C
    .incbin "data/maps/online/Internet/map_6109C0.scb" @ 0x6109C0

    .end
