    .include "constants.inc"
    .include "macros.inc"

    .text

    .include "images/oam.inc"
    .include "images/sprite.inc"
    .include "data/maps/graphic_data.inc"
    .include "images/ui.inc"
    .include "images/portrait.inc"
    .include "images/battle_ui.inc"
    .include "images/passcode.inc"
    .include "images/battle.inc"
    .include "images/pet.inc"

    .include "text/battlechip.inc"
    .include "text/item.inc"
    .include "text/talk.inc"
    .include "text/dialogue.inc"
    .include "text/scenario.inc"
    .include "text/tutorial.inc"
    .include "images/transition.inc"

    .include "data/maps/area_data.inc"

    .end