#include "offsets.h"
    .include "constants.inc"
    .include "macros.inc"


global_label BgTask_804FD64
    task_tileset slot=0, src=tileset_0791AB4, dst=0x6000020, count=0x10, bufIndex=25, delay=240
    task_tileset_arg TilemapEntry_804EE78_0
    task_tileset_arg TilemapEntry_804EE78_1, 32
    task_tileset_arg TilemapEntry_804EE78_2, 4
    task_tileset_arg TilemapEntry_804EE78_1, 4
    task_tileset_arg TilemapEntry_804EE78_2, 4
    task_tileset_arg TilemapEntry_804EE78_1, 4
    task_tileset_arg TilemapEntry_804EE78_2, 4
    task_tileset_arg TilemapEntry_804EE78_1, 4
    task_tileset_arg TilemapEntry_804EE78_2, 4
    task_tileset_arg TilemapEntry_804EE78_1, 4
    task_tileset_arg TilemapEntry_804EE78_2, 4
    task_tileset_arg TilemapEntry_804EE78_3, 120
    task_repeat

