#include "offsets.h"
    .include "constants.inc"
    .include "macros.inc"


global_label BgTask_804FD64
    task_tileset 0, 0x8791AB4, 0x6000020, 0x10, 25, 240
    task_tileset_arg 0x804EE78
    task_tileset_arg 0x804EE98, 32
    task_tileset_arg 0x804EEB8, 4
    task_tileset_arg 0x804EE98, 4
    task_tileset_arg 0x804EEB8, 4
    task_tileset_arg 0x804EE98, 4
    task_tileset_arg 0x804EEB8, 4
    task_tileset_arg 0x804EE98, 4
    task_tileset_arg 0x804EEB8, 4
    task_tileset_arg 0x804EE98, 4
    task_tileset_arg 0x804EEB8, 4
    task_tileset_arg 0x804EED8, 120
    task_repeat

